grpc/grpc-node

packages/grpc-js/package.json
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/subchannel.ts

Apparently #1842 somehow failed to add any new logs to the trace output for the error reported in #1841. These new logs should guarantee that we see at least one new log line. In particular, in `http_proxy.ts`, in `getProxiedConnection`, every `reject` and `resolve` now has a corresponding log or trace log line, so we should always be able to see how that function finished.

grpc-js: Add more trace logging around establishing connections

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

The goal is to give more immediate feedback for errors like the one reported in #1850. Currently if the user passes an object of the wrong type, the error when it is used occurs asynchronously, which loses relevant context and results in a less-helpful error message.

grpc-js: Tighten server.bindAsync creds typecheck

---

packages/grpc-js/src/index.ts

I want to have a way to proactively answer the question "Are you sure you're using the right version of the library?"

grpc-js: Add trace log with library version

---

packages/grpc-native-core/index.d.ts

This is for compatibility with grpc-js, which does not have a type argument in its `ServiceDefinition`. Making the argument optional shouldn't break any existing code.
I think this is the simplest way to fix #1766, and since we need to do another release anyway this seems like the best time to do it.

grpc: Make ServiceDefinition type argument optional

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/generated/google/protobuf/EnumOptions.ts
packages/grpc-js-xds/src/generated/google/protobuf/EnumValueOptions.ts
packages/grpc-js-xds/src/generated/google/protobuf/FieldOptions.ts
packages/grpc-js-xds/src/generated/google/protobuf/FileOptions.ts
packages/grpc-js-xds/src/generated/google/protobuf/MessageOptions.ts
packages/grpc-js-xds/src/generated/typed_struct.ts
packages/grpc-js-xds/src/generated/udpa/type/v1/TypedStruct.ts
packages/grpc-js-xds/src/http-filter.ts
packages/grpc-js-xds/src/http-filter/router-filter.ts
packages/grpc-js-xds/src/index.ts
packages/grpc-js-xds/src/protobuf-any.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/route-action.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/filter-stack.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/subchannel.ts

This is an implementation of [gRFC A39](https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md). On the grpc-js side, this adds the `dynamicFilterFactories` field to the `CallConfig` type, which is returned by a `ConfigSelector` function. These dynamic filters are run between name resolution and load balancing, i.e. as early as possible after getting a `ConfigSelector`. The name comes from grpc/grpc#24920.
On the grpc-js-xds side, this adds handling in the xDS resolver for the various HTTP filter fields, and uses them to create filters as specified that are passed along as dynamic filters.

grpc-js-xds: Add HTTP Filters support

---

packages/grpc-js/src/call-stream.ts

This should fix #1094. In [the status codes usage doc](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) this event is in the category
> Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks

grpc-js: Handle errors thrown by writing to http2 stream

---

packages/grpc-js/package.json
packages/grpc-js/src/server-call.ts

This fixes #1871, according to the person who filed the issue.

grpc-js: Check for closed server stream before sending

---

packages/grpc-js/src/call-stream.ts

It was reported in https://github.com/grpc/grpc-node/issues/1769#issuecomment-894822111 that users see this error sometimes, and it means that from the client point of view, it looks like the connection dropped in the middle of a stream, so this is the proper code and it can make error handling smoother.

grpc-js: Map ETIMEDOUT errors to UNAVAILABLE

---

packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts

The main purpose of this change is to implement the following line of [proposal A39](https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md):
> gRPC will support HTTP filters in xDS v3 only. Filters will continue to be ignored when speaking xDS v2.

grpc-js-xds: Distinguish v2 and v3 when handling messages

---

packages/grpc-js-xds/README.md

This is in preparation for the next release. A29 is not implemented; I didn't skip it by accident.

grpc-js-xds: Update readme feature list

---

TROUBLESHOOTING.md

Fixed typo of 'support' inside [TROUBLESHOOTING.md](https://github.com/grpc/grpc-node/blob/master/TROUBLESHOOTING.md)
- Duplicate of #1874 
Please have a look @murgatroid99

fix(docs): supporst ⟶ supports

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

I ran into this problem when generating code for [channelz.proto](https://github.com/grpc/grpc-proto/blob/master/grpc/channelz/v1/channelz.proto), because the service has a `GetChannel` method.

proto-loader: Avoid generating conflicting method names in service clients

---

packages/grpc-js/src/http_proxy.ts

my corporate proxy requires the Host header to be defined to the target host, orelse it returns a 403 error

adds sometimes required Host header to proxy connection

---

packages/grpc-js/src/http_proxy.ts

Backport #1900 to the 1.4.x branch.

grpc-js: adds sometimes required Host header to proxy connection

---

packages/grpc-js-xds/src/xds-client.ts

We need this to correlate client logs with TD logs. (PR for 1.4.x)

grpc-js-xds: Log loaded bootstrap info in xDS client (1.4.x)

---

packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Log loaded bootstrap info in xDS client (1.3.x)

---

packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Log loaded bootstrap info in xDS client (1.2.x)

---

packages/grpc-js/src/channel.ts

The original reason for having this requirement in the old library was for compatibility with the corresponding core type. That got carried over, but there's no real reason now to keep enforcing it, and the presence of this requirement creates a restriction that is unusual in JavaScript that prevents a wrapping library from blindly passing along an options object so that the lower-level library can simply use any options that it considers relevant. In fact, gRPC channel options are already deliberately namespaced, which makes blindly passing options even more reasonable.
In short, I want to eliminate the need for code like in googleapis/gax-nodejs#1115

grpc-js: Loosen requirements on channel option types

---

packages/grpc-js-xds/interop/xds-interop-client.ts

If you call `array.splice(-1, 1)`, it will delete the last item in the list, which is not the desired outcome here. I don't know if this can actually happen, but it's better to be safe than sorry.

grpc-js-xds: fix use of splice in interop test code

---

packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/xds-bootstrap.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js/src/server.ts

This fixes a few different things for the xDS tests:
- Enable source maps, so that error messages point to TS file lines.
- Ensure that the `serverFeatures` field in the bootstrap file is always set, as the type specifies
- Improve error handling and reporting in the xDS client async initialization code
- Report specific errors when servers fail to bind ports.

grpc-js-xds: A few fixes for xDS tests

---

packages/grpc-js-xds/src/xds-client.ts

The `error` event does not fire if a call does not end with an error, i.e. if it ends with the OK status.

grpc-js-xds: Handle all ways control-plane streams can end

---

packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Handle all ways control-plane streams can end (1.3.x)

---

packages/grpc-js-xds/package.json

I think #1910 and #1921 are worth publishing as a patch.

grpc-js-xds: Bump to 1.3.2

---

packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

First, this adds square brackets around the list of received names so that if the list is empty, it's clear that something was supposed to be there, and second, this fixes the LDS resource log to actually say "LDS" instead of "RDS".

grpc-js-xds: Improve received resource list logging

---

packages/grpc-js/src/channelz.ts

I realized that `Buffer.from` assumes that its inputs are separated into bytes, but the previous parsing code wasn't doing that, so it was getting the wrong numbers.

grpc-js: channelz: Fix algorithm for representing an IPv6 address in binary

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-channelz.ts

When I added support for that option I was a little overzealous with making code conditional and I accidentally made attaching an http2 stream to a call conditional on channelz being enabled. There is now a test that the basic functionality still works with that option set.

grpc-js: Fix handling of grpc.enable_channelz option

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

That line shouldn't be there at all. It just creates an orphaned socket reference that can never be cleaned up.

grpc-js: Remove an extra call to registerChannelzSocket

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/google/longrunning/Operations.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/Echo.ts
packages/proto-loader/package.json

This fixes #1966. The previous generated callback type doesn't match the actual behavior or type definitions of the gRPC libraries. Both libraries export the `requestCallback` type, so this will work with both. I don't see this as a breaking change because code that depended on the wrong parts of the previous generated types wouldn't work correctly anyway.

proto-loader: Fix generated types for callbacks

---

packages/grpc-js/src/channel-credentials.ts

This adds all of the certificate info that Node can provide to the object passed to the `checkServerIdentity` callback. The previous restriction was for compatibility with the `grpc` package, but with the deprecation of that package that is less valuable. This is a non-breaking change because it only adds properties to the object that is provided to the API user.
This PR accomplishes essentially the same thing as #1866. I requested some changes in that PR and the contributor never responded, and now there is additional demand for this improvement in #1965, so I did it myself.

grpc-js: Provide full certificate in `checkServerIdentity` callback

---

packages/grpc-js/src/channel-credentials.ts

This is a fix for #1968. Unconditionally setting the option to `verifyOptions?.checkServerIdentity` sets the value to `undefined` if the original value is unset. Node (at least in version 10) asserts that the value is a function if it is set, so this causes an assertion error.

grpc-js: Don't pass undefined checkServerIdentity

---

packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

This is the Node version of grpc/grpc#28128. The code that is being removed here is redundant with the code that removes a resource when its last watcher is removed, which will happen anyway in situations when the parent resource no longer refers to it.

grpc-js-xds: Remove LDS and CDS code for removing RDS and EDS entries

---

packages/grpc-js-xds/src/csds.ts

The absence of those paths was causing warnings but not errors.

grpc-js-xds: Include additional paths when loading csds protos

---

packages/grpc-js/package.json
packages/grpc-js/src/server-call.ts
packages/grpc-js/test/test-client.ts
packages/grpc-js/test/test-resolver.ts
packages/grpc-js/test/test-server.ts
packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json
run-tests.bat
test/api/connectivity_test.js
test/gulpfile.ts

This skips three groups of tests:
1. All tests against the native library on Node versions 14 and greater. The purpose of those tests is to test that grpc-js is interoperable and behaviorally consistent with the native library, not to test the function of the native library itself. That fails if the native library itself is not behaving correctly, so it's best to skip the tests where that is the case. We are still testing that in Node versions 10 and 12.
2. The `NoCompress` flag test. We currently use the `encoding` argument of the `write` method to pass write flags in. This is not supported functionality, but it has worked for a long time. However, Node 16 apparently added validation for that argument, and any flags we pass in are not considered valid. So, that now does not work at all, …

Make changes to make all of the test jobs green

---

packages/grpc-js/src/resolving-load-balancer.ts

Send the BackoffOptions to the BackoffTimeout just as in **subchannel.ts, line 221**. Without this code, **grpc.initial_reconnect_backoff_ms** and **grpc.max_reconnect_backoff_ms** are not used at all in the gRPC client and the retry will always use the default values (1000 and 120000)

grpc-js: Send backoffOptions to BackoffTimeout

---

packages/grpc-js/package.json

The main thing was moving `@types/semver` from `dependencies` to `devDependencies`, because it is only used in the `gulpfile`, as pointed out in https://github.com/grpc/grpc-node/issues/1955#issuecomment-988926285. I also removed `yargs` because I couldn't find any other reference to it in this package.

grpc-js: Clean up some dependencies

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/client-interceptors.ts

The code already existed to ensure that the status/halfClose comes after the last message when interceptors do async processing. This change extends that to ensure that metadata is processed before both of those.
I also added handling for a call trying to output a status before the `start` method is called. Now the status waits for that, instead of getting sent into the void.
This fixes #1984 and #1985.

grpc-js: Preserve order of metadata, messages, and call end with async interceptors

---

packages/grpc-js-xds/scripts/xds.sh

[Backport][@grpc/grpc-js@1.4.x] use xds-test-server-5

---

packages/grpc-js-xds/scripts/xds.sh

[Backport][@grpc/grpc-js@1.3.x] use xds-test-server-5

---

packages/grpc-js-xds/scripts/xds.sh

[Backport][@grpc/grpc-js@1.2.x] use xds-test-server-5

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

This fixes #1995. Yargs 17 makes the `argv` object possibly a `Promise`, and the simplest way to make TypeScript OK with accessing its properties is to `await` it.

proto-loader: Update yargs to version 17

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

This is mostly reversing #2006, but I put a tighter version range on `yargs` this time. `yargs` 17 drops compatibility with Node 10, which causes problems because we test on Node 10. #1995 is still fixed: `npm audit` shows no problems with this new dependency.

Decrease dependency to yargs 16 for compatibility with Node <12

---

packages/grpc-js/src/object-stream.ts
packages/grpc-js/src/server-call.ts

Backport of #2007. We're not going to publish another 1.3 version, but we need this for xDS tests.

grpc-js: Fix compatibility with @types/node 17.0.6 (1.3.x)

---

packages/grpc-js/src/object-stream.ts
packages/grpc-js/src/server-call.ts

grpc-js: Fix compatibility with @types/node 17.0.6 (1.2.x)

---

packages/grpc-js/README.md

I found the [doc](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js#supported-channel-options) is outdated,  the `grpc-node.max_session_memory` options is missing.
_Originally posted by @NeoyeElf in https://github.com/grpc/grpc-node/issues/1666#issuecomment-1007093753_

 added grpc-node.max_session_memory to js docs

---

packages/grpc-js/README.md
packages/grpc-js/src/channel-options.ts

This is an expansion on #2015 to include other options that were added but not added to the documentation.

grpc-js: Document recently-added channel options

---

packages/grpc-js/src/make-client.ts

Currently neither `serviceName` nor `classOptions` are not used in `makeClientConstructor` at all. In some cases it is very handy to access at least `serviceName` in generated class to identify which service exactly generated class belongs to.

grpc-js: Set provided class options to generated class

---

packages/grpc-js-xds/package.json

Extension files are also referenced in the grpc-js-xds code https://github.com/grpc/grpc-node/blob/master/packages/grpc-js-xds/src/resources.ts#L68, so they need to be included when grpc-js-xds is installed as a dependency.

Add envoy/extensions files

---

packages/grpc-js-xds/package.json

Backport #2018 to the 1.5.x branch to publish a patch.

grpc-js-xds: Add envoy/extensions files in 1.5.x

---

packages/grpc-js/src/http_proxy.ts

The environment variable `http_proxy` will be used for UDS connections which prevents the connection from working. Since UDS runs on the local machine there's no use for a sending it through a proxy. This pull request adds a check which disables the http proxy if the target is a Unix Domain Socket.

grpc-js: Don't use http_proxy for uds connections

---

packages/grpc-js/package.json
packages/grpc-js/src/resolver-dns.ts

This change is to address the increased DNS resolution traffic when using round robin reported in #2023. With this change, any single channel will space out DNS requests based on the configured connection backoff settings.

grpc-js: Add backoff to DNS resolution attempts

---

packages/grpc-js/package.json
packages/grpc-js/src/server.ts

This fixes #2026. nodejs/node#35824 indicates that this is not handled internally by Node, and that we have to handle this error.

grpc-js: Add secureConnection error handling in server

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/test/test-local-subchannel-pool.ts

This fixes a bug that would cause a null reference exception when closing a channel that used a local subchannel pool.

grpc-js: Fix pick first shutdown reference handling

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/resolver-dns.ts

This should fix #2031. The main issue was the code in `load-balancer-child-handler.ts`: it's just a copy/paste error, and the result is that calls to `exitIdle` would not be propagated to child LB policies. That meant that when a new call tried to kick an IDLE LB policy, it would not happen, and it would only eventually leave IDLE when it got a new address list from the resolver. This problem was exacerbated by the missing `backoff.reset` call in `dns-resolver.ts`. The backoff is meant to wait an increasing amount of time after each failure, but because it was not reset there it would also wait an increasing amount of time after each successful IP address resolution.

grpc-js: Fix `exitIdle` propagation and DNS IP result backoff

---

packages/grpc-js/src/logging.ts
packages/grpc-js/src/subchannel.ts

This adds HTTP/2 settings frame information to debug logs.
HTTP/2 settings frame contains important information like max_concurrent_streams and initial_window_size useful for debugging concurrency, latency, and throughput issues.

Add HTTP/2 settings frame tracing

---

doc/environment_variables.md
packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

This adds yet another `subchannel_*` tracer, and they could probably be consolidated, but for now I just want to get this out. This will test a guess I have about the cause of #2049.

grpc-js: Add session state logging at call start

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server.ts

Migrating from `grpc` to `@grpc/grpc-js` I missed the part where `Server.bind` was not implemented. The TypeScript type-checker would've caught my mistake if the return type was set as `never`.
I think it would be accurate to have their return types be `never` until implemented https://www.typescriptlang.org/docs/handbook/2/functions.html#never

grpc-js: Return never from functions that always throw

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/subchannel.ts

The idea here is that every trace that references a subchannel should include the subchannel ID number, and every trace that references a specific call stream should include that call stream's ID number. I think I accomplished that.

grpc-js: Consistently log subchannel and call IDs in traces

---

packages/grpc-js/gulpfile.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/duration.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/service-config.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-outlier-detection.ts

This implements the non-xDS part of [gRFC A50](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md). I also needed to add the subchannel interface and wrapper that that spec refers to. Other languages already had that.
The most important new code is in `load-balancer-outlier-detection.ts`.
Currently the only test is a simple regression test verifying that the client functions normally when the `outlier_detection` LB policy is configured. The test file has the machinery for other tests, but I don't know how to implement those yet. As mentioned in the spec, the ability to use the `outlier_detection` LB policy is disabled by default, and enabled only if the corresponding environment variable is set. That layer of protection will be removed when there is enough testing, …

grpc-js: Add outlier detection LB policy

---

test/interop/interop_client.js

This might be related to the failure we're seeing in the latest test in grpc/grpc#29062 (https://source.cloud.google.com/results/invocations/db79eb34-916d-4c37-b14b-42aac68fc5b4/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_toprod/log). This change matches the code on line 483 of the same file.

Add credentials scope in oauth2_auth_token interop test

---

doc/environment_variables.md
packages/grpc-js/src/channel.ts

We want to figure out what is constructing all of the channels that are in use in a certain user's code, and this seems like the simplest way to do that.

grpc-js: Add channel construction stacktrace traces

---

packages/grpc-js/src/channel.ts

This adds transparent retry for the error "The session has been destroyed" when starting a call on a subchannel. The correspondence between that string and the error code in this code comes from https://github.com/nodejs/node/blob/a01302b8dfaa9aa6290cd6bee552c4ce30dca34c/lib/internal/errors.js#L1031

grpc-js: Transparently retry session destroyed error

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

The current code can output a spurious extra trace if a call is cancelled after it succeeds. That extra trace is misleading because the call does not actually end with that second status code.

grpc-js: Trace call end when actually ending the call

---

packages/grpc-js/package.json
packages/grpc-js/src/server.ts

When I originally added the `channelzEnabled` option, it looks like I missed having it guard some code in the server for some reason. I did a more exhaustive search this time and I'm pretty sure I got everything. This should fix #2068 in particular with the bottom change: that `registerChannelzSocket` call was unguarded, but the corresponding `unregisterChannelzRef` call was guarded, which meant that registered sockets would pile up indefinitely.

grpc-js: Improve coverage of channelzEnabled checks in server code

---

packages/grpc-js/src/index.ts

Since Metadata is exposed and its constructor takes MetadataOptions, those should also be exposed.

Expose MetadataOptions interface in grpc-js.

---

packages/grpc-js/README.md
packages/grpc-js/package.json
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/resolver-dns.ts

This adds a delay after a successful DNS request before another DNS request can be started, configurable with the `grpc.dns_min_time_between_resolutions_ms` channel arg, defaulting to 30 seconds. This all matches the current behavior of the C core.

grpc-js: Add support for `grpc.dns_min_time_between_resolutions_ms` channel arg

---

packages/grpc-js/src/channel.ts
packages/grpc-js/src/channelz.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts

Channelz IDs for channels, subchannels, and servers also serve as entity IDs in trace logs. The current behavior creates a dummy ref with the ID -1 when channelz is disabled, but that makes different entities indistinguishable in trace logs. With this change, instead a channelz ref is created as usual but no corresponding channelz data is created or stored.

grpc-js: Use real channelz IDs when channelz is disabled

---

packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Don't stop backoff timers for LRS streams

---

packages/grpc-js-xds/src/xds-client.ts

The various `{ads,lrs}NodeV{2,3}` fields are all populated from the same information in the bootstrap file, so it is valid to pick one specific one to grab the Node ID.

grpc-js-xds: Include Node ID in XdsClient status errors

---

packages/grpc-js-xds/src/xds-stream-state/eds-state.ts

This change updates the validation logic to follow grpc/proposal#295

grpc-js-xds: Reject EDS updates with duplicate locality/priority pairs

---

packages/grpc-js/src/subchannel.ts

By default, we don't send pings when there are no active streams because some servers don't like that. But that doesn't mean that existing pending pings should be invalidated when the last stream ends. This change fixes that. I changed this line instead of changing `stopKeepalivePings` because there are two other call sites of `stopKeepalivePings` that should have the other behavior.

grpc-js: Don't clear ping timeout when still connected

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

The `grpc-node.max_session_memory` option was added in #1666 to configure Node's per-session memory limit. Recent testing related to https://github.com/googleapis/nodejs-firestore/issues/1023#issuecomment-1079149229 indicate that Node's behavior degrades in an undesirable and possibly buggy way when this limit is reached. To fix that behavior this change disables that limit by default.

grpc-js: Disable per-session memory limit by default

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-client.ts

This fixes #2090. The change to the channel here is just to track name resolution errors so that if a call comes in while the channel is in TRANSIENT_FAILURE, backing off waiting to resolve again, we end the call with an error, the same as if the LB policy was in TRANSIENT_FAILURE. The change to the resolving load balancer just lets the `exitIdle` schedule another name resolution attempt if the state is TRANSIENT_FAILURE, which is consistent with handling of `exitIdle` and backoffs in other places. I removed the state transition from there because it is redundant with the one in `updateResolution`, and inappropriate when not calling that function immediately. I also moved the backoff timer start to the start of name resolution instead of the end, for consistency with other backoff timers.

grpc-js: Fix handling of calls after resolution failure

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/resolving-load-balancer.ts

This fixes #2094. `childLoadBalancer.exitIdle()` can cause a state change, which results in failing the check to re-resolve.
There is another problem that `PickFirstLoadBalancer` has a code path to call `requestReresolution`, but it may actually be unreachable because the logic there is kind of convoluted. It would be good to fix that, but for now, it's worth getting this quick fix out.

grpc-js: Consistently re-resolve when idle

---

packages/grpc-js/src/resolver-dns.ts

The purpose of that field is to indicate that a request to update the name resolution has come in while the resolver is in a period when it is waiting before making the next resolution attempt, so that when it is done waiting, it starts the next attempt immediately. It needs to be unset then so that it can have the correct meaning in the next waiting period.
Pointed out in https://github.com/grpc/grpc-node/issues/2080#issuecomment-1100763866

grpc-js: DNS: unset continueResolving when starting a resolution attempt

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

We assume that when a keepalive ping times out, that means that the connection is gone. So we should also not expect that any existing calls will make progress, so we should just end them instead of waiting for their deadlines to expire, if they even have one. This change matches the behavior of other languages like Java: https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/core/src/main/java/io/grpc/internal/KeepAliveManager.java#L287-L289.

grpc-js: End calls when keepalive pings time out

---

packages/grpc-js/src/client.ts

For unary and client streaming requests, the client expects to get exactly one response message. We already report an error when the client receives more than one message. This change adds an error when the client receives 0 messages.
This addresses #2065 and #2101.

grpc-js: Report error when no message received for unary response

---

packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/resolver-dns.ts

As pointed out in https://github.com/grpc/grpc-node/issues/2080#issuecomment-1102136143, in some cases the backoff timer and next resolution timer could both trigger, causing double resolver attempts, double backoff timers, etc., which can then cause further proliferation of requests. So the fix here is to more consistently prevent new DNS requests while any DNS request is already running, and also clear timers before setting new ones.

grpc-js: Fix double resolver calls in DNS resolver

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts

This change makes the subchannel pool behave the same whether they are global or local. The main issue was that not calling `subchannel.ref` when creating the subchannel resulted in the subchannel shutting down but staying in the pool when its refcount reached 0, and then the pool could still use it. This is counter to the intention that a subchannel should only be shut down when it will never be used again. Once that is removed, the cleanup timer becomes useful to avoid filling the pool up with unused subchannels, and the result is that the `global` constructor parameter doesn't do anything anymore.
I also changed the subchannel shutdown behavior to transition to IDLE instead of TRANSIENT_FAILURE. In theory, both of those should be fine there because the important thing is closing and …

grpc-js: Fix shutting down subchannels in separate pools

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

This implements the changes described in grpc/proposal#297. I had to switch from `setInterval` to `setTimeout` because in some cases we need to start a shorter timer and then go back to running it for the full interval after that.

grpc-js: Update outlier detection to address recent spec changes

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

grpc-js: Fix mean calculation in outlier detection LB policy

---

packages/grpc-js/src/call.ts
packages/grpc-js/src/client.ts

This adds information to the stack traces of call status errors with the call stack of where the call was initiated.
This fixes #1810.
For example, with this change, a stack trace of an error in one of the tests looks like this:
```
Error: 14 UNAVAILABLE: Name resolution failed for target dns:host.invalid
at Object.callErrorFromStatus (/usr/local/google/home/mlumish/grpc-node/packages/grpc-js/src/call.ts:81:17)
at Object.onReceiveStatus (/usr/local/google/home/mlumish/grpc-node/packages/grpc-js/src/client.ts:352:36)
at Object.onReceiveStatus (/usr/local/google/home/mlumish/grpc-node/packages/grpc-js/src/client-interceptors.ts:462:34)
at Object.onReceiveStatus (/usr/local/google/home/mlumish/grpc-node/packages/grpc-js/src/client-interceptors.ts:424:48)
at …
```

grpc-js: Add calling context to call errors

---

packages/proto-loader/package.json

This fixes #2111. I tested this with long version 4 and 5 and it imports the same thing in both cases.

proto-loader: Don't force long@5

---

packages/proto-loader/package.json

This puts it back to the way it was before I started changing this, but leaves the change to the `import` line intact so that it is still compatible with 5.x. When I started this, I didn't realize that `long` 4.x actually has a separate `@types/long` package, but 5.x includes its types. TypeScript seems to prefer the included type information, so the types in 5.x would override the types for 4.x even if the user explicitly declared a dependency on `@types/long` 4.x.
This should fix #2113.

proto-loader: Switch `long` dependency back to 4.x

---

packages/grpc-js/src/subchannel.ts

I had a situation with 1 subchannel for multiple streams. If a keepalive timeout occured, it would not trigger a 'Connection dropped' for each stream.
I found a bug in the code that handles the disconnect listeners. The listener function itself can [remove itself from the array](https://github.com/bartslinger/grpc-node/blob/0a0e13eedecedb31e91ad2d250c5fca6f31e46b6/packages/grpc-js/src/call-stream.ts#L334). The removal [uses splice](https://github.com/bartslinger/grpc-node/blob/0a0e13eedecedb31e91ad2d250c5fca6f31e46b6/packages/grpc-js/src/subchannel.ts#L981). Thereby, the next item shifts one place and will not be called from the loop. This is a common problem and is usually handled by looping in reverse.

bugfix: handle disconnectListeners in reverse to allow listener removal in loop

---

packages/proto-loader/package.json

The package protobufjs before 6.11.3 are vulnerable to Prototype Pollution which can allow an attacker to add/modify properties of the Object.prototype.
This vulnerability can occur in multiple ways:
1. by providing untrusted user input to util.setProperty or to ReflectionObject.setParsedOption functions
2. by parsing/loading .proto files
Publish Date: 2022-05-27
URL: [CVE-2022-25878](https://vuln.whitesourcesoftware.com/vulnerability/CVE-2022-25878)

bump protobufjs to "^6.11.3"

---

packages/grpc-js/test/fixtures/test_service.proto
packages/grpc-js/test/generated/Response.ts
packages/grpc-js/test/generated/TestService.ts
packages/grpc-js/test/test-server.ts

We got a report by email that a user is experiencing a bug with the Node server and a different client where compressed messages would be delivered to the server application jumbled. This test creates a compressible message that compresses to a size large enough to span multiple HTTP/2 frames, and the server sends the same message back to the client to confirm that it received it intact.

grpc-js: Add a test for compressing large messages

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

These images are used in the staging tests, which don't build docker images themselves. The code for this is copied with slight modification from https://github.com/grpc/grpc/blob/1be6e2c9ebfb4a26bebe6b3f3c45cffc70e71b68/tools/internal_ci/linux/psm-security.sh#L46-L51

xDS k8s interop script: publish version-tagged docker images

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

The line copied from the Python script was hardcoded and not handled by a variable, so I did not change it on the first pass.

xDS k8s tests: fix a line in the url_map test script

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Docker auth needed to be done before pushing thats to the GCR.
Also add missing versioned image tagging to xds_k8s_url_map.sh.

xDS k8s tests: fix docker auth error in the build scripts

---

packages/grpc-js-xds/interop/Dockerfile

I did not notice that this earlier because the test jobs were not actually running the tests from the version branch.

Backport xDS k8s interop docker image to version branch (1.6.x)

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

These lines are copied from the other script. Without this the docker image ends up broken.

Clone submodules in xds k8s url map script

---

packages/proto-loader/package.json

Protobuf.js version 7.0.0 was released very recently, so this change picks it up. Note: for 0.x versions, the minor version acts like a major version, and users will need to explicitly change their dependencies to get the new version. I changed the minor version in this case because the proto-loader library delegates a lot of functionality to Protobuf.js, so there is a lot of potential for delegated breakage.

proto-loader: Update protobufjs dependency to 7.x

---

packages/grpc-js/package.json

This is a follow up to #2167. Now that the new version of `@grpc/proto-loader` has been released, this updates grpc-js to use it.

grpc-js: Update proto-loader dependency to ^0.7.0

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

It turns out that I made the same error I fixed in #2108 in the standard deviation calculation too.

grpc-js: Outlier detection: Fix standard deviation calculation

---

packages/grpc-js-xds/interop/Dockerfile
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts

The main change here is adding trace logging, modeled heavily on the logs added to the core implementation in grpc/grpc#30239. I also made the changes described in grpc/proposal#315, and I made the unwrapping of the subchannel in the wrapper more consistent.

grpc-js: Add outlier detection tracing and enable it in interop tests, plus some other changes

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

The `ejected` state overrides the reported connectivity state. The existing implementation implements that correctly when handling the connectivity state update event, but it does not implement `getConnectivityState`, so that falls back to the default implementation which just proxies the result from the `childSubchannel`. This matters because the `round_robin` LB policy uses `getConnectivityState` instead of just tracking the state update events.

grpc-js: Implement getConnectivityState in subchannel wrapper

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

When the address list is updated, the child will probably request new subchannels for the addresses, and if the addresses are unchanged, the same subchannels will be provided but the outlier detection LB policy will still recreate the wrapper objects. I made two changes here to preserve the state when that happens:
- Construct the wrapper using the subchannel's reported state instead of defaulting to the `IDLE` state, so that the wrapper reports the correct state immediately, before the subchannel's state changes.
- If the address is already ejected, propagate that state to the new subchannel wrapper.

grpc-js: Preserve state when recreating subchannel wrappers

---

packages/grpc-js/tsconfig.json

This is the same as #2121, redone with permission of the author, because of CLA problems. This change prevents the TypeScript compiler from generating `/// <reference types="long" />` from `import type { Long } from '@grpc/proto-loader'`, which causes problems when users have other dependencies on `long`.
Fixes #2030.

grpc-js: Specify 'types' option in tsconfig file

---

packages/grpc-js/src/call-stream.ts

The reference chain in #2184 shows that the trailer event handler specifically is holding a reference to the `Http2CallStream` object, and that event handler is the only one that uses `bind`, so it seems likely that those are related. With this change, that event handler will be created similarly to the others, so hopefully that will fix the problem.

grpc-js: Avoid explicit bind in trailer event handler

---

packages/grpc-js-xds/interop/Dockerfile
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts

This backports #2177, #2179, and #2180 to the 1.6.x branch.

grpc-js: backport outlier detection fixes to v1.6.x

---

packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts
test/kokoro/linux.cfg

The main goal of this change is to add the resource timer, which is described in [this section of the xDS docs](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#knowing-when-a-requested-resource-does-not-exist). Essentially, the protocol does not consistently tell us when a resource does not exist, so we assume that the server will respond to any request within 15 seconds, and if the client does not get the requested resource in that time, it assumes that it does not exist. Since the timer is watching server response latency, we only run it while we have an active ADS stream. The specific algorithm is as follows:
- When a watcher subscribes to a new resource name, if the ADS stream is alive, start the timer for that resource name.
- When the ADS stream dies, cancel all …

grpc-js-xds: Refactor xDS stream state and add resource timer

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

This will work once the corresponding feature is enabled in production.

grpc-js-xds: Enable the outlier detection interop test

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Same as #2185, but for the 1.6.x branch. This will work once the feature is enabled in production, and once #2181 is merged.

grpc-js-xds: Enable the outlier detection interop test (1.6.x)

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

This is an attempt to fix the `ClientHttp2Stream` leak described in #2184. The likely cause of the leak is that `stream.close()` is called but it still has incoming data waiting to be read so it is never destroyed. This fixes that by putting the stream into flowing mode and discarding all incoming messages after outputting a status. This should have no user-visible effect because the existing code already does not output any messages after outputting a status.

grpc-js: Drain incoming http2 data after outputting status

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

grpc-js-xds: Fix outlier detection interop test name (v1.6.x)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

grpc-js-xds: Fix outlier detection interop test name

---

packages/proto-loader/package.json

This fixes a breakage in the interop test docker image build. It looks like `lodash` had an update that made it incompatible with `typescript` v3, so I upgraded to `typescript` v4, and I also needed to update `gts` for compatibility with the upgraded `typescript` version.

proto-loader: Update dependencies to fix compilation error

---

packages/proto-loader/package.json

This reverts #2192. We thought it wouldn't break Cloud API client libraries, but it did. We'll try this again in the future after they have made some changes.

proto-loader: Undo upgrade of 'long' dependency

---

packages/grpc-js/src/load-balancer-child-handler.ts

Based on conversations with the team, this is a correction to the behavior when handling an LB policy config update that changes the LB policy type. This `ChildLoadBalancerHandler` class handles graceful switchover from the existing LB policy to the new one. The current behavior is to switch when the new one is in the READY state, but instead it will switch whenever the new one is in any state other than CONNECTING.

grpc-js: Switch LB policy when new one is not CONNECTING

---

packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts
packages/grpc-js/src/experimental.ts

This is an implementation of [gRFC A53](https://github.com/grpc/proposal/blob/master/A53-xds-ignore-resource-deletion.md). I think this is the implementation strategy that minimizes changes to existing code.

grpc-js-xds: Implement ignore_resource_deletion option

---

packages/proto-loader/package.json

This is the same as #2196. That breakage is also impacting the test jobs on the 1.6.x branch.

proto-loader: Update dependencies to fix compilation error (1.6.x)

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

This change addresses grpc/proposal#323.

grpc-js: Stop ejecting when current percent is equal to max

---

packages/grpc-js-xds/src/resolver-xds.ts

We may also want to do this for per-call authority overrides, but that would require reworking a lot of this class so it is deferred.

grpc-js-xds: Use authority override to select VirtualHost when provided

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_url_map.cfg

- Enables pod log collection in all PSM interop jobs implemented
in https://github.com/grpc/grpc/pull/30594.
- Associate test suite runs with their own log file, so it's displayed
on the "Target Log" tab
- Adds missing `--force_cleanup` to the lb test (reduces leaked
resources)
- Fix run_test not returning correct exit status, causing false
positives in some cases. See https://github.com/grpc/grpc/pull/30768

xDS interop: enable pod log collection in the buildscripts

---

packages/proto-loader/package.json

This PR updates `proto-loader` package.json to include `.js.map` files.
Fixes #2170

include `.map` files in proto-loader npm package

---

packages/grpc-js/src/load-balancer-outlier-detection.ts

Now that the interop tests are passing.

grpc-js: Enable outlier detection by default

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

The same as #2213, but making the change on the v1.6.x branch.

grpc-js: Fix typo in previous status message handling fix

---

packages/grpc-js/src/server-call.ts

I'm working on some server interceptors that are injected as part of our generation process.  These interceptors need to know the final gRPC status and the path (really the service and function) that the request was sent to.  In the current model, both of these bits of information are hidden within the internal call implementation. This PR exposes both of these so that they can be accessed without crossing the internal implementation boundary.

Expose path and callEnd event in ServerSurfaceCall

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_url_map.cfg

Backport of #2208 to @grpc/grpc-js@1.6.x.
- Enables pod log collection in all PSM interop jobs implemented
in https://github.com/grpc/grpc/pull/30594.
- Associate test suite runs with their own log file, so it's displayed
on the "Target Log" tab
- Adds missing `--force_cleanup` to the lb test (reduces leaked
resources)
- Fix run_test not returning correct exit status, causing false
positives in some cases. See https://github.com/grpc/grpc/pull/30768

xDS interop: enable pod log collection in the buildscripts (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_url_map.cfg

Backport of #2208 to @grpc/grpc-js@1.5.x.
- Enables pod log collection in all PSM interop jobs implemented
in https://github.com/grpc/grpc/pull/30594.
- Associate test suite runs with their own log file, so it's displayed
on the "Target Log" tab
- Adds missing `--force_cleanup` to the lb test (reduces leaked
resources)
- Fix run_test not returning correct exit status, causing false
positives in some cases. See https://github.com/grpc/grpc/pull/30768

xDS interop: enable pod log collection in the buildscripts (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js/test/test-outlier-detection.ts

These tests test the validation rules described in [this section of the outlier detection gRFC](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md#temporary-environment-variable-protection).

grpc-js: Add tests for outlier detection validation rules

---

packages/grpc-js/src/channel.ts

This is an implementation of [gRFC A54](https://github.com/grpc/proposal/blob/master/A54-restrict-control-plane-status-codes.md).

grpc-js: Restrict control-plane status codes

---

packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

Another check a few lines later validates that the sum of the individual weights is equal to the total weight, so this also implicitly validates that the sum of the weights is non-zero. The field is a `uint32` so we already assume it is non-negative.

grpc-js-xds: NACK WeightedCluster if total_weight is 0

---

packages/grpc-js/package.json
packages/grpc-js/src/client.ts

This is an update to the change I made in #2109 that added caller stack traces to call errors. It turns out that getting the `stack` field of an error is a relatively expensive operation, so we don't do it in the hot path, and instead we wait until an error actually occurs. The goal is to fix the performance issues reported in #2231. #2109 is the only change that looks like it could possibly impact latency between 1.6.7 and 1.6.8.

grpc-js: Defer evaluating caller stack until an error

---

packages/proto-loader/package.json

To publish #2183. In Node's semver semantics, when the major version is 0, the minor version is treated as the major version, and the patch version is treated as the minor version.

proto-loader: Bump to 0.7.3

---

packages/grpc-tools/build_binaries.sh

For now, pre-compiled binary of `grpc-tools` is missing for M1 mac (arm64).
https://github.com/grpc/grpc-node/issues/1405
It is possible to run M1 mac by setting `npm_config_target_arch=x64`, but it is a little bit messy.
It must be straightforward to wait for M1 build machines in GitHub action, 
https://github.com/grpc/grpc-node/issues/1405#issuecomment-1195903603
but we can build universal binaries by setting `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to `cmake`, and can extract binaries for x86_64/arm64 using `lipo`.
Or, it would be good to provide universal binaries without separating binaries.
In my Macbook (intel), I can successfully build both x86_64 and arm64 binaries.
```
$ uname -v
Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 …
```

Build arm64 binaries for mac

---

packages/grpc-tools/package.json

To publish the new M1 binaries from #2235.

grpc-tools: Bump to version 1.11.3

---

packages/grpc-tools/build_binaries.sh

This is an update to the change made in #2235 to fix #2238. node-pre-gyp refers to the x86-64 architecture as "x64", so we need to use that name whenever we generate output in this script. This doesn't require a new release because I fixed the issue with the last release manually.

grpc-tools: Fix x64 arch name in build script

---

packages/grpc-js-xds/src/xds-stream-state/eds-state.ts

The previous `1<<32` is not a valid number representation in JavaScript. This hex value is the simplest way I could think of to represent that number.

grpc-js-xds: Fix limit representation for priority weight validation

---

packages/grpc-js/package.json
packages/grpc-js/src/server.ts

#2084 changed the default on the client side. This change makes the server handling consistent with that previous change.
Pointed out in https://github.com/grpc/grpc-node/issues/1158#issuecomment-1278633978.

grpc-js: Handle the grpc-node.max_session_memory option consistently on the client and server

---

packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/test/test-outlier-detection.ts

The tests are regression tests for basic outlier detection functionality that should have already existed, and the new tracing is there to debug recent interop failures.

grpc-js: Add more outlier detection tests and tracing

---

run-tests.bat
run-tests.sh

Node 10 and 12 are no longer maintained, and Node 18 is now out.

grpc-js: Test against actively maintained Node versions

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Channelz.ts
packages/grpc-js/src/metadata.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts

I've been working on improving perf of grpc-js and a few things stood out to me:
1. Each `Http2ServerCallStream` has an empty timer created, which results in overhead, I assume this was done in an effort to have the same backing map, but performance is gained when not cleaning / creating timeouts needlessly
2. Track `aborted` event and in case stream is `aborted` emit `cancelled`, otherwise graceful stream end shouldn't cause what ultimately is exception. This allows for improved performance around cancellation logic
3. Wrap call to tracing as JSON.stringify + toJSON on metadata is an expensive operation and is performed regardless of tracing actually be on
Locally I've had all the tests pass on node 18, fingers crossed they pass everywhere else. I'm still mostly concerned about (2) as I …

fix: track aborted status, do not stringify for tracing

---

packages/grpc-js-xds/interop/xds-interop-client.ts

This is an attempt to get more details on the apparent low QPS that seems to be causing recent interop test failures.

grpc-js-xds: Log stats periodically in interop tests

---

packages/grpc-js/package.json

This fixes the compilation breakage seen in #2255 that was also reported in DefinitelyTyped/DefinitelyTyped#63022

grpc-js: Pin @types/lodash to fix broken build

---

packages/grpc-js/src/resolving-call.ts

Just something I forgot to do in the original implementation.

grpc-js: Restart deadline timer after getting timeout from service config

---

packages/grpc-js/package.json
packages/grpc-js/src/call-credentials.ts
packages/grpc-js/src/client-interceptors.ts
packages/grpc-js/src/error.ts
packages/grpc-js/src/metadata.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts

Redoing #2259 after merging from 1.7.x in #2261.
A recent change to `@types/lodash` broke compatibility with TypeScript 3.9, because that version is outside of the support range. Future changes to types packages will probably cause this again, so the best remedy is to use a newer version of TypeScript. There are two main changes requiring code changes in this library:
- When creating a Promise, `resolve` can only be called with no parameters if the Promise explicitly has the `void` type parameter.
- When catching a thrown error, the error now has the `unknown` type, so we need to explicitly check that type.

grpc-js: Update to newest typescript compiler

---

packages/grpc-js-xds/interop/xds-interop-client.ts

The xDS interop client uses `setInterval` with an interval of `1000/qps` to send `qps` requests per second. However, `setInterval` may take slightly longer than the specified amount of time to trigger the timer, and it does not correct for accumulated errors. The result is that local testing (without using xDS) shows about 97-98 calls started per second on average when `qps` is set to 100. With this change, the client reports at least 99 calls started each second, and at most 101, with an average slightly below 100.
I want to see the impact when the actual QPS is significantly below the configuration, as in current test failures I am investigating.

grpc-js-xds: interop client: correct for setInterval variance

---

packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolving-call.ts

This is a change I originally made as part of the retries implementation, but I want to submit it separately because I think it may have an impact on the xDS interop test failures that I am currently investigating. In particular, the existing implementation has a correctness issue where filter factories provided in the config from the name resolver are not propagated to where the filters are actually instantiated.

grpc-js: Handle filters in ResolvingCall instead of LoadBalancingCall

---

packages/grpc-js-xds/scripts/xds.sh

I am doing this with the old framework because I am unsure how this would work in the new framework when the client is in a docker container. The config file grabs artifacts from `github/grpc/reports/**`, so hopefully this should work.

grpc-js-xds: interop: output CPU profile logs in old framework tests

---

packages/grpc-js-xds/scripts/xds.sh

The original path I used in #2268 was not actually relative to the artifacts directory, so making it absolute made it point at the wrong place. This fixes that. Compare with [the config](https://github.com/grpc/grpc-node/blob/master/test/kokoro/xds-interop.cfg#L22)

grpc-js-xds: interop: Fix target directory for profile log

---

packages/grpc-js/src/filter-stack.ts
packages/grpc-js/src/internal-channel.ts

CPU performance logs of xDS tests showed that a large amount of time was being spent in `FaultInjectionFilter#sendMetadata` in multiple tests. I believe this is caused by [this section of `ResolvingCall`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/resolving-call.ts#L176) that extends the `filterStackFactory` with the filters from the config from the resolver. The `filterStackFactory` there is the same one owned by the channel, so each call would add another instance of the filter for future calls. The solution is to provide a copy of the object to each call, so that it does not add to the original.

grpc-js: Fix reuse of channel filter stack factory

---

packages/grpc-js/src/filter-stack.ts

#2271 did not fully fix the problem because the clone still has a reference to the original array.

grpc-js: Make filter stack factory clone with a copy of the array

---

packages/grpc-js-xds/interop/xds-interop-client.ts

This is an update to #2263, to handle the case where the set of configured call types changes after the process starts.

grpc-js-xds: interop: Fix timestamp handling when config changes

---

packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/server.ts

This is an implementation of [gRFC A9: Server-side Connection Management](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md), except for `MAX_CONNECTION_IDLE` because I don't have an established setup for tracking open streams. This change was prompted by a request in #2265.

grpc-js: Implement server connection management

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/google/api/FieldBehavior.ts
packages/proto-loader/golden-generated/google/protobuf/FieldDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/FieldOptions.ts
packages/proto-loader/golden-generated/google/protobuf/FileOptions.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/EchoRequest.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/EchoResponse.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/Severity.ts

Avoid using Typescript `enums`.
Instead of a TS enum that are both a value and a type, define a js object that will only hold either the `Number` or `String` (Depending on the configuration) representation of an `enum`.
For backwards compatibility, have the permissive type accept both the `Number` and `String` representations, and the restrictive type be a union of the `String` or `Number` representations.
These changes have the added benefit of simplifying the generator code, because `Message` and `Enum` types are now treated the same.

proto-loader-gen-types Avoid TS enums

---

packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts

This is an implementation of [gRFC A57: XdsClient Failure Mode Behavior](https://github.com/grpc/proposal/blob/master/A57-xds-client-failure-mode-behavior.md). Some of the existing behavior matches that proposal, these are the changes:
- An ADS stream only reports an error when receiving a non-OK status if it did not previously receive a response from the server. Previously it reported that error unconditionally.
- The backoff for starting a stream resets when a message is received from the xDS server. Previously it would reset only if the response validated successfully.
- The connectivity state of the channel that connects to the xDS server is watched, and an error is reported if the channel state becomes TRANSIENT_FAILURE.
- The `waitForReady` option is used when starting the ADS …

grpc-js-xds: Update failure mode behavior

---

packages/grpc-js-xds/src/environment.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/route-action.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js/src/experimental.ts

This is an implementation of [gRFC A44: gRPC xDS Retry Support](https://github.com/grpc/proposal/blob/master/A44-xds-retry.md).

grpc-js-xds: Implement retry support

---

tools/release/native/Dockerfile

The build has been failing recently because some of the GPG keys for accessing apt repositories are too old. This upgrade fixes that in local testing.
The test job this is supposed to fix is "grpc-tools Build / Linux grpc-tools Build"

grpc-tools: Update native build docker image

---

PACKAGE-COMPARISON.md
README.md

As pointed out in #2283, the information in both of these documents is somewhat out of date, so I updated it. In particular, I marked the old `grpc` package as "deprecated", as has been done in other places. I also switched the order of the two packages in the README, to prioritize the one that is not deprecated.

Update information in README and PACKAGE-COMPARISON docs

---

packages/proto-loader/README.md
packages/proto-loader/bin/proto-loader-gen-types.ts

This PR introduces a boolean option `branded` for `proto-loader-gen-types`.
If the branded option is on, `interface` representing a Message has additional `__type` property, that has the `fullName` of originating `Message` as its value.
```proto
package test;
message FooRequest {
string name = 1;
}
```
turns into
```ts
interface FooRequest {
name: string;
__type: '.test.FooRequest';
}
```
Since typescript only supports structural typing, if any two types has the exact same structure, they can be used interchangeably.
This makes codes like below totally valid.
```ts
interface FooRequest {
name: string;
}
interface BarRequest {
name: string;
}
function requestFoo(param: FooRequest) { ... }
function requestBar(param: BarRequest) { ... }
const fooArg: FooRequest = { name: "this is foo" }; …
```

proto-loader-gen-types: Support nominal typing with type branding

---

packages/grpc-tools/build_binaries.sh
packages/grpc-tools/package.json

This fixes #2287. The current release has a bug where the Mac artifacts are extracted into a directory called `GNUSparseFiles.0`. This comes from extracting a sparse file from a POSIX/PAX format archive ([documentation](https://www.gnu.org/software/tar/manual/html_node/Sparse-Recovery.html)). `file` shows that only the Mac artifacts are in the POSIX format, and the others are in the GNU format. I am assuming that the `tar` implementation in the Mac build environment defaults to the POSIX format, which would mean that we can avoid this problem by forcing the GNU format.

grpc-tools: Force GNU format for artifact tarballs

---

packages/grpc-tools/CMakeLists.txt
packages/grpc-tools/package.json

It looks like the Mac build environment got upgraded recently and it is building the binary in a way that doesn't work on older environments. This change should make it build the same as how it build on the old environment.
The code in this change comes from [this post](https://stackoverflow.com/a/34208904/159388).

grpc-tools: Build for older Mac version

---

packages/grpc-tools/CMakeLists.txt
packages/grpc-tools/build_binaries.sh

According to [this post](https://stackoverflow.com/a/55294037/159388), adding `FORCE` may help if the option isn't working. The `otool` call should let us check if this worked.

grpc-tools: Build for an older Mac version (attempt 2)

---

PACKAGE-COMPARISON.md
packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/environment.ts
packages/grpc-js/package.json

De-experimentalize xDS retry support, and update versions and documentation. My condition for publishing this release is stable xDS retry support, so I will merge this PR once we reach that point.

grpc-js: Prepare for 1.8.0 release

---

packages/grpc-js-xds/src/csds.ts
test/api/error_test.js
test/interop/interop_client.js
test/performance/benchmark_client.js
test/performance/benchmark_client_express.js
test/performance/histogram.js

- Fix `host_override` param typo in /test/interop/interop_client.js
- Fix other typos

Fix host_override param typo:

---

packages/grpc-js/src/retrying-call.ts

This fixes #2301. Currently the buffer tracker entry is retained after the call ends, so the number of entries grows without bound as calls are made. This fixes that by freeing up that entry when a call ends. The function call added here already has the desired behavior on [this line](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/retrying-call.ts#L89). I also discard the buffer entries at the same time to maintain consistency between the buffer tracker and the actual buffer.

grpc-js: Discard buffer tracker entry when RetryingCall ends

---

packages/grpc-js/src/server-call.ts

This fixes #2300. The specification that these headers should be included is in the "Trailers-Only" bullet [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses).

grpc-js: Add HTTP status and content type headers to trailers-only responses

---

packages/grpc-js/README.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/test/test-resolver.ts

Adds support for `grpc.service_config_disable_resolution` to fix #1518 .

grpc-js: Add support for grpc.service_config_disable_resolution

---

packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts

This change refactors the `Subchannel` class into three classes/interfaces as follows:
- `Subchannel`: Abstraction over connections to a specific backend server. Manages connectivity state and connection backoff.
- `SubchannelConnector`: manages the process of establishing a connection to a backend.
- `Transport`: Manages a single connection.
Currently the only `SubchannelConnector` and `Transport` implementations use HTTP/2, and the subchannel pool is hardcoded to use those implementations, but the `Subchannel` class now no longer has any HTTP/2-specific code and could be used with other transport implementations.
The purpose of this change is to fix #2176. Specifically, when the subchannel stops using a transport because it has received a GOAWAY, the subchannel will discard the …

grpc-js: Refactor `Transport` and `SubchannelConnector` out of `Subchannel`

---

packages/grpc-js-xds/scripts/xds.sh

grpc-js-xds: Reduce GCE xDS interop tests to ping_pong and circuit_breaking

---

packages/grpc-js-xds/scripts/xds.sh

Backport of #2310 to @grpc/grpc-js@1.5.x.
---

grpc-js-xds: Reduce GCE xDS interop tests to ping_pong and circuit_breaking (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/scripts/xds.sh

Backport of #2310 to @grpc/grpc-js@1.6.x.
---

grpc-js-xds: Reduce GCE xDS interop tests to ping_pong and circuit_breaking (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds.sh

Backport of #2310 to @grpc/grpc-js@1.7.x.
---

grpc-js-xds: Reduce GCE xDS interop tests to ping_pong and circuit_breaking (@grpc/grpc-js@1.7.x backport)

---

packages/grpc-js-xds/scripts/xds.sh

Backport of #2310 to @grpc/grpc-js@1.8.x.
---

grpc-js-xds: Reduce GCE xDS interop tests to ping_pong and circuit_breaking (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts

`push` uses `process.nextTick` to force the read event to be asynchronous. Because of this the status can show up in between when `push` is called and when the message is actually passed along. So, we stop the status from being output in that intervening time.
This issue was pointed out in #2315, but I think this is a better solution than the one suggested there.

grpc-js: Ensure ordering between status and final message

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-server.ts

The transport should not report disconnection to its active calls when receiving a GOAWAY, because in general GOAWAYs can allow existing streams to finish on their own, and Node will end the stream directly when that is not the case. Manual testing shows that this change fixes the situation depicted in the new test where a client receives a GOAWAY in the middle of a stream. The test is skipped because on Node versions older than 18, the streams continue after the GOAWAY but end with an error anyway, probably because of nodejs/node#42713.
I think this fixes #2318.

grpc-js: Don't end calls when receiving GOAWAY

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/transport.ts

This matches the previous behavior of the subchannel's call refcount. The session needs to be reffed to keep the Node process alive if it is in use.
This should fix #2318.

grpc-js: Reference session in transport when there are active calls

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

xds interop: Fix buildscripts not continuing on a failed test suite

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2323 to @grpc/grpc-js@1.5.x.
---
The `((` construct returns a 0 exit code if the value is non-zero. Since the value starts at 0 and we do a post-increment, it will always fail the first time. Changing it to a pre-increment fixes the problem.

xds interop: Fix buildscripts not continuing on a failed test suite (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2323 to @grpc/grpc-js@1.6.x.
---
The `((` construct returns a 0 exit code if the value is non-zero. Since the value starts at 0 and we do a post-increment, it will always fail the first time. Changing it to a pre-increment fixes the problem.

xds interop: Fix buildscripts not continuing on a failed test suite (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2323 to @grpc/grpc-js@1.7.x.
---
The `((` construct returns a 0 exit code if the value is non-zero. Since the value starts at 0 and we do a post-increment, it will always fail the first time. Changing it to a pre-increment fixes the problem.

xds interop: Fix buildscripts not continuing on a failed test suite (@grpc/grpc-js@1.7.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2323 to @grpc/grpc-js@1.8.x.
---
The `((` construct returns a 0 exit code if the value is non-zero. Since the value starts at 0 and we do a post-increment, it will always fail the first time. Changing it to a pre-increment fixes the problem.

xds interop: Fix buildscripts not continuing on a failed test suite (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

This is a similar fix to #2240.

grpc-js-xds: weighted clusters: stop checking total_weight, check weight sum <= uint32 max

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/transport.ts

https://github.com/grpc/grpc-node/issues/2318#issuecomment-1403124466 reported a regression in that previously fixed issue. I suspect that the problem is that once a subchannel stops using a transport, nothing has a reference to that transport, which makes it eligible to be garbage collected. To avoid this, the subchannel call now holds a reference to the transport, so it stays alive as long as at least one active call is using it.
I also removed the `disconnectListener` because it became unused in the previous refactor.

grpc-js: Hold a reference to transport in SubchannelCall

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts

Calling `ref` and `unref` on the session determines whether the session keeps the process alive. The handling of this needs to be independent of keepalive settings.
I think this is the actual problem in https://github.com/grpc/grpc-node/issues/2318#issuecomment-1404127354.

grpc-js: Fix tracking of active calls in transport

---

packages/grpc-js/src/retrying-call.ts

`progress` is an implementation detail of the retrying call design. It is meaningful for determining whether to retry an individual attempt, but there is no reason to include it in the final status surfaced to the user.

grpc-js: Remove `progress` field in status from retrying call

---

packages/grpc-js/src/index.ts

The `InterceptingListener` type is already used in the publicly exported type `InterceptingCall`, and the `NextCall` interface is already publicly used in the publicly exported type `Interceptor`.

grpc-js: Export `InterceptingListener` and `NextCall` types

---

packages/grpc-js/package.json
packages/grpc-js/src/retrying-call.ts

This fixes #2347. The call site of `commitCallWithMostMessages` assumes that some call has been committed after the function returns. This can fail for two reasons:
1. All existing underlying calls are completed.
2. A completed call has more messages sent than all active calls
This change removes the second possibility entirely, and adds checks to handle the first case properly.

grpc-js: Fix `commitCallWithMostMessages` trying to commit completed attempts

---

packages/grpc-js/package.json
packages/grpc-js/src/call-credentials-filter.ts
packages/grpc-js/src/call-credentials.ts
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/client-interceptors.ts
packages/grpc-js/src/error.ts
packages/grpc-js/src/metadata.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts

This is a port of #2262 into the 1.7.x branch. The build seemed to be broken by DefinitelyTyped/DefinitelyTyped#64266, specifically that the new version of `@types/node` is not compatible with Typescript 3.x. The simplest solution that avoids similar problems in the future is to update Typescript.

grpc-js: Update to newest typescript compiler (1.7.x)

---

packages/grpc-js/src/deadline.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/resolving-call.ts

This has two related changes:
- Ensure that timeouts generated from deadlines to be passed to `setTimeout` are always reasonable values.
- Consistently represent deadlines as ISO date strings in logs, to match the timestamps that are always included in trace log lines.
This started when I saw this log line, and found it difficult to compare the timestamp with the deadline:
```
D 2023-01-31T03:30:06.992Z | channel | (2) <target> createCall [1914] method="<method>", deadline=Tue Jan 31 2023 03:30:06 GMT+0000 (Coordinated Universal Time)
```

grpc-js: Improve timeout handling and deadline logging

---

packages/grpc-js-xds/interop/Dockerfile
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts

Outlier detection in xDS is broken without this change. Specifically, the `newLocalityPriorities` map tracks which priority each locality is currently in, so that priorities that contain the same locality can use the same name the next time an update is sent. Without this added line, that map will not be populated at all, so priority names will never be reused. This causes the priority policy to always create new LB policy instances for its children, which resets the persistent data the outlier detection LB policy uses to make ejection determinations.
I also updated the tracer list in the interop Dockerfile to include some more recently-added tracers.

grpc-js-xds: Fix bug that prevented priority name reuse

---

packages/grpc-js-xds/src/load-balancer-cds.ts

Without this the outlier detection LB policy is just never created.

grpc-js-xds: Pass along outlier detection config from CDS to child policy

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/google/protobuf/FileOptions.ts

By adding the JSDoc `@deprecated` annotation to the output comments to interface fields IDE's can pick it up and deliver a better developer experience. This annotation is only added when the `includeComments` option is enabled. Since protobuf.js already parses if a field is deprecated or not the options object with that information is passed to the `formatComment` function.
Update golden generated with @deprecated annotation.
Resolves #2348

Write @deprecated jsdoc annotation if includeComments is enabled

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts

This fixes a bug in the keepalive implementation that did not conform to this part of the [keepalive spec](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md):
> When a client receives a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings", it should log the occurrence at a log level that is enabled by default and double the configure KEEPALIVE_TIME used for new connections on that channel.
Currently, it only doubles the keepalive time for the subchannel that received the GOAWAY.
This fix is modeled heavily on grpc/grpc#23313. I made the following changes:
- The channel now tracks the current keepalive time, including throttling modifications.
- The subchannel now passes its keepalive time along with every connectivity state update. …

grpc-js: Propagate keepalive throttling throughout channel

---

packages/grpc-js-xds/interop/Dockerfile

The interop clients run the admin servers (channelz and CSDS), so these logs should be infrequent enough to be useful and they may help debug failures when the interop driver times out requesting channelz information.

grpc-js-xds: interop: log server events

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-pick-first.ts

This fixes #2368. The change in #2363 caused the pick first LB policy to own `SubchannelWrapper` objects as opposed to `Subchannel` objects for a first time. This triggered a bug that existed since the introduction of subchannel wrappers, where the LB policy would perform an equality test between two subchannel interface objects without handling the case where one is a wrapper. The calls to `getRealSubchannel` fix that. This bug was not previously triggered because the only previous `SubchannelWrapper` implementation was for the outlier detection LB policy, and it makes no sense to use that LB policy with pick first.
In addition, testing this also revealed an older bug that has existed since the introduction of `SubchannelAddress` objects. The LB policy currently performs a naive equality …

grpc-js: Fix bugs in pick first LB policy and channel subchannel wrapper

---

packages/grpc-js/package.json
packages/grpc-js/src/retrying-call.ts

This fixes #2371. Currently, in a retrying call, when a message that has been sent is no longer needed, its entry in the message buffer is replaced with a placeholder entry with `entryType="FREED"`. This frees up the memory of the actual message contents, but in a long-running stream, the placeholder entries themselves can pile up and start to use a significant amount of memory.
With this change, the message buffer only contains the range of messages that still need to be sent, and the new `writeBufferOffset` field indicates the offset the buffer has from the beginning of the message stream. The code still tracks message indices relative to the start of the message stream, because that can always just be incremented without any concern for the current state of the buffer.

grpc-js: Stop leaking freed message buffer placeholder objects

---

packages/proto-loader/bin/proto-loader-gen-types.ts

- Explicitly list the primitive field types that use Long, instead of searching for `64` in the type name.
Currently the check for when to import `Long` just looks to see if any field type has `64` in the name.
This potentially leads to adding unused imports that causes a typescript error, when using something like `google.protobuf.Int64Value`
```
src/__generated__/Example.ts:6:1 - error TS6133: 'Long' is declared but its value is never read.
6 import type { Long } from '@grpc/proto-loader';
```

proto-loader-gen-types Narrow field Long check

---

packages/grpc-js-xds/src/load-balancer-weighted-target.ts

The number of targets will usually be small, so a binary search probably does not improve performance over a linear search, and any performance gains it does provide are not worth the complexity.

grpc-js-xds: Use simpler search algorithm in weighted target picker

---

packages/grpc-js/src/server-call.ts

add await/async on method that return promise to ensure that the order of message (and of the end of stream) are preserved
The goal is to fix the ticket #2375 where the end of stream can arrive before last messages and the message can be lost.

grpc-js: add await/async on method that return promise

---

packages/grpc-js/src/load-balancing-call.ts

With a trace log before and after the pick call, this should conclusively determine whether the picker ever hangs.

grpc-js: Trace before call to LB policy picker

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/subchannel-address.ts

This fixes #2379. In the current code, if the pick-first LB policy gets an address list that is shorter than the previous address list, the loop checking for equality can run off the edge of the list and pass an `undefined` value the type checker doesn't account for into `subchannelAddressEqual`. I added three layers of protection to avoid this:
1. The loop is skipped if the lengths are equal.
2. `subchannelAddressEqual` is only called if the value is not `undefined`.
3. `subchannelAddressEqual` can now handle `undefined` values, in case something like this happens elsewhere.

grpc-js: Fix address equality check in pick-first

---

packages/grpc-js/src/resolving-call.ts

The hang logs are consistently stopping between receiving a message and outputting a status. This should give us more information about what is happening.

grpc-js: Add more logging to trace handling of received messages

---

packages/grpc-js-xds/interop/Dockerfile

Testing a hypothesis that a test failure we have been seeing is specific to Alpine.

grpc-js-xds: Use non-alpine docker image for interop tests

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts

We look at this field when measuring usage.

grpc-js-xds: Populate Node message field user_agent_version

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts

This fixes #2393. Manual testing shows that without this change, after a channel is closed, the channelz registry reference keeps the transport alive, and that in turn keeps the subchannel alive.

grpc-js: Unregister socket from channelz when closing transport

---

packages/grpc-js-xds/interop/Dockerfile

I haven't reproduced the failure yet under Node 18.

grpc-js-xds: Use Node 18 in interop docker image

---

packages/grpc-js-xds/interop/Dockerfile

Backport of #2389 and #2404 to 1.18.x.

grpc-js-xds: Use Debian and Node 18 in interop Dockerfile (1.8.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use Debian and Node 18 in interop Dockerfile (1.7.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use Debian and Node 18 in interop Dockerfile (1.6.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use Debian and Node 18 in interop Dockerfile (1.5.x)

---

packages/grpc-js-xds/scripts/xds.sh

This will help debug the circuit_breaking failure when it occurs on master.

grpc-js-xds: Use the same tracers in the legacy driver as in the new one

---

packages/grpc-tools/README.md

The provided link leads to a 404 since Google pulled the documentation page for the JS library and left the poor developers without any documentation.
The original page can be accessed via [Wayback Machine](http://web.archive.org/web/20220422095626/https://developers.google.com/protocol-buffers/docs/reference/javascript-generated).
The replacement link provides the same original content.

Replace invalid link in grpc-tools README

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js/README.md
packages/grpc-js/package.json
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/deadline.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/subchannel-address.ts
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-resolver.ts
packages/grpc-js/test/test-server.ts

Redoing #2382 to resolve merge conflicts.

Merge v1.8.x into master

---

packages/grpc-js-xds/interop/xds-interop-client.ts

The `callTimeHistogram` tracks the distribution of call duration per call type and per status code, for logging. Currently they are just output as large lists of numbers. This change instead has them output as actual histogram graphs.

grpc-js-xds: Render call time histograms nicely in interop logs

---

packages/grpc-js/src/load-balancer-round-robin.ts

The current implementation with independent tracking of subchannel state counts is brittle because the states need to be synchronized everywhere. I think there is a possibility that deviations there could have caused a recent test failure. The change here is just to always check the subchannel directly when the state is needed.

grpc-js: Simplify round robin implementation

---

packages/grpc-js-xds/test/test-cluster-type.ts

The `only` there caused other test groups in other files to be skipped.

grpc-js-xds: Remove extra 'only' from local testing

---

packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-global-subchannel-pool.ts

The test in #2419 revealed a couple of bugs related to the order of connectivity state change events:
- `PickFirstLoadBalancer#pickSubchannel` informs its parent of the state change before resolving its own internal state, and as a result arbitrary code can run at that point.
- The calls to the list of listeners in `Subchannel#transitionToState` can eventually result in API calls that cause additional state changes, causing potential reentrancy in `transitionToState` which can result in out-of-order state change notifications.
The changes to fix this are:
- Move the state reporting in `PickFirstLoadBalancer#pickSubchannel` to the end.
- Refactor the `listener` list in `Subchannel` to a set to simplify interacting with it and to allow removing listeners during the iteration.
- Ensure all …

grpc-js: Fix connectivity state change event sequencing

---

packages/grpc-js-xds/scripts/xds.sh

Update for b/232859415. 50 QPS is too low because part of the test expects it to reach 1000 pending requests, and with a 20 second timeout, it will barely reach that and will never trigger circuit breaking.

PSM Interop: Increase old driver QPS to 75 (v1.8.x)

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

This fixes #2435. Yargs version 16 has a dependency that is vulnerable to [CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw). Yargs 17 has the updated dependency.

proto-loader: Update to yargs@17.x

---

run-tests.bat
run-tests.sh

Backport of #2246 to @grpc/grpc-js@1.7.x.
---
Node 10 and 12 are no longer maintained, and Node 18 is now out.

grpc-js: Test against actively maintained Node versions (@grpc/grpc-js@1.7.x backport)

---

run-tests.bat
run-tests.sh

Backport of #2246 to @grpc/grpc-js@1.6.x.
---
Node 10 and 12 are no longer maintained, and Node 18 is now out.

grpc-js: Test against actively maintained Node versions (@grpc/grpc-js@1.6.x backport)

---

run-tests.bat
run-tests.sh

Backport of #2246 to @grpc/grpc-js@1.5.x.
---
Node 10 and 12 are no longer maintained, and Node 18 is now out.

grpc-js: Test against actively maintained Node versions (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/scripts/xds-v3.sh
packages/grpc-js-xds/scripts/xds.sh

Legacy xDS v2 test suite should only be running `ping_pong`.

PSM Interop: do not run circuit_breaking in Legacy xDS v2 suite

---

packages/grpc-js-xds/scripts/xds-v3.sh
packages/grpc-js-xds/scripts/xds.sh

Backport of #2447 to @grpc/grpc-js@1.6.x.
---
Legacy xDS v2 test suite should only be running `ping_pong`.

PSM Interop: do not run circuit_breaking in Legacy xDS v2 suite (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds-v3.sh
packages/grpc-js-xds/scripts/xds.sh

Backport of #2447 to @grpc/grpc-js@1.5.x.
---
Legacy xDS v2 test suite should only be running `ping_pong`.

PSM Interop: do not run circuit_breaking in Legacy xDS v2 suite (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

We configured TestGrid to file bug separately for each failed sub-target, if we still fail the main target, TestGrid will fail duplicate bugs.
The same change in core: https://github.com/grpc/grpc/pull/33222.

PSM Interop: Don't fail target if sub-target already failed

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2457 to @grpc/grpc-js@1.8.x.
---
We configured TestGrid to file bug separately for each failed sub-target, if we still fail the main target, TestGrid will fail duplicate bugs.
The same change in core: https://github.com/grpc/grpc/pull/33222

PSM Interop: Don't fail target if sub-target already failed (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2457 to @grpc/grpc-js@1.6.x.
---
We configured TestGrid to file bug separately for each failed sub-target, if we still fail the main target, TestGrid will fail duplicate bugs.
The same change in core: https://github.com/grpc/grpc/pull/33222

PSM Interop: Don't fail target if sub-target already failed (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2457 to @grpc/grpc-js@1.5.x.
---
We configured TestGrid to file bug separately for each failed sub-target, if we still fail the main target, TestGrid will fail duplicate bugs.
The same change in core: https://github.com/grpc/grpc/pull/33222

PSM Interop: Don't fail target if sub-target already failed (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/src/matcher.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

`string_match` is a type of string matcher that replicates the logic of several existing matchers, with the addition of the `ignore_case` flag. The `ignore_case` flag is intentionally not used for `safe_regex`.

grpc-js-xds: Support string_match in header matching

---

packages/grpc-js/package.json
packages/grpc-js/src/client.ts
packages/grpc-js/src/load-balancing-call.ts

The first fix, in `client.ts` is to `null` the `callerStackError` variable before the `onReceiveStatus` callback returns. The `Error` object retains information about the stack trace where it was created, including context objects. In the specific case where a new request is initiated while handling the result of a previous request, the new request's `callerStackError` would retain a stack context that includes the previous `callerStackError`. If done in a ping-pong type loop, this retention could be recursive.
The second fix is to ensure that non-OK statuses caused by picker errors (especially if the channel is not connected) are emitted asynchronously. If emitted synchronously, if calls are retried unconditionally and synchronously, the process could make no progress towards …

grpc-js: Fix a couple of things that came up while investigating a memory leak

---

packages/grpc-js-xds/scripts/xds.sh

Node 12 is past EOL and it looks like the TypeScript compiler version we use no longer runs on it.

grpc-js-xds: Update Node version in old test script

---

packages/grpc-js-xds/scripts/xds.sh

This is a modification to #2466. It looks like Node 18 is too new, and it doesn't work in the environment that this test job runs in.

grpc-js-xds: Downgrade Node version in old test script to 16

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts

The missing implementation code was pointed out in #2468.

grpc-js: Implement trace function in Http2SubchannelConnector

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

The same change in core: https://github.com/grpc/grpc/pull/33520.

[PSM interop] Don't fail target if sub-target already failed

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2475 to @grpc/grpc-js@1.8.x.
---
The same change in core: https://github.com/grpc/grpc/pull/33520

[PSM interop] Don't fail target if sub-target already failed (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2475 to @grpc/grpc-js@1.7.x.
---
The same change in core: https://github.com/grpc/grpc/pull/33520

[PSM interop] Don't fail target if sub-target already failed (@grpc/grpc-js@1.7.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2475 to @grpc/grpc-js@1.6.x.
---
The same change in core: https://github.com/grpc/grpc/pull/33520

[PSM interop] Don't fail target if sub-target already failed (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2475 to @grpc/grpc-js@1.5.x.
---
The same change in core: https://github.com/grpc/grpc/pull/33520

[PSM interop] Don't fail target if sub-target already failed (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use distroless Node image for interop Dockerfile (1.8.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use distroless Node image for interop Dockerfile (1.7.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use distroless Node image for interop Dockerfile (1.6.x)

---

packages/grpc-js-xds/interop/Dockerfile

grpc-js-xds: Use distroless Node image for interop Dockerfile (1.5.x)

---

packages/grpc-js-xds/interop/Dockerfile

Switching to distroless to minimize exposure to vulnerabilities.

grpc-js-xds: Use distroless Node image for interop Dockerfile

---

packages/grpc-js/README.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/test-idle-timer.ts

Implement channel idle timeout functionality: after a channel has no active calls for a certain amount of time, it will close any active connections and enter the IDLE state. The amount of time is configured by the [`grpc.client_idle_timeout_ms`](https://grpc.github.io/grpc/cpp/group__grpc__arg__keys.html#ga51ab062269cd81298f5adb6fd9a45e99) option. The default value is 30 minutes (1,800,000) and the minimum is 1 second (1000).
The changes making some fields `readonly` are primarily to make it easier to track which ones will be constant for the lifetime of the object and which may need to be reset when going to the IDLE state.
I also added some testing helper code to make it easier to add new tests of client or server behavior.
This is related to #2463 in the sense that that change's …

grpc-js: Implement channel idle timeout

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/test/test-outlier-detection.ts

This makes Node's behavior match the other languages. The only effect outlier detection can have with a pick_first child policy is to cause a reconnection if the request failure percentage exceeds a certain value. We only want to support outlier detection for health checking, not for connection management, so that combination is now disallowed.
If the user triggers this by explicitly passing a service config in channel arguments, constructing the channel will throw the error immediately. If they trigger it by providing the service config in a DNS TXT record, it should cause requests to fail with that error.

grpc-js: Disallow pick_first as child of outlier_detection

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Similar to https://github.com/grpc/grpc/pull/33542.
Note that there's a ticket to automatically use the one specified in the `--server_image_canonical` flag, but for now we just hardcode.
ref b/261911148, b/282106799.

grpc-js-xds: Bump the canonical server from v1.46.x to v1.56.0

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2488 to @grpc/grpc-js@1.7.x.
---
Similar to https://github.com/grpc/grpc/pull/33542.
Note that there's a ticket to automatically use the one specified in the `--server_image_canonical` flag, but for now we just hardcode.
ref b/261911148, b/282106799.

grpc-js-xds: Bump the canonical server from v1.46.x to v1.56.0 (@grpc/grpc-js@1.7.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2488 to @grpc/grpc-js@1.6.x.
---
Similar to https://github.com/grpc/grpc/pull/33542.
Note that there's a ticket to automatically use the one specified in the `--server_image_canonical` flag, but for now we just hardcode.
ref b/261911148, b/282106799.

grpc-js-xds: Bump the canonical server from v1.46.x to v1.56.0 (@grpc/grpc-js@1.6.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh

Backport of #2488 to @grpc/grpc-js@1.5.x.
---
Similar to https://github.com/grpc/grpc/pull/33542.
Note that there's a ticket to automatically use the one specified in the `--server_image_canonical` flag, but for now we just hardcode.
ref b/261911148, b/282106799.

grpc-js-xds: Bump the canonical server from v1.46.x to v1.56.0 (@grpc/grpc-js@1.5.x backport)

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts

To provide context and metadata in our internal gRPC handling framework, we utilize nodejs's [asynchronous context tracking](https://nodejs.org/api/async_context.html), specifically metadata namespaces similar to `cls-hooked`, implemented with `AsyncLocalStorage`.
Due to the asynchronous nature of the `Http2ServerCallStream`, the synchronous handling of receiving unary messages introduced in #2249 causes unexpected behavior. Handling the stream outside of a `Promise` makes node leave the context prematurely before continuing the message handling, therefore rendering access to the information stored with `AsyncLocalStorage` impossible.

Fix premature leaving of context due to improper Http2ServerCallStream handling

---

packages/grpc-js/src/transport.ts

I noticed in [this SO question](https://stackoverflow.com/q/76690466/159388) that the `transport` trace logs had `[object Object]` instead of the channel target.

grpc-js: Fix transport trace message formatting

---

packages/grpc-js/package.json
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/transport.ts

This fixes the implementation of the [keepalive spec](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md), specifically the following paragraphs:
> Since keepalive is not occurring on HTTP/2 connections without any streams, there will be a higher chance of failure for new RPCs following a long period of inactivity. **To reduce the tail latency for these RPCs, it is important to not reset the keepalive time when a connection becomes active; if a new stream is created and there has been greater than 'keepalive time' since the last read byte, then a keepalive PING should be sent (ideally before the HEADERS frame). Doing so detects the broken connection with a latency of keepalive timeout instead of keepalive time + timeout.**
> keepalive time is ideally measured from …

grpc-js: Fix keepalive ping timing after inactivity

---

packages/grpc-js/src/server-call.ts

Fix a compilation error caused by DefinitelyTyped/DefinitelyTyped#66144.

grpc-js: Fix compilation error from new @types/node version (1.7.x)

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts

Part of the change in #2513 added a trace line to starting the keepalive timer. That can be called from the constructor if the option `grpc.keepalive_permit_without_calls` is set, and that fails because the object isn't fully constructed. This change just rearranges the constructor so that the parts of the setup that affect trace logs are completed as early as possible, and starting the keepalive timer happens as late as possible.

grpc-js: Fix a crash when `grpc.keepalive_permit_without_calls` is set

---

test/any_grpc.js
test/package.json
test/performance/benchmark_server.js
test/performance/driver.js
test/performance/worker.js

The change in `any_grpc.js` allows code packaging tools such as [`pkg`](https://www.npmjs.com/package/pkg) to correctly process that `require` call.
The old `grpc` library is now an optional dependency, so that installation of other packages can proceed if in environments where that package is not supported, particularly when the runtime is a newer version of Node.
When calling `RunServer` on a worker with a `port` of `0`, the response now reports the actual bound port instead of `0`.
The new `worker.js` is there for manual testing. It expects two workers to be running at the specified ports on `localhost`, and it instructs them to run a simple benchmark.

Fix some issues with the benchmark code

---

test/any_grpc.js

As currently written, the `any_grpc.js` file expects the user to use Node's `--require` option with one of the files in `test/fixtures` to determine what gRPC implementations to use on the client and server. This option can be cumbersome to use in some situations. This change makes files usable in those situations with the reduced functionality that the choice of gRPC implementation is not configurable.

Default to pure JS implementation in tests

---

packages/proto-loader/package.json

protobufjs 7.x depends on long ^5.0.0. This PR updates the dependency in proto-loader to match, so that we avoid installing multiple versions of long.

proto-loader: Update long dependency to match protobufjs

---

test/performance/driver.js
test/performance/worker_service_impl.js

This error is probably the last thing keeping this benchmark from working with our benchmarking suite.

benchmark: Delay shutdown in quitWorker

---

examples/metadata/README.md
examples/metadata/client.js
examples/metadata/server.js
examples/protos/echo.proto

This is the first item in the list of examples that we are adding. The functionality of this code is copied entirely from [the corresponding Go example](https://github.com/grpc/grpc-go/tree/master/examples/features/metadata).

Add metadata example

---

examples/deadline/client.js
examples/deadline/server.js

The functionality of this code is copied entirely from [the corresponding go example](https://github.com/grpc/grpc-go/tree/master/examples/features/deadline). It uses `echo.proto`, which is added in #2487.

Add deadline examples

---

packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/transport.ts

This new option `grpc-node.tls_enable_trace` enables the tracing output in Node's built in TLS module. This works on both clients and servers, and it should work when using a proxy on the client.
This option was requested in #2468.

grpc-js: Add channel option to enable TLS tracing

---

packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/test-pick-first.ts

This implements the non-xDS parts of [gRFC A62](https://github.com/grpc/proposal/blob/master/A62-pick-first.md). I also took this as an opportunity to simplify some aspects of the pick_first LB policy implementation.
The new tests in `test-pick-first.ts` primarily test how the LB policy responds to connectivity state transitions and address list updates, because I think that's the trickiest part of the behavior. There are also a few tests specifically of the address list randomization functionality.
I omitted the environment variable protection for the address list randomization option because I believe it is sufficiently tested by the new tests.

grpc-js: Implement pick_first sticky TF and address list shuffling

---

packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js/README.md
packages/grpc-js/package.json

It looks like line 3 of grpc-js-xds/README.md wasn't updated for a while, but it's probably not worth going back and changing it.

grpc-js/grpc-js-xds: Update to 1.9.0, and update READMEs

---

packages/grpc-js/src/load-balancer-pick-first.ts

This addresses a possible cause of #2537. TypeScript doesn't require this check because the type system does not account for array out-of-bounds access.

grpc-js: Add null check in pick_first array access

---

packages/grpc-js-xds/src/duration.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/route-action.ts
packages/grpc-js-xds/src/xds-resource-type/cluster-resource-type.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/service-config.ts
packages/grpc-js/test/test-deadline.ts

More generally, the principle here is that LB policy configs should be created and passed around as plain objects until they need to be passed to an LB policy, at which time they are parsed into a typed object.
In addition, an LB policy config for a non-leaf/petiole policy has a list of possible configs for each child policy, and the first usable config in the list is used. Prior to this change, that selection took place at child policy creation time. Now, it takes place at LB policy config parse time, recursively.
The purpose of this PR is to make it easier to implement [custom LB policies](https://github.com/grpc/proposal/blob/master/A52-xds-custom-lb-policies.md). Specifically, that spec requires generating arbitrary LB policy configs from `Struct` messages.
API changes:
- The …

grpc-js: Return LB policy configs from resolvers in JSON form

---

packages/grpc-js/src/load-balancing-call.ts

grpc-js: Handle race between call cancellation and auth metadata generation

---

packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/subchannel.ts

The channelz output from `grpcdebug` in https://github.com/grpc/grpc-node/issues/2502#issuecomment-1660777601 shows logs that look like `CONNECTING -\u003e READY`, which is supposed to be `CONNECTING -> READY`. To make that look better, this change uses a format that is more similar to logs shown in examples in the `grpcdebug` documentation. So, that log line would now say `Connectivity state change to READY`.

grpc-js: Improve formatting of channelz logs for grpcdebug

---

packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts
packages/grpc-js-xds/src/xds-bootstrap.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/test/framework.ts
packages/grpc-js-xds/test/test-bootstrap.ts

This change makes the `XdsServerConfig` type a valid input to `validateXdsServerConfig` (as well as already being its output). The bootstrap file's servers are passed through `validateXdsServerConfig`, and then the resulting value is used to populate the `lrsLoadReportingServer` field of the `CdsUpdate` object. That field is then used to populate the `lrs_load_reporting_server` field of the `DiscoveryMechanism`, which is validated again when creating the xds_cluster_resolver LB policy config. That is then validated yet again when used in the xds_cluster_resolver to create the lrs LB policy config.
In addition, the lrs config generated by the xds_cluster_resolver LB policy did not have the `child_policy` field, and there was a bug in the lrs config parser that failed to handle that field …

grpc-js-xds: Fix handling of LRS server configs

---

packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/test/framework.ts

The circuit breakers configs were not tested before.

grpc-js-xds: Fix a typo in xds_cluster_impl parsing code

---

packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/xds-bootstrap.ts
packages/grpc-js-xds/test/test-confg-parsing.ts

These new tests verify that LB policy configuration parsing works correctly for all LB policies defined in the xDS package. Currently these tests primarily cover the case where the config is valid, because when everything else is functioning correctly, all generated configs should be valid.

grpc-js-xds: Add config parsing tests

---

packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/test/test-confg-parsing.ts

This should fix the remaining config parsing failures in interop tests.

grpc-js: Add config parsing tests and fix outlier detection config parsing

---

packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/transport.ts

Our build got broken by DefinitelyTyped/DefinitelyTyped#66176. It turns out that `Timer` is an old compatibility type and `Timeout` is the actively used type, so this switch should avoid future breakages.

grpc-js: Switch Timer type to Timeout

---

packages/grpc-js/src/subchannel-call.ts

nodejs/node#49147 shows that in some rare scenarios, calling `end` in the `write` callback can put the whole session into a bad state, where the socket is closed but the session is treated as still open. This could cause the symptoms described in #2502. https://github.com/nodejs/node/issues/49147#issuecomment-1679515331 indicates that this problem does not occur if the contents of the `write` callback are enclosed in `process.nextTick`, so that's what I did here. In case `stream.close` in the `write` callback can cause the same problem, all of the code in the callback is enclosed in `process.nextTick`. This callback is already always asynchronous with respect to other code, so other than avoiding this bug, this change should have no observable effects to user code.

grpc-js: Defer actions in http2 stream write callback

---

packages/grpc-js/package.json
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/service-config.ts

Issue #2549 made me realize that the code that handles method config names doesn't match the specification in [service_config.proto](https://github.com/grpc/grpc-proto/blob/master/grpc/service_config/service_config.proto), so this fixes that. There are two related changes here:
1. The service config parser now accepts a method config name with an unset `service` field, and coalesces empty string to unset for both the `service` and `method` fields.
2. The code for selecting a method config by name now prioritizes the most specifically matching config, instead of the first one in the list that matches at all.

grpc-js: Fix method config name handling in service configs

---

packages/grpc-js-xds/src/xds-client.ts

This could cause the ADS stream to stop permanently, triggered by the following sequence of events:
1. The ADS stream and LRS stream start around the same time.
2. The ADS stream ends with an error.
3. The LRS stream receives a message while the ADS stream is still backing off.

grpc-js-xds: Fix backoff timer reference when handling LRS stream messages

---

packages/proto-loader/package.json

We previously updated to a prerelease version in #2526 to test the changes in #2504. The change seems to be OK, so we should be fine to publish this.

proto-loader: Bump version to 0.7.9

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/test/backend.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts

Enables the test for the feature that was added in #2555.

grpc-js-xds: interop: add custom_lb test, reformat test list

---

packages/grpc-js/src/load-balancer-pick-first.ts

If subchannel wrap isn't equals and wrap's real subchannel is same, will result subchannel‘s state listener loss. When grpc server down, pick first can't change connectivity state to TRANSIENT_FAILURE, and load-balancing-call doPick function will infinite call.

Fix pick-first-load-balancer pick subchannel lost state listener

---

packages/grpc-js/src/transport.ts

The issue with not handling the error was reported in #2562, but this is the right way to handle the error.

grpc-js: Handle keepalive ping error

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

grpc-js: Fix pick-first-load-balancer pick subchannel lost state listener (1.9.x)

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts
packages/grpc-js-xds/src/load-balancer-xds-wrr-locality.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-ip.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel-address.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/test-pick-first.ts
packages/grpc-js/test/test-resolver.ts

This includes most of the changes in the in-progress [gRFC A61: IPv4 and IPv6 Dualstack Backend Support](https://github.com/grpc/proposal/pull/356). In particular, this has the following changes:
- The `updateAddressList` method of a `LoadBalancer` now takes an `Endpoint` list instead of a `SubchannelAddress` list. An `Endpoint` contains a list of `SubchannelAddresses`.
- Resolver results are an `Endpoint` list instead of a `SubchannelAddress` list.
- The round_robin LB policy now delegates to pick_first for each endpoint, instead of managing subchannels directly.
- The outlier_detection LB policy now tracks call results and ejections by endpoint instead of by address.
- The `SubchannelInterface` now includes additional methods for reporting health state separately from connectivity …

grpc-js: Make pick_first the universal leaf policy, plus related changes

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts
packages/grpc-js-xds/src/load-balancer-xds-wrr-locality.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-pick-first.ts

The `ring_hash` LB policy will need access to a channel option, and this is the cleanest way to do that. I also tweaked the pick_first changes from #2561 so that the `reportHealthStatus` option is passed in using an internal channel option instead of a special constructor argument.

grpc-js: Pass channel options to LoadBalancer constructors

---

packages/grpc-js/package.json
packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-load-balancer.ts

This makes a few improvements to issues exposed by the test linked from #2570, specifically related to closing a connection immediately after it is established
1. In `ResolvingLoadBalancer`, reset the backoff timer when name resolution succeeds.
2. In `DnsResolver`, start the timers before starting resolution, because the timers can be cancelled immediately after starting resolution, and if they can happen in the wrong order they won't actually be cancelled.
3. Also in `DnsResolver`, cancel the rate limiting timer when outputting a result for an IP address target. The purpose of the rate limit is to limit DNS query traffic, and an IP address target does not result in a DNS query so the rate limit is unnecessary.
Experimental changes:
- Added `BackoffTimeout#getEndTime`, to get the …

grpc-js: Make a few improvements to DNS resolving timing

---

packages/proto-loader/README.md
packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

Currently, `grpcLib` is required, and the types generated use it. With this change, the option can be omitted, and as a result the root file, client, and service implementation types are not generated, and the `ServiceDefinition` types do not reference the `grpc` library. Message and Enum types are still generated without any changes.
This change is mainly needed to implement [gRFC L106: Node Health Check Library 2.0](https://github.com/grpc/proposal/blob/master/L106-node-heath-check-library.md) to enable that library to implement a service without reference to a specific grpc implementation library.

proto-loader: Allow the `grpcLib` option to be omitted in the type generator

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/test/client.ts
packages/grpc-js-xds/test/test-core.ts

This fixes #2579 (as far as I can tell). The `destroy` method was not resetting the right state, and as a result, it would not start a new watch for the LDS resource, or for the RDS resource once the LDS resource is received.

grpc-js-xds: Fix behavior when channel goes IDLE

---

packages/grpc-js/src/resolving-load-balancer.ts

I believe this will fix the failure seen in [this affinity test run](https://fusion2.corp.google.com/invocations/8df8c4b8-7e16-4b8f-9e32-5a120922461e/targets/grpc%2Fnode%2Fmaster%2Fxds_k8s_lb%2Faffinity_test/tests). This change mirrors behavior in `updateState` from #2568.

grpc-js: Delegate to child picker in ResolvingLoadBalancer#updateResolution

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/generated/cluster.ts

I published version 1.9.1 with the wrong submodule commit checked out, resulting in an inconsistent package that can't load. The distrib tests didn't catch this because they were run with the correct submodule commit. The `prepare` script runs before publishing, so this forces the submodule and the code generated from it to be the correct version.

grpc-js-xds: Force submodule update and code generation in prepare script

---

packages/grpc-js-xds/package.json

I added this in #2582 to try to avoid situations where we publish with the wrong submodule commit checked out, but it turns out that we need to run local `npm install` in contexts where we don't have git, so this doesn't work.

grpc-js-xds: Don't call git commands in npm scripts

---

examples/cancellation/README.md
examples/cancellation/client.js
examples/cancellation/server.js

This is modeled after the [Go cancellation example](https://github.com/grpc/grpc-go/tree/master/examples/features/cancellation). In my own testing, it appears that the `cancelled` event is not actually triggered on the server. I consider this a bug, which is tracked in #2583.

Add cancellation example

---

examples/error_handling/README.md
examples/error_handling/client.js
examples/error_handling/server.js

This is modeled after the [Go error handling example](https://github.com/grpc/grpc-go/tree/master/examples/features/error_handling), but with additional code for streaming responses, because errors are sent and handled differently in that case.

Add error handling example

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

This was making the tests taking a long time to exit after finishing. Our general principle is that grpc should keep the process open if and only if there is a pending request or other surface API event (e.g. channel state change). If a call is not assigned to a connection, the channel has a timer that keeps the process open, and if the call is assigned to a connection, the corresponding transport keeps the connection open. Either way, the subchannel is never responsible for that, so it should unref any timers or other handles that it owns.

grpc-js: Unref backoff timer in subchannel

---

packages/grpc-js/package.json
packages/grpc-js/src/server.ts

Tests shared in #2581 show that if `bindAsync` is called, and then `tryShutdown` or `forceShutdown` is called before the `bindAsync` operation completes, the result is that the port stays bound forever, holding the process open. This fixes the error by adding a `shutdown` flag that is set by `tryShutdown` and `forceShutdown`, and ensuring that `bindAsync` does not leave ports bound if that flag is set. Specifically, it throws an error if `bindAsync` is called after shutdown, and adds checks after getting the resolver result and in the `listen` callback to not continue binding ports and/or close any bound ports.

grpc-js: Handle race between bindAsync and (try|force)Shutdown

---

examples/cancellation/README.md
examples/cancellation/server.js

Explicitly state that the server could get either the `cancelled` event or the `end` event, because that is what actually happens.

Cancellation example: corrected information

---

packages/grpc-js/src/channel-credentials.ts

I was looking at this code just to understand the credentials behavior and was having trouble wrapping my head around how insecure credentials could accept call credentials but not allow composing them. Then I realized it is an unused parameter in a private constructor, the public entry point never passes it call credentials. As it's private, I guess it should be OK to remove this to make the code's intent clearer.

chore(grpc-js): remove unused callcredentials parameter from insecure impl

---

doc/environment_variables.md
packages/grpc-js/src/index.ts
packages/grpc-js/src/logging.ts

This fixes #2594 by removing the `index` tracer and moving the relevant information (the library version) into the common prefix of all trace log messages. That will also help confirm the version in the frequent case when people provide snippets of trace logs that don't include the first log, or don't have the `index` tracer enabled. I also included the PID because sometimes people provide logs with output from multiple processes interspersed, and this will help separate them.

grpc-js: Include library version and PID in all trace logs

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts

Specifically, propagate error information from transport code to subchannel connectivity state updates, and from there to pickers returned by pick_first and round_robin. This will help debug connectivity errors, particularly in cases when the request errors do not occur close to the connection attempts in the logs.
The change to the `UnavailablePicker` constructor to accept partial status objects is copied from master.
This change does not cover xDS code.

grpc-js: Propagate connectivity error information to request errors

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

This implements the change described in [gRFC L107](https://github.com/grpc/proposal/pull/395). In short, servers will start serving as soon as ports are bound, and `Server#start` has no functional effect.

grpc-js: Deprecate Server#start

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/test/test-pick-first.ts

This fixes two aspects of the pick_first LB policy's behavior while in sticky TF mode:
1. When it gets an address update, it should do a happy eyeballs pass. Instead it was skipping that for some reason.
2. When it enters sticky TF mode, it requests address reresolution, but after that, if it stays in sticky TF mode, there is no trigger to request reresolution again, potentially leading to a perpetually stale address list.

grpc-js: pick_first: fix happy eyeballs and reresolution in sticky TF mode

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts

This fixes the memory leak reported in https://github.com/grpc/grpc-node/issues/2448#issuecomment-1782690279, according to my manual testing.

grpc-js: Cancel and don't start idle timer on shutdown

---

packages/grpc-js/package.json
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-ip.ts
packages/grpc-js/test/test-pick-first.ts

This should fix https://github.com/grpc/grpc-node/issues/2604#issuecomment-1784525579. PR #2602 changed pick_first behavior so that it would request a resolver update the first time every subchannel reported TRANSIENT_FAILURE after an address list update. With subchannel reuse, a subchannel could already be in TRANSIENT_FAILURE immediately after an address list update, so pick_first would request a resolver update immediately. The rate limit on DNS targets would rate limit that whole process, but the same is not true of IP targets, causing a tight loop that does nothing. IP targets will never return a different address list, so the result is to just not respond to resolver update requests. The flag is reset in the `destroy` function because that is how channel idleness is handled, and an …

grpc-js: Don't repeat fixed resolver results

---

packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts

When the target gRPC URI doesn't contain a port, and as such defaults to the default HTTPS port, the code didn't send the port as part of the `HTTP` `CONNECT` request when a proxy is configured, leading to proxies rejected the request with a 400 Bad Request, as the request line is malformed.
We saw this while using `firebase/firestore` which uses gRPC underneath by default, and connect to "firestore.googleapis.com" without a port by default.
Contributed by courtesy of [swimm.io](https://swimm.io/)

Fix missing port in proxy CONNECT when using the default HTTPS port

---

packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/uri-parser.ts
packages/grpc-js/test/test-server.ts

This implements [L109: Node: Server API to unbind ports](https://github.com/grpc/proposal/blob/master/L109-node-server-unbind.md).
Most of the work was in refactoring `bindAsync` to make `unbind` implementable, and introducing tracking of previous `bindAsync` calls as a unit. As a result, `bindAsync` behavior has slight changes to observable behavior: when making a `bindAsync` call with the same target string as a previous call, if the credentials are equivalent, the result of the previous call is passed along to the new callback, but if they are different, the new call fails with an error.
The new `ServerCredentials#_equals` and `combineHostPort` functions are new utility functions that were needed to implement the new `bindAsync` behavior.
The change in `subchannel.ts` was a fix to …

grpc-js: Implement `Server#unbind`

---

packages/grpc-js/src/resolver-uds.ts

#2609 did not include the UDS resolver. This fixes that.

grpc-js: Return the result from the UDS resolver only once

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/test/test-pick-first.ts

This fixes the bug described in https://github.com/grpc/grpc-node/issues/1490#issuecomment-1814642543. #2609 was introduced to prevent a busy loop when pick_first is in TRANSIENT_FAILURE, and the resolver always returns the result immediately. However, making the resolver only return once caused pick_first to never update after going from READY to IDLE when a connection drops. This fixes that by making `exitIdle` use the most recent address list. This will result in some wasted work if the address list is stale, but if `exitIdle` is called there should also be a resolver update pending, so it will be eventually consistent.

grpc-js: Make pick_first use exitIdle

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

I believe this is the cause of #2621. This is a very similar problem to the one fixed in #2559. The potential incorrect behavior here is that a subchannel in the subchannel list is the same as the one that has been picked, but it is wrapped with a different object so the check here compares false, resulting in removing the listener erroneously. That would cause pick_first to not react to subsequent changes in the subchannel state, which matches the log shown in #2621. I don't actually know of a code path that could cause this this outcome, but it's best to be consistent in how we check this anyway.

grpc-js: pick_first: fix currentPick comparison in resetSubchannelList

---

packages/grpc-reflection/src/implementations/reflection-v1.ts

I found issue:
More info about issue #2631 
```typescript
const toVisit: IFileDescriptorProto[] = [...(this.fileDependencies.get(file) || [])];
while (toVisit.length > 0) {
const current = toVisit.pop();
if (!current || visited.has(current)) {
continue;
}
visited.add(current);
toVisit.push(...this.fileDependencies.get(current)?.filter((dep) => !visited.has(dep)) || []);
}
return Array.from(visited);
}
```

Fix issue #2631 [@grpc/grpc-reflection] Issue with proto file dependencies only on second or next request

---

packages/grpc-reflection/README.md

I noticed that **ReflectionServer** is imported in the Readme but only **ReflectionService** exists in the project's index.ts

fix grpc-reflection README: rename import

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Source: https://github.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
New repo: https://github.com/grpc/psm-interop
New path: `.kokoro/psm_interop_kokoro_lib.sh`
Ref https://github.com/grpc/psm-interop/pull/16.

buildscripts: Use the Kokoro shared install lib from the new repo

---

packages/grpc-js/src/index.ts

I think `VerifyOptions` should be export.

fix: export type VerifyOptions

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2635 to @grpc/grpc-js@1.9.x.
---
Source: https://github.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
New repo: https://github.com/grpc/psm-interop
New path: `.kokoro/psm_interop_kokoro_lib.sh`
Ref https://github.com/grpc/psm-interop/pull/16

buildscripts: Use the Kokoro shared install lib from the new repo (@grpc/grpc-js@1.9.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2635 to @grpc/grpc-js@1.7.x.
---
Source: https://github.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
New repo: https://github.com/grpc/psm-interop
New path: `.kokoro/psm_interop_kokoro_lib.sh`
Ref https://github.com/grpc/psm-interop/pull/16

buildscripts: Use the Kokoro shared install lib from the new repo (@grpc/grpc-js@1.7.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2635 to @grpc/grpc-js@1.8.x.
---
Source: https://github.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
New repo: https://github.com/grpc/psm-interop
New path: `.kokoro/psm_interop_kokoro_lib.sh`
Ref https://github.com/grpc/psm-interop/pull/16

buildscripts: Use the Kokoro shared install lib from the new repo (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js/src/subchannel.ts

In this promise resolution handler, we have a transport that has just finished connecting. We only use it if the subchannel is currently in the CONNECTING state. If it is not, we just drop the transport on the floor. However, it is still holding the resources related to an established connection, so we have to release those by calling `transport.shutdown()`.
I discovered this bug while investigating #2641.

grpc-js: Shutdown transport if a state change occurs while connecting

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts

This fixes #2642: in the current idle timer implementation, if `getConnectivityState(true)` is called multiple times, it can lose track of idle timer handles without cancelling them, resulting in those timers firing inappropriately and setting the connectivity state to IDLE when that should not happen.
This change has two layers of defense against that failure: first, the timer now cannot be started if one is already running, so it should not be possible to lose track of existing running timers. Second, the client now tracks the timestamp of the last activity, and the idle timer will only actually set the state to IDLE if enough time has passed since the last activity.
In addition, this second change is part of an optimization to the idle timeout behavior: previously, the timer would …

grpc-js: Fix and optimize IDLE timeouts

---

doc/environment_variables.md
packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/test/client.ts
packages/grpc-js-xds/test/test-core.ts
packages/grpc-js/README.md
packages/grpc-js/package.json
packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/logging.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-ip.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/service-config.ts
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-pick-first.ts
packages/grpc-js/test/test-server.ts

These changes have been accumulating for a while.

Merge 1.9.x into master

---

packages/grpc-health-check/package.json

Currently, `typescript` is installed as a dependency in `grpc-health-check` package, but it's only used during build. This pull-request moves it to a dev dependency.

grpc-health-check: Move `typescript` as a dev dependency

---

packages/grpc-js/src/call-interface.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server-interceptors.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/test-channelz.ts
packages/grpc-js/test/test-server-deadlines.ts
packages/grpc-js/test/test-server-interceptors.ts

This is an implementation of gRFC L112, currently in review at grpc/proposal#406. I had to rewrite a lot of the server-side request handling code to accommodate the new API, and I think the result is an improvement.
I changed a couple of existing tests because the previous behavior was incorrect:
- A test previously asserted that when a server sends an error, channelz counts it as a failed stream in the socket data. However, a stream should be counted as successful if the server explicitly ended it with trailers.
- Previously, the server sent an `OUT_OF_RANGE` status when receiving an invalid `grpc-timeout` value, but the library is not allowed to generate that status, so I changed it to `INTERNAL`.
The new test file shows a few over-simplified examples of using the server interceptor …

grpc-js: Implement server interceptors

---

packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js/package.json

grpc-js/grpc-js-xds: Bump version to 1.10.0

---

packages/grpc-js-xds/test/backend.ts
packages/grpc-js-xds/test/test-core.ts
packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts

This fixes #2666. After #2561, round_robin delegates to pick_first for each endpoint. As a result, it runs into essentially the same problem pick_first had that was fixed in #2619: once a child has a READY->IDLE transition, nothing triggers it to start connecting again. round_robin is supposed to have every child connected or connecting at all times, so the fix is to have the child reconnect immediately after it goes to IDLE.
The test is in the xDS package because that is where the problem was detected, because round_robin is used much more in the xDS context.
Note that this won't impact the channel-level idle timeout, because the channel discards the current LB policy when it goes idle.

grpc-js: round_robin: always have children reconnect immediately

---

packages/grpc-reflection/proto/sample/sample.proto
packages/grpc-reflection/proto/sample/unscoped.proto
packages/grpc-reflection/src/implementations/common/utils.ts
packages/grpc-reflection/src/implementations/reflection-v1.ts
packages/grpc-reflection/test/test-reflection-v1-implementation.ts
packages/grpc-reflection/test/test-utils.ts

Bugfix to handle references to root-level message types in the default (unspecified) package from issue #2671. This was causing warnings about failed lookups to any message type that:
1. Was in the default package (eg. no `package` directive in the proto file), and
2. Was at the top-level of the package, not nested in another message
The root cause of this was a bug in the `scope` utility where, when we were seeking up the package scope for where the symbol reference lived, we skipped over the root (`.`) package. Relevant snippet from bug report:
> we end up with `TopLevelMessage` being indexed as `.TopLevelMessage` and the reference to it from `ProcessRequest` being sourced from the scope `.ProcessRequest`. When checking the index the search goes like this in order:
>   1. Check current …

fix(grpc-reflection): [#2671] handle references to root-level message types in default package

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

This implements gRFC L114 (currently in review at grpc/proposal#418). So, it will fix #2317.

grpc-js: Add Server#createConnectionInjector API

---

packages/grpc-reflection/package.json
packages/grpc-reflection/proto/sample/sample.proto
packages/grpc-reflection/src/implementations/reflection-v1.ts
packages/grpc-reflection/test/test-reflection-v1-implementation.ts

This is a follow up to #2673, and fixes #2671 according to my manual testing. The new comment basically explains this change:
> In files with no package, symbols are populated in the symbols table with a leading period in the key. If there is a package, the symbol does not have a leading period in the key. For simplicity, we check without the period, then with it.
CC @jtimmons

reflection: Fix references to symbols with no package

---

packages/grpc-js/src/load-balancer-pick-first.ts

From [A62](https://github.com/grpc/proposal/blob/master/A62-pick-first.md):
> If this connection breaks at a later point in time, `pick_first` will not attempt to reconnect until the application requests that it does so, or makes an RPC.
This was a mistake in #2511, but without #2619 and [this change in #2568](https://github.com/grpc/grpc-node/commit/3a43cba3a3a5afb5c0bbfc621922ee023f977e5e#diff-569f9a9708121d140658da08c9840dc00b0dde21c880b320bc251a20cf1fda02), it probably wouldn't work correctly.
This error was pointed out in https://github.com/grpc/grpc-node/pull/2677#issuecomment-1974839742.

grpc-js: pick_first: Don't automatically reconnect after connection drop

---

examples/keepalive/README.md
examples/keepalive/client.js
examples/keepalive/server.js
examples/package.json

This adds an example of configuring client and server keepalive options, modeled on [the Go example](https://github.com/grpc/grpc-go/tree/master/examples/features/keepalive). Note that ping enforcement settings are not included because that functionality is not implemented in Node.
I had to bump the minimum required grpc-js version to 1.10.2 because that is the version that added support for the `grpc.max_connection_idle_ms` server option.

Add keepalive example

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

This change (#2680) was the only one in 1.10.2 that affected the request path, so it is the most likely cause of #2690.

Revert #2680 "grpc-js: pick_first: Don't automatically reconnect after connection drop"

---

packages/grpc-js/src/server-interceptors.ts
packages/grpc-js/test/test-server-interceptors.ts

The idea with the part of the code modified here is that the user can pass in a partially filled in responder or server listener, and the rest of the object will be filled in with defaults so that the rest of the class can handle it more simply. Unfortunately, the specific strategy of doing that using the spread operator (`...`) works with unpopulated object fields, but not object fields set to `undefined`, which is what `ResponderBuilder` and `ServerListenerBuilder` produce.
The test auth interceptor partially populates both a listener and a resolver, so switching it to use the builders should ensure that it catches this problem on both sides.

grpc-js: Ensure server interceptors work with builder utility classes

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts

Based on the hypothesis that #2625 is caused by RST_STREAM rate limiting (for rapid reset mitigation), this change reduces the chances of that by avoiding sending an RST_STREAM from the client when the server has already half-closed its side of the connection.

grpc-js: Avoid sending redundant RST_STREAMs from the client

---

examples/interceptors/README.md
examples/interceptors/client.js
examples/interceptors/server.js

This adds the interceptor example, based largely on the [Go example](https://github.com/grpc/grpc-go/tree/master/examples/features/interceptor). I split up the interceptor functionality differently, because the interceptor API is different.
When writing these examples I discovered a bug in the implementation; the fix is out for review in #2696. With that fix in place, the examples work fine.

Add interceptors example

---

packages/grpc-js-xds/interop/Dockerfile
packages/grpc-js-xds/package.json
packages/grpc-js/package.json
packages/grpc-js/src/generated/channelz.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Address.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Channel.ts
packages/grpc-js/src/generated/grpc/channelz/v1/ChannelData.ts
packages/grpc-js/src/generated/grpc/channelz/v1/ChannelTrace.ts
packages/grpc-js/src/generated/grpc/channelz/v1/ChannelTraceEvent.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Channelz.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetChannelResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetServerResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetServerSocketsResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetServersResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetSocketResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetSubchannelResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/GetTopChannelsResponse.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Security.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Server.ts
packages/grpc-js/src/generated/grpc/channelz/v1/ServerData.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Socket.ts
packages/grpc-js/src/generated/grpc/channelz/v1/SocketData.ts
packages/grpc-js/src/generated/grpc/channelz/v1/SocketOption.ts
packages/grpc-js/src/generated/grpc/channelz/v1/SocketOptionLinger.ts
packages/grpc-js/src/generated/grpc/channelz/v1/SocketOptionTimeout.ts
packages/grpc-js/src/generated/grpc/channelz/v1/Subchannel.ts

The main change here is to upgrade from TypeScript 4 to TypeScript 5 in the `@grpc/grpc-js-xds` package. This fixes an issue where the generated code changes from #2693 would not be accepted by the compiler.
I also modified `grpc-js` so that it uses the local copy of `proto-loader`, to avoid delays in detecting these issues, and I updated the committed copy of the generated code.

grpc-js-xds: Use TypeScript 5

---

packages/grpc-js-xds/scripts/xds.sh

#2700 changed grpc-js and grpc-js-xds dev builds to use the local proto-loader installation for faster test turnaround on protobuf TypeScript code generation changes. That PR included changes to the Dockerfile to handle that local usage correctly. This change does the same thing for the legacy test script.

grpc-js-xds: Make legacy interop script use proto-loader correctly

---

packages/grpc-js/src/client.ts

Some applications may explicitly set `Error.stackTraceLimit = undefined`.
In this case it is not safe to assume `new Error().stack` is available using the `!` operator.
Before this patch, using grpc-js in this situation when an Error occurs or when a trace is needed may result in uncaught exceptions crashing the application.
One thing I considered is that often stack traces are indented by four spaces by the JS engine such as node. My default message for clarity is just `no track trace available` versus using the magic number of spaces. I'm torn on the right solution here, but I personal prefer the clarity of a plain string rather than assuming our environment is one which adds random spaces to make CLI focused output prettier.

Resolve exception when Error.stackTraceLimit is undefined

---

packages/grpc-js/src/client.ts

Backport #2701: Resolve exception when Error.stackTraceLimit is undefined

---

packages/grpc-js/src/call-interface.ts
packages/grpc-js/src/deadline.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/subchannel-address.ts
packages/grpc-js/src/subchannel-call.ts

Currently, the details string in a client-side deadline exceeded error is just "Deadline exceeded". This change adds more information to that, to help narrow down the cause of those errors. Specifically, it shows a breakdown of any time taken before the request was actually sent to a specific server, along with the address of the server if it was sent. For example, an error string from a test with all information shown looks like this:
```
Deadline exceeded after 1.001s,name resolution: 0.000s,metadata filters: 0.002s,previous attempts: 0,time to current attempt start: 0.001s,LB pick: 0.006s,remote_addr=[::1]:45251
```
This is just a first pass to get some useful information into the error string, and to add the framework to add or change individual pieces of information there as …

grpc-js: Add more info to deadline exceeded errors

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-channel-credentials.ts

grpc-js: Call custom `checkServerIdentity` when target name override is set

---

gulpfile.ts
packages/proto-loader/package.json

#2700 added a cross dependency between grpc-js and proto-loader, so now proto-loader needs to be built before grpc-js. This change fixes the root gulpfile to respect that order.
I also added the `ts-node` dev dependency in proto-loader because it is needed to run that gulpfile in isolation, for testing.

Fix build order in root gulpfile to handle cross dependency

---

packages/grpc-js/package.json
packages/grpc-js/src/server-interceptors.ts

I think this is the cause of #2707. If headers are queued to send but have not actually been sent because they were blocked by TCP flow control, the server will get to this point and think that it should send a trailers-only response. The new check is more correct anyway: sending a trailers-only response should depend on whether the application has decided to send anything else.

grpc-js: Fix check for whether to send a trailers-only response

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

PSM Interop: Migrate to Artifact Registry

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2712 to @grpc/grpc-js@1.10.x.
---

PSM Interop: Migrate to Artifact Registry (@grpc/grpc-js@1.10.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2712 to @grpc/grpc-js@1.9.x.
---

PSM Interop: Migrate to Artifact Registry (@grpc/grpc-js@1.9.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2712 to @grpc/grpc-js@1.8.x.
---

PSM Interop: Migrate to Artifact Registry (@grpc/grpc-js@1.8.x backport)

---

packages/grpc-js-xds/scripts/xds_k8s_lb.sh
packages/grpc-js-xds/scripts/xds_k8s_url_map.sh

Backport of #2712 to @grpc/grpc-js@1.7.x.
---

PSM Interop: Migrate to Artifact Registry (@grpc/grpc-js@1.7.x backport)

---

packages/proto-loader/package.json
packages/proto-loader/src/index.ts
packages/proto-loader/test/descriptor_type_test.ts
packages/proto-loader/test_protos/method_options.proto

This PR adds support for [MethodOptions](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto#L887-L919) to proto-loader.
It is a continuation of #2230 (originally written by @hiepthai) which tries to address the comments of @murgatroid99.

grpc-loader: Expose method options

---

packages/proto-loader/bin/proto-loader-gen-types.ts

For client class types, the code generator generates two method declarations for each method: one for the exact original name, and one for the camel case version of the name. Using `Set` avoids duplication if both of those are the same.
This fixes #2686.

proto-loader: Avoid generating duplicate method declarations in some cases

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts

This makes a couple of changes to HTTP status code handling:
1. When surfacing a gRPC error synthesized from an HTTP status code, the details string now contains the actual status code number.
2. When a call ends with no trailers received and there was a non-OK HTTP status code, surface that error instead of a more generic error about not receiving trailers. This fixes #2722.
I also added some information to the "RST_STREAM with code 0" error to explain what it means semantically, and I had to refactor `handleTrailers`. That refactor does change the behavior slightly, mainly to prioritize the gRPC status over the HTTP status when provided, which I think is more correct behavior.

grpc-js: Improve reporting of HTTP error codes

---

packages/grpc-health-check/package.json
packages/grpc-reflection/package.json
packages/proto-loader/package.json

This sets the minimum version to the one with the fix for [CVE-2023-36665](https://nvd.nist.gov/vuln/detail/CVE-2023-36665).
Also update the dependency on proto-loader in the health check and reflection packages.

proto-loader: Update dependency on protobufjs

---

packages/grpc-js/src/client.ts
packages/grpc-js/test/test-server-errors.ts

The new `call.startRead()` call is the fix for the main bug. Previously the  I also changed the client to use the `UNIMPLEMENTED` status code for cardinality violations to make it consistent with the server, and because that is what the spec actually says.
This fixes #2768.

grpc-js: Fix client hang when receiving extra messages for a unary response

---

packages/grpc-js/src/server.ts
packages/grpc-js/src/transport.ts

Improve server-side keepalives, possibly resolve bug where keepalive errors were not being treated as errors.
- Bugfix: Ensure that if session.ping returns false we correctly identify fail the keepalive and connection
- Bugfix: Ensure that if the interval between keepalives being sent occurs faster than the prior keepalive's timeout that we do not overwrite the reference to the prior timeout. Before this change: we could have in theory prevented a valid keepalive timeout from clearing itself because it's object reference was replaced with a newer timeout. This rewrite keeps every timeout as a local (vs a shared state per session). Even if the timeout outlives the lifetime of a session, we still guard against errors by checking that the parent interval is not falsy. I reckon this could …

Keepalive bugfixes and unify timers strategies between client and server

---

packages/grpc-js/src/http_proxy.ts

When using an HTTP CONNECT proxy, it is possible for the server's first HTTP2 packet to reach the client before the node's HTTP library even starts parsing the HTTP `HTTP/1.1 200 Connected` response.
When that happens, node's HTTP response parser may take these extra bytes (i.e. the server's first HTTP2 packets) out of the socket into its parsing buffer. That means that these extra bytes will not be emitted through the tunneled socket provided on the `connect` event. Instead, these extra bytes are provided through [the `head` parameter of the `connect` event](https://nodejs.org/docs/latest/api/http.html#event-connect_1).
This PR reinjects these extra bytes (if any) into the tunneled socket.
Fixes #2744.

HTTP CONNECT: handle early server packets

---

packages/grpc-js/src/http_proxy.ts

Added support for URL encoded user credentials.
Previously, if a username/password contained a special character that required encoding, eg `grpc_proxy=http://user%40example.com:password@127.0.0.1:8888`, then the connection would be rejected (40x).

fix: add decoding for url encoded user credentials

---

packages/grpc-js/src/compression-filter.ts

The changes for https://github.com/grpc/grpc-node/security/advisories/GHSA-7v5v-9h63-cj86 inadvertently removed client-side checking for sending overly large message. That is not a security issue, because that check is just for early notification of the error that the other side would send.

grpc-js: Re-add client-side max send message size checking

---

packages/grpc-js/src/http_proxy.ts

Both of those PRs are patch changes.

Backport #2746 and #2761 to 1.10.x

---

packages/grpc-js/src/service-config.ts
packages/grpc-js/test/test-retry-config.ts

This PR corrects five error messages in grpc-js's `serviceConfig` validation:
- 3 typos corrected from `Invld` to `Invalid`
- 2 corrected to say that strings containing decimals are valid in `initialBackoff` and `maxBackoff` values of `retryConfig`.
Validation for `initialBackoff` and `maxBackoff` in `retryConfig` use the following regex which allows decimals:
```
/**
* Recognizes a number with up to 9 digits after the decimal point, followed by
* an "s", representing a number of seconds.
*/
const DURATION_REGEX = /^\d+(\.\d{1,9})?s$/;
```
However, the error messages for `initialBackoff` and `maxBackoff` in `validateRetryPolicy` state that the values "must be a string consisting of a positive integer followed by s".
I discovered this when correcting a copied Go serviceConfig containing …

[grpc-js] Fix error messages in `serviceConfig` validation

---

doc/environment_variables.md
gulpfile.ts
packages/grpc-js/gulpfile.ts
packages/grpc-js/src/environment.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/test/test-resolver.ts

As per issue https://github.com/grpc/grpc-node/issues/2775, this pr adds support for overriding the authority on DNS resolver.

fix: support authority overrides in the DNS resolver

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-idle-timer.ts

I think there are cases where it can take about double the configured idle timeout for a connection to actually go idle. This waits for triple the time for a margin of error.

grpc-js: Increase state change deadline in server idle tests

---

packages/grpc-js/src/internal-channel.ts
packages/grpc-js/test/test-client.ts

This fixes #2786. This change ensures that if a channel closes while it has pending calls that are not attached to a connection, those calls will end, instead of waiting for a connection forever.

grpc-js: Ensure pending calls end after channel close

---

packages/grpc-js/src/server-call.ts

This is a follow up to the change that adds that API to `ServerInterceptingCall`, to make that information more consistently available. This fixes #2762.

grpc-js: Add `getHost` to surface server call classes

---

packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js/README.md
packages/grpc-js/package.json

grpc-js: Bump packages to 1.11.0, and update documentation

---

packages/grpc-js-xds/README.md
packages/grpc-js-xds/package.json
packages/grpc-js/README.md
packages/grpc-js/package.json

#2796 but actually on the 1.11.x branch.

grpc-js: Bump packages to 1.11.0, and update documentation (actually on 1.11.x this time)

---

packages/grpc-js/src/retrying-call.ts
packages/grpc-js/test/test-retry.ts

In version 1.11.1, grpc client crashes if receives custom error code with error `cannot read properties of undefined reading .toLowerCase()`

fix(grpc-js): client crash on custom error code

---

packages/grpc-js/src/transport.ts

Some recent trace logs indicate that a session `error` event can be emitted without a `close` event, so we propagate errors from those events directly instead of waiting for the `close` event.

grpc-js: Report session error events instead of waiting for close

---

packages/grpc-js/src/internal-channel.ts

In internal-channel.ts file there is a trace after channel is constructed.
In this trace, the full stacktrace is added.
The trace is written only when the log level is on trace, but the stacktrace is calculated in any case.
We found in our usage, that if you have a big bundle file it can take few seconds to calculate the stacktrace, it can be reasonable in trace mode but not in production.
See https://github.com/grpc/grpc-node/pull/2816 for the conversation with @murgatroid99.

made the call to trace to be called only when tracer is enabled

---

packages/grpc-js/src/certificate-provider.ts
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-certificate-provider.ts
packages/grpc-js/test/test-channel-credentials.ts
packages/grpc-js/test/test-end-to-end.ts

This is foundational work for [gRFC A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md). I put it in the main library because it doesn't use any xDS features. The xDS library will use these APIs to apply its configuration. As part of this change, channel credentials now have internal reference counting APIs, though only the new credentials use them.
Also, while I was trying to get this to work, I noticed and fixed a bug in the pick_first LB policy that caused it to report stale connectivity error messages.

grpc-js: Add file watcher certificate provider, and credentials that use them

---

packages/grpc-js/src/call-credentials.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/test/test-call-credentials.ts

The method name is required to create valid SIGv4 authenticated requests for [Amazon VPC Lattice](https://docs.aws.amazon.com/vpc-lattice/latest/ug/sigv4-authenticated-requests.html).
This is available in multiple implementations (c++, Golang, PHP).
See also 
- https://grpc.io/docs/guides/auth/#extending-grpc-to-support-other-authentication-mechanisms
- https://docs.aws.amazon.com/vpc-lattice/latest/ug/sigv4-authenticated-requests.html#sigv4-authenticated-requests-golang

Provide the method_name for the CallCredentials callback generateMetadata

---

packages/grpc-js/src/load-balancer-pick-first.ts

This includes a few related changes to the pick_first LB policy to simplify its behavior, in order to reduce the chances of reaching a bad state, and to make it easier to reason about:
- In `pickSubchannel`, avoid assuming that the subchannel to be picked has any state related to this LB policy instance; in particular, don't assume that it has the state change listener registered, and don't have special case behavior if it's the same subchannel as the current pick. Instead, unconditionally reset the LB policy state and set up the relevant subchannel state from scratch.
- In `resetSubchannelList`, remove the special case when handling the current pick.
- In `connectToAddressList`, don't take any additional actions when immediately picking one of the new subchannels.
- In …

grpc-js: Simplify pick_first behavior

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-round-robin.ts

This should fix #2824. It looks like round_robin was previously relying on pick_first (the leaf balancer) to request name resolution whenever an individual connection would be dropped, but that behavior was a bug that was fixed in #2784. So, round_robin needs to request name resolution itself.

grpc-js: round_robin: Request resolution on connection drop

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-ring-hash.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-resolver.ts
packages/grpc-js-xds/src/load-balancer-xds-wrr-locality.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-pick-first.ts

This will be used as part of the implementation of [gRFC A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md) to allow the CDS LB policy to see whether or not the user has provided `XdsCredentials` and if so replace them with the file watcher credentials as configured by CDS.

grpc-js: Construct LB policies with credentials and enable them to override subchannel credentials

---

packages/grpc-js-xds/src/xds-bootstrap.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js/src/certificate-provider.ts
packages/grpc-js/src/duration.ts
packages/grpc-js/src/experimental.ts

As [described in A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md#certificate-provider-plugin-framework), this adds handling for the `certificate_provider` field in the xDS bootstrap file, and a registry of certificate provider plugins configured this way.

grpc-js-xds: Add bootstrap certificate provider config handling

---

packages/grpc-js/src/duration.ts
packages/grpc-js/test/test-duration.ts

It wasn't correctly handling the case where the decimal part was omitted. So it would handle "1.5s" correctly, but "1s" would cause it to throw an error.

grpc-js: Fix duration parsing bug

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/transport.ts

Adding fix to ignore self-signed certificates verification

Adding fix to ignore self-signed certificates verification

---

packages/grpc-js-xds/package.json
packages/grpc-js/package.json

This release just has a few minor changes, but #2832 is part of a launch.

grpc-js: Bump to 1.12.0

---

packages/grpc-js-xds/package.json
packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-retry.ts

When I cut the 1.12.x branch, I didn't realize that the 1.11.x branch hadn't been merged into master. This fixes that.

grpc-js: Port bugfixes from 1.11.x into 1.12.x

---

packages/grpc-js/package.json
packages/grpc-js/src/certificate-provider.ts

This fixes https://github.com/grpc/grpc-node/issues/2834#issuecomment-2401398011

grpc-js: Use util.promisify instead of fs/promises for Node 12 compatibility

---

packages/grpc-tools/src/node_generator.cc

This pull request fixes file generation to work with grpc-js. The bug is that the second argument of the makeClientConstructor function is missing, although it is required.

Fixed generation of grpc services

---

packages/grpc-js-xds/src/xds-dependency-manager.ts
packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/test/test-pick-first.ts

This change fixes two significant bugs introduced in #2844:
1. pick_first reported IDLE instead of TRANSIENT_FAILURE when provided a zero-length address list. This caused all calls to queue for LB picks instead of ending with an error, which means that they piled up quickly.
2. As a consequence of the way in-use clusters were retained, the xDS dependency manager would provide the config again every time a call was committed (or at least most of the time).

grpc-js-xds: Fix a couple of bugs with the config tears change

---

packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/test/framework.ts
packages/grpc-js-xds/test/test-core.ts

Currently it only passes along updates to new children. This was fine when the cds LB policy was responsible for watching for Cluster resource updates, but now that those updates come in along with the LB policy config updates, the xds_cluster_manager needs to pass them along.

grpc-js-xds: xds_cluster_manager: pass along updates to existing children

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-ring-hash.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-wrr-locality.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-pick-first.ts

This reverts PR #2821. After discussions in the team, I decided that it makes more sense to go in a different direction to implement xDS channel credentials.

Revert "grpc-js: Enable LB policies to override subchannel credentials"

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-ring-hash.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/load-balancer-xds-wrr-locality.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-pick-first.ts

This removes the channel options argument from the `LoadBalancer` constructor and adds it to the `updateAddressList` method, replacing the `attributes` argument. Resolver attributes are now added to channel options, as are any other values that need to be passed between LB policies but don't go in the LB policy config. Channel options that start with the string defined in `SUBCHANNEL_ARGS_EXCLUDE_KEY_PREFIX` will not be passed to subchannel constructors or used to determine subchannel uniqueness.

grpc-js: Pass channel args to LB policies with updates

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/server.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/test/client.ts

The old version of `@types/node` had a declaration of the `Buffer` declaration that is incompatible with new versions of TypeScript, so this update resolves that. The only changes that needed to be addressed with code changes were:
1. The `NodeJS.Timer` type has been replaced with `NodeJS.Timeout`.
2. The `localAddress` field in the `Socket` type is no longer guaranteed to be populated.

grpc-js-xds: Update `@types/node` and update code for compatibility

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-channel-credentials.ts

This modifies the `ChannelCredentials` API so that instead of providing the connection options which are used to establish a TLS connection, it provides a `SecurityConnector`, which is created using information about a specific subchannel, and is responsible for establishing TLS connections on top of TCP connections.
With this change, the steps of establishing an HTTP/2 session are more cleanly divided:
- The transport establishes the TCP connection, potentially delegating to the proxy connection code.
- The security connector establishes the TLS connection on top of the TCP connection (or passes it through untouched, in the case of insecure credentials)
- The transport creates the HTTP/2 session on top of the socket provided by the security connector.

grpc-js: Add security connector, rework connection establishment

---

packages/grpc-js/package.json
packages/grpc-js/src/transport.ts

With this change, socket closure causes open streams to report UNAVAILABLE instead of another code when possible. This handling previously existed, but was lost in the refactor that added the transport.

grpc-js: Restore socket disconnect handling

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/transport.ts

This changes a few things to try to report connection drops with the UNAVAILABLE status more consistently:
- The transport now passes the connection drop event along to the call even if a GOAWAY has already been handled. This is important in the server-side graceful connection shutdown case, in which the server always first sends a GOAWAY and then drops the connection seconds later.
- The transport now passes the connection drop event along immediately instead of waiting with a `setImmediate`, to ensure that the call sees the event as quickly as possible.
- The call now delays handling the event with a `setImmediate` to mimic the old sequencing in most cases, but first flags that a connection drop event was seen. User reports indicate that Node (or nghttp2) probably synthesizes a …

grpc-js: Improve event sequencing when handling connection drops

---

packages/grpc-js-xds/package.json

`gts` has a peer dependency on `typescript` that was incompatible with the dependency we declared.

grpc-js-xds: Update gts to be compatible with typescript version

---

packages/grpc-js-xds/src/index.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/resources.ts
packages/grpc-js-xds/src/xds-credentials.ts
packages/grpc-js-xds/src/xds-resource-type/cluster-resource-type.ts
packages/grpc-js-xds/src/xds-resource-type/listener-resource-type.ts
packages/grpc-js-xds/test/client.ts
packages/grpc-js-xds/test/framework.ts
packages/grpc-js-xds/test/test-xds-credentials.ts
packages/grpc-js/src/certificate-provider.ts
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/test-channel-credentials.ts

This adds the `XdsChannelCredentials` class, as specified in [gRFC A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md). This also includes some other changes to accommodate that:
- `CertificateProviderChannelCredentials` have been modified so that if the initial attempt to load certificates is still pending, the secure connector waits for them instead of immediately failing.
- `CallCredentials` are no longer extracted from `ChannelCredentials` at channel creation time. Instead, they are provided by the secure connector, and by the subchannel that owns it.

grpc-js-xds: Add XdsChannelCredentials

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-priority.ts
packages/grpc-js-xds/src/load-balancer-ring-hash.ts
packages/grpc-js-xds/src/load-balancer-weighted-target.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-impl.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/test/test-custom-lb-policies.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-outlier-detection.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolving-load-balancer.ts

This modifies the `ChannelControlHelper#updateState` function signature to add an `errorMessage` argument, which can be either a string or null. The expectation is that it should be a string when the status is TRANSIENT_FAILURE, and null otherwise. The purpose of this is to enable LB policies with multiple children to provide some error information from clients when synthesizing an aggregate status to be passed to their parents. In order to avoid including excessive information in the status message, each such LB policy only passes along the last error message it has seen from any child.

grpc-js: Propagate error messages through LB policy tree

---

.github/workflows/grpc-tools-build.yml

Similar to #2815, but changing the upload and download sides at the same time.

bump actions/download-artifact and actions/upload-artifact from 2 to 4 in grpc-tools build workflow

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel-call.ts

grpc-js: Prioritize HTTP status errors over message decoding errors

---

packages/grpc-js-xds/src/xds-client.ts

This fixes #2875 by never deleting `typeStates` entries in `AdsCallState` once they are created. As a result, the nonce will persist for the duration of the ADS stream. In addition, handling nonces for unknown types is not an issue because a type stays known for the duration of the stream after it is requested once, and we do not guarantee handling of the case where a control plane sends a resource type that was never requested.
The only functional impact that I can see of this change is that it will send a `DiscoveryRequest` with an empty `resource_names` list after unsubscribing from the last resource of a particular type, and I believe that is the correct behavior.
This should not meaningfully impact resource usage, because a type state with no resources is just two strings and an …

grpc-js-xds: Preserve resource type version and nonce when unsubscribing

---

packages/grpc-js/README.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/transport.ts

This PR adds support for setting an `initialWindowSize` in the http2 session. This fixes #2429, as described in the issue the default window size is 64Kb which is OK for typical http2 use cases but isn't so good for usage inside internal networks with larger response sizes.
I have chosen to add a channel option to implement this as it seemed the most sensible way to make this change. Please advise if there is a better way to achieve this.

feat(grpc-js): allow configurable http2 initial window size

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Preserve resource type version and nonce when unsubscribing (1.12.x)

---

packages/grpc-js-xds/src/xds-dependency-manager.ts
packages/grpc-js-xds/test/test-core.ts

It looks like the problem fixed in #2879 may have been shadowing a logic error in the xDS dependency manager that is causing the change_backend_service interop test to fail, but with the current logging it's hard to tell what the problem is. This change adds two kinds of detailed trace logging to try to understand that problem:
- Log each resource watch start and end, with a reason
- Log whenever `maybeSendUpdate` does not send an update, with a reason
I also added a test to try to replicate the change_backend_service test locally, but it didn't reproduce the failure.

grpc-js-xds: Add more detailed xDS dependency manager logging

---

packages/grpc-tools/README.md
packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_generator.h
packages/grpc-tools/src/node_plugin.cc

Fixes #2865 
This adds a new flag `omit_serialize_instanceof` which, when set, omits the `instanceof` check from the generated JS code. It defaults to `false`, which retains the current behavior (ie. with the check).

feat(grpc-tools): add omit_serialize_instanceof generator option

---

packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts

First, this modifies the `ConfigSelector` API to make it an object instead of a function. The object has an `invoke` method, which is called the same way the function was previously called, and an additional `unref` function, which signals the end of the lifetime of the `ConfigSelector`. This allows resolvers to track and act on the lifetime of the `ConfigSelector`.
Second, this modifies the xDS resolver so that it keeps a cluster ref for each cluster that a `ConfigSelector` can select, for the lifetime of the `ConfigSelector`, plus an additional ref for each call for which a cluster has been selected, until that call is committed. This ensures that once a `ConfigSelector` is created, every cluster it can select will be subscribed to continuously until no more calls need it.

grpc-js-xds: Reference clusters for ConfigSelector lifetime

---

packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/retrying-call.ts

The main change here is to modify the implementation of the `grpc.enable_retries` option. Now, when it is set to 0, instead of skipping `RetryingCall` entirely and making `LoadBalancingCall` a direct child of `ResolvingCall`, `RetryingCall` is used in a new mode that does not perform any retries.
The main purpose of this is to create a place to correctly call `CallConfig#onCommitted` consistently, whether or not that option is set. Previously, it would only be called in `LoadBalancingCall` after starting the `SubchannelCall`. This was both too early (if the call was later retried) and it could fail to be called (if the LB pick failed).
One other change this required was performing the functionality of `commitCall` even if the underlying call already completed, which means that buffered …

grpc-js: Always use RetryingCall, always call onCommitted

---

doc/environment_variables.md
packages/grpc-js/src/http_proxy.ts

**Issue created https://github.com/grpc/grpc-node/issues/2878**
**Issue:** 
The grpc-js lib doesn't support having CIDR blocks in the **NO_PROXY** variable (like 172.16.0.0/12
192.168.0.0/16). It only checks if the address we target is in the list of IPs in the NO_PROXY. Hence, it supposes that NO_PROXY is a list of single IPs.
For example if the NO_PROXY contains 192.168.0.0/16 and the IP you're trying to reach is 192.168.0.10. This latter is NOT considered in the range of the NO_PROXY because the lib just compares the IP to the elements of the NO_PROXY list.
We also want to support the case where we whitelist domain name suffixes in the NO_PROXY (like example.com, .internal., .local. ).
**What is done in this PR:**
- Parse NO_PROXY list to get the ip and the prefix length of the CIDR
- …

fix: support CIDR blocks in no_proxy env variable

---

packages/grpc-js-xds/src/xds-client.ts

grpc-js-xds: Preserve resource type version and nonce when unsubscribing (1.11.x)

---

packages/grpc-js-xds/src/xds-client.ts

Backport https://github.com/grpc/grpc-node/pull/2879 to 1.10.x

grpc-js-xds: Preserve resource type version and nonce when unsubscribing (1.10.x)

---

packages/grpc-js-xds/src/xds-client.ts

Backport https://github.com/grpc/grpc-node/pull/2879 to 1.9.x

grpc-js-xds: Preserve resource type version and nonce when unsubscribing (1.9.x)

---

examples/retry/README.md
examples/retry/client.js
examples/retry/server.js

This is essentially a one-to-one port of the [Go retry example](https://github.com/grpc/grpc-go/tree/master/examples/features/retry).

Add retry example

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/transport.ts

This fixes a bug caught by interop tests that caused Google Front End servers to reject requests made by this library over TLS. Our best guess at a proximate cause for this error is that the request has an unexpected `:scheme` header value of `http` instead of `https` because that is the scheme used in the URL passed to `http2.connect`.
In order to consistently use the correct scheme, `SecureConnector#connect` now annotates the result with an additional field indicating whether the connection is secure, and this value determines the scheme.

grpc-js: Connect with https scheme when using TLS

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts

This addresses #2893 to the greatest extent reasonable.
This PR includes 3 changes to allow garbage collection of IDLE channels:
- Modify the subchannel wrapper used by the channel so that it does not register itself until it has a ref, to handle the fact that pick_first may never ref some subchannels.
- Don't run the `callRefTimer` until a call is started, and stop it when the channel goes IDLE.
- Move the channelz info into a separate object, so that the reference from channelz only keeps that object alive instead of the whole channel.
A caveat here is that repeatedly creating and discarding channels without closing them will still leak some memory with channelz, because the channel is never unregistered with channelz, so channelz needs to retain the associated data. This does not …

grpc-js: Allow garbage collection of IDLE channels

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts

Backport #2891 to 1.12.x with a version bump.

grpc-js-xds: fix LrsCallState statsTimer memory leak

---

packages/grpc-js-xds/src/xds-resource-type/cluster-resource-type.ts
packages/grpc-js-xds/src/xds-resource-type/endpoint-resource-type.ts
packages/grpc-js-xds/src/xds-resource-type/listener-resource-type.ts
packages/grpc-js-xds/src/xds-resource-type/route-config-resource-type.ts
packages/grpc-js-xds/src/xds-resource-type/xds-resource-type.ts

Previously, when validating resources, the validation function would short circuit on the first error, and the NACK would contain a generic message indicating that the resource failed to validate. Now the validation functions find every validation error, and report the details of all of them.

grpc-js-xds: NACK with detailed validation errors

---

packages/grpc-js-xds/interop/test-client.Dockerfile
packages/grpc-js-xds/interop/test-server.Dockerfile
packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/interop/xds-interop-server.ts
packages/grpc-js-xds/src/index.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/server.ts
packages/grpc-js-xds/src/xds-credentials.ts
packages/grpc-js-xds/src/xds-dependency-manager.ts
packages/grpc-js-xds/src/xds-resource-type/listener-resource-type.ts
packages/grpc-js-xds/test/test-xds-credentials.ts
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/channelz.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-channel-credentials.ts
packages/grpc-js/test/test-server-credentials.ts
packages/grpc-js/test/test-server.ts
test/kokoro/psm-security.cfg

This change also includes a variety of fixes to make those tests pass:
- Fix parsing of SAN entries to correctly handle colons in names.
- Handle unset `CommonTlsContext.validation_context_type`.
- Handle unset `filter_chain_match`.
- Add `Server` protected methods `experimentalRegisterListenerToChannelz`, `experimentalUnregisterListenerFromChannelz`, and `experimentalCreateConnectionInjectorWithChannelzRef`.
- Modify `ServerCredentials` to separate options that are used once on `Http2Server` construction from options that can be updated such as by a certificate provider.
- Make transport and channel credentials connection establishment code handle and report more connection errors.
- Wait for credentials information to be loaded from certificate providers before starting to connect, to …

grpc-js-xds: Implement and enable security interop tests

---

packages/grpc-js-xds/package.json
packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts

In preparation for a 1.13.x release.

Merge 1.12.x into master

---

packages/grpc-js-xds/src/load-balancer-ring-hash.ts

This fixes a bug that causes ring_hash to proactively connect to a second backend if the first backend it connects to does not happen to be first in the list.

grpc-js-xds: ring_hash: Fix proactive connect logic when already connecting

---

packages/grpc-js-xds/interop/test-client.Dockerfile
packages/grpc-js/src/backoff-timeout.ts

Trying to debug a test failure in which the client does not seem to be backing off after a connection error.

grpc-js: Add backoff timer trace logging

---

packages/grpc-js/src/auth-context.ts
packages/grpc-js/src/call-interface.ts
packages/grpc-js/src/call.ts
packages/grpc-js/src/client-interceptors.ts
packages/grpc-js/src/load-balancing-call.ts
packages/grpc-js/src/resolving-call.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server-interceptors.ts
packages/grpc-js/src/subchannel-call.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-channel-credentials.ts

Implement [gRFC L35](https://github.com/grpc/proposal/blob/master/L35-node-getAuthContext.md)

grpc-js: Add getAuthContext call method

---

packages/grpc-js/src/backoff-timeout.ts

If `runOnce` is called by the callback (which does happen in subchannels), it will set `running` to `true` before the timer handler sets it to `false`, resulting in an invalid `running` state. This change fixes that by resolving the state before calling the callback.

grpc-js: Fix reentrancy problem in backoff timer callback

---

packages/proto-loader/README.md
packages/proto-loader/bin/proto-loader-gen-types.ts

Add the following two options to `proto-loader-gen-types`:
- `targetFileExtension`: File extension for generated files. Defaults to `.ts`
- `importFileExtension`: File extension for import specifiers in generated code. Defaults to none (omitted)
The default behavior of `proto-loader-gen-types` is kept unchanged to avoid any possible breaking on existing usage, and the output is only modified when options are provided as needed.
Closes #2907

feat(proto-loader-gen-types): add options for specifying file extensions

---

packages/grpc-js/src/retrying-call.ts
packages/grpc-js/test/test-retry.ts

This fixes #2923.
Since I was in there, I also reordered the feature check in the `RetryingCall` constructor to check whether the feature is entirely disabled first.

grpc-js: Fix min/max switch in retry throttler

---

packages/grpc-js/package.json
packages/grpc-js/src/internal-channel.ts

Since `this.options` is modified on line 295, all later uses of the `options` object should refer to `this.options` instead of the local `options` variable. In particular, the change to the `ResolvingLoadBalancer` constructor call fixes #2932, because after #2854 the channel options get to the subchannel constructor through the LB policy, instead of getting merged with the channel options in `channelControlHelper.createSubchannel`, and the `options` variable didn't contain the proxy information that the subchannel would use to connect through a proxy.

grpc-js: Consistently reference the same options object in the channel constructor

---

packages/grpc-js/src/transport.ts

A user noted in https://github.com/grpc/grpc-node/issues/2669#issuecomment-2764910982 that Nagle's algorithm may contribute to performance issues some people experience. This change is consistent with the other implementations:
- C core sets TCP_NODELAY [here](https://github.com/grpc/grpc/blob/168a1caf9d2ae35aae72ecb62e88348a893664d7/src/core/lib/iomgr/socket_utils_common_posix.cc#L242).
- gRPC Java calls `setTcpNoDelay` [here](https://github.com/grpc/grpc-java/blob/a13fca2bf2cddd58d917865bc0bb24036c5eb873/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L745)
- [Go disables Nagle's algorithm by default](https://news.ycombinator.com/item?id=34179426)

grpc-js: Disable Nagle's algorithm

---

packages/grpc-js/src/transport.ts

Dino does not implement `http2.getDefaultSettings()` (https://github.com/denoland/deno/issues/28566). This change avoids triggering that issue by setting the `initialWindowSize` setting only if the channel option is set instead of falling back to the default setting.

grpc-js: Avoid calling http2.getDefaultSettings

---

packages/proto-loader/package.json

proto-loader: Bump to 0.7.14

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/package.json

This is an update to the feature added in #2912 that fixes the oversight described in https://github.com/grpc/grpc-node/issues/2907#issuecomment-2815240648.

proto-loader: Apply targetFileExtension to root files

---

packages/grpc-health-check/proto/health/v1/health.proto

Clients cannot get a list of the services a certain server is watching to and their respective status.
In the context of Kubernetes, we have livez and readyz endpoints, by listing all the services a server is checking, we could return a response like the `/readyz?verbose` Kubernetes API returns:
```
[+]ping ok
[+]log ok
[+]etcd ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]poststarthook/start-cluster-authentication-info-controller …
```

Add List method to Health service

---

packages/grpc-js/package.json
packages/grpc-js/src/channel-credentials.ts

This fixes #2955 (I think). The logic to set SNI from the proxy connection target was implemented twice, and the second one was overriding the setting from the `ssl_target_name_override` option. This change fixes that by removing the duplicate logic and rearranging the rest.

grpc-js: Fix ability to set SNI with ssl_target_name_override option

---

packages/grpc-js/src/retrying-call.ts

Resolves: https://github.com/grpc/grpc-node/issues/2959

fix(grpc-js): fix jitter for client retries

---

packages/grpc-js-xds/src/xds-dependency-manager.ts

This aligns LOGICAL_DNS handling with the changes described in https://github.com/grpc/proposal/pull/477. It looks like we previously did not have the old correct behavior, in that we were passing multiple endpoints without forcing the pick_first LB policy.

grpc-js-xds: Combine endpoints for LOGICAL_DNS clusters

---

examples/debugging/README.md
examples/debugging/client.js
examples/debugging/server.js

This example is closely based on [the corresponding Go example](https://github.com/grpc/grpc-go/tree/master/examples/features/debugging), except that, like with the load balancing example, it doesn't need a custom resolver to connect to multiple addresses.

Add debugging example

---

packages/grpc-js-xds/interop/generated/test.ts
packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/generated/ads.ts
packages/grpc-js-xds/src/generated/cluster.ts
packages/grpc-js-xds/src/generated/csds.ts
packages/grpc-js-xds/src/generated/endpoint.ts
packages/grpc-js-xds/src/generated/fault.ts
packages/grpc-js-xds/src/generated/http_connection_manager.ts
packages/grpc-js-xds/src/generated/listener.ts
packages/grpc-js-xds/src/generated/lrs.ts
packages/grpc-js-xds/src/generated/pick_first.ts
packages/grpc-js-xds/src/generated/rbac.ts
packages/grpc-js-xds/src/generated/ring_hash.ts
packages/grpc-js-xds/src/generated/route.ts
packages/grpc-js-xds/src/generated/tls.ts
packages/grpc-js-xds/src/generated/typed_struct.ts
packages/grpc-js-xds/src/generated/wrr_locality.ts
packages/grpc-js-xds/test/generated/echo.ts
packages/grpc-js/package.json
packages/grpc-js/src/generated/channelz.ts
packages/grpc-js/test/generated/Request.ts
packages/grpc-js/test/generated/test_service.ts
packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/echo.ts
packages/proto-loader/package.json
packages/proto-loader/src/index.ts
packages/proto-loader/test/descriptor_type_test.ts

This implements the change described in https://github.com/grpc/proposal/pull/503 for both the runtime generator and the TypeScript generator. This doesn't add any types to the API, it just makes the serialize and deserialize functions more generally usable. It breaks the API by changing the `MessageTypeDefinition` type signature, so I bumped the version.

proto-loader: Output functions to serialize and deserialize messages

---

packages/grpc-js/src/single-subchannel-channel.ts

This is a minimal implementation that connects the surface channel API to the subchannel API, to allow generated client classes to make requests on one specific subchannel. This will be used to implement the client-side handling of out-of-band metrics in [gRFC A51](https://github.com/grpc/proposal/blob/master/A51-custom-backend-metrics.md). It will also be useful for implementing [gRFC A17](https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md) in the future.

grpc-js: Add a single-subchannel channel implementation

---

packages/grpc-js/src/index.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/orca.ts
packages/grpc-js/src/single-subchannel-channel.ts
packages/grpc-js/src/subchannel-interface.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/common.ts

This implements the client-side out of band metrics part of [gRFC A51](https://github.com/grpc/proposal/blob/master/A51-custom-backend-metrics.md). This change adds `addMetricsSubscription` and `removeMetricsSubscription` methods to `PickFirstLoadBalancer` and `LeafLoadBalancer`. Petiole load balancing policies can subscribe to out of band metrics updates using those methods.

grpc-js: Implement ORCA client-side OOB metrics

---

packages/grpc-js/src/compression-filter.ts

grpc-js: Declare buffer type to avoid build error (1.13.x)

---

packages/grpc-js/src/compression-filter.ts

Backport https://github.com/grpc/grpc-node/pull/2987 to 1.12.x

grpc-js: Declare buffer type to avoid build error (1.12.x)

---

packages/grpc-js/src/compression-filter.ts

Backport https://github.com/grpc/grpc-node/pull/2987 to 1.11.x

grpc-js: Declare buffer type to avoid build error (1.11.x)

---

packages/grpc-js/src/compression-filter.ts

Backport https://github.com/grpc/grpc-node/pull/2987 to 1.9.x

grpc-js: Declare buffer type to avoid build error (1.9.x)

---

packages/grpc-health-check/src/generated/grpc/health/v1/Health.ts
packages/grpc-health-check/src/generated/grpc/health/v1/HealthListRequest.ts
packages/grpc-health-check/src/generated/grpc/health/v1/HealthListResponse.ts
packages/grpc-health-check/src/health.ts
packages/grpc-health-check/test/generated/grpc/health/v1/Health.ts
packages/grpc-health-check/test/generated/grpc/health/v1/HealthListRequest.ts
packages/grpc-health-check/test/generated/grpc/health/v1/HealthListResponse.ts
packages/grpc-health-check/test/generated/health.ts
packages/grpc-health-check/test/test-health.ts

This PR introduces the implementation of the new `List` endpoint to the `Health` service in order to list all the services that a certain server is watching to.
It also adds generated files for the endpoint and its tests. 
I would like to write some tests too but I couldn't run the test suite as it is as I get some errors, any help is appreciated.
```
gulpfile.ts:28:19 - error TS2339: Property 'parallel' does not exist on type 'Gulp'.
28 const lint = gulp.parallel(jsCore.lint);
gulpfile.ts:30:20 - error TS2339: Property 'series' does not exist on type 'Gulp'.
30 const build = gulp.series(protobuf.compile, jsCore.compile, jsXds.compile);
```
gRPC-proto added in https://github.com/grpc/grpc-node/pull/2951
https://github.com/grpc/proposal/pull/468

Health list endpoint

---

packages/grpc-js/package.json
packages/grpc-js/src/duration.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-weighted-round-robin.ts
packages/grpc-js/src/priority-queue.ts
packages/grpc-js/src/resolver-ip.ts
packages/grpc-js/src/single-subchannel-channel.ts
packages/grpc-js/test/generated/EchoMessage.ts
packages/grpc-js/test/generated/EchoService.ts
packages/grpc-js/test/generated/echo_service.ts
packages/grpc-js/test/test-priority-queue.ts
packages/grpc-js/test/test-weighted-round-robin.ts

This implements the weighted_round_robin LB policy as described in [gRFC A58](https://github.com/grpc/proposal/blob/master/A58-client-side-weighted-round-robin-lb-policy.md). The change to add it as an xDS endpoint picking policy will be in a separate PR.

grpc-js: Implement weighted_round_robin LB policy

---

test/kokoro/psm-light.cfg

This is the test job to run the federation test, with https://github.com/grpc/psm-interop/pull/185.

grpc-js-xds: Add psm-light test job config

---

packages/grpc-js-xds/scripts/xds.sh

With #2978, the grpc-js install script now needs access to the contents of a submodule. So, this script now runs `git submodule update` before any `npm install`.

grpc-js-xds: interop: Fix order of submodule update and npm install

---

packages/grpc-js-xds/interop/test-client.Dockerfile
packages/grpc-js/package.json
packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/internal-channel.ts
packages/grpc-js/src/retrying-call.ts
packages/grpc-js/src/transport.ts
packages/grpc-js/test/test-channel-credentials.ts
packages/grpc-js/test/test-retry.ts

To prepare for the 1.14.x release.

Merge v1.13.x into master

---

examples/routeguide/dynamic_codegen/route_guide_server.js

.start() method is directly integrated in the bindAsync function

removed the .start() method as it is deprecated
