- kokoro-linux.sh
> Add Kokoro test script

- test/kokoro/linux.cfg
- test/kokoro/macos.cfg
> Add Kokoro config for Linux/MacOS

- packages/grpc-js-core/gulpfile.js
- packages/grpc-js-core/package.json
This change corrects sourcemaps, and specifies files that will be bundled in the npm package for js-core.
> Update js-core gulpfile and packaging

- gulpfile.js
- package.json
- packages/grpc-health-check/gulpfile.js
- packages/grpc-js-core/gulpfile.js
- packages/grpc-native-core/gulpfile.js
- packages/grpc-native-core/package.json
- run-tests.sh
- test/gulpfile.js
- test/kokoro/linux.cfg
- test/kokoro/macos.cfg
The XML file names are going to be based on timestamp and not anything useful, but it's better than nothing.
> Add Jenkins XML reporting to tests

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/ext/call_credentials.cc
- packages/grpc-native-core/ext/call_credentials.h
This updates the submodule and credentials code to match changes made in grpc/grpc#12374.
This should fix grpc/grpc#12781.
> Update grpc submodule

- run-tests.sh
I think this might fix grpc/grpc#12978.
> Try not updating npm in tests

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
Seemed easier to just make a new PR for #72 
I made the changes to `package.json.template` and should now be PR-ing to the right branch!
> Include index.d.ts in the published npm package

- packages/grpc-js-core/src/channel.ts
This streamlines some of the channel state transition code and adds proper channel reconnection support with exponential backoff in the pure JS implementation, in accordance with the [Connectivity Semantics and API](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md) and [Connection Backoff Protocol](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md) documents.
I removed the idle timeout code because it wasn't correct, and according to grpc/grpc#13212, the C core doesn't have that either.
> Fix channel state code and add backoff code

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
> Backport "Build different binaries for different libc’s (a.k.a. support alpine linux)"

- packages/grpc-native-core/package.json
This picks up a security bugfix from the C core (specifically grpc/grpc#13642).
> Update v1.7.x branch to 1.7.3

- packages/grpc-native-core/ext/server.cc
This improves the situation reported in #142.
> Add JS error for missing callback to sever#tryShutdown

- package.json
- packages/grpc-js-core/package.json
- packages/grpc-js-core/src/channel.ts
- packages/grpc-js-core/test/test-call-stream.ts
- packages/grpc-js-core/test/test-channel-credentials.ts
- packages/grpc-js/package.json
This change addresses compiler errors stemming from TS 2.7.
> Fix TS compiler errors and pin TS to 2.7

- package.json
- packages/grpc-js-core/package.json
- packages/grpc-js-core/src/channel.ts
- packages/grpc-js-core/test/test-call-stream.ts
- packages/grpc-js-core/test/test-channel-credentials.ts
- packages/grpc-js/package.json
- packages/grpc-native-core/src/client.js
- test/api/credentials_test.js
- test/api/surface_test.js
- test/interop/interop_client.js
This should wait until #164 is merged to ensure that all of the changes in v1.8.x get into v1.9.x
> Merge master into v1.9.x

- packages/grpc-native-core/index.d.ts
- packages/grpc-native-core/index.js
> Fix documentation of part of the type signature for server credentials

- packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.bat
- packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.sh
> Adding electron 1.8 support.

- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
- packages/grpc-native-core/tools/buildgen/generate_projects.sh
Also removing the temporary build.yaml override from it.
> Upmerge from v1.10.x

- packages/grpc-js-core/package.json
- packages/grpc-protobufjs/package.json
CC @wenbozhu. These are the names we want to release these packages under.
> Update js and protobuf package names

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/templates/binding.gyp.template
> Hide symbols.

- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
This doesn't correspond to a tagged version in the grpc/grpc repo, but I want to publish a package with grpc/grpc#14804.
> Upgrade to v1.10.1

- README.md
- packages/grpc-js-core/README.md
- packages/grpc-protobufjs/README.md
This just adds some basic documentation to the two newer packages that we want to publish soon.
> Add README files for new packages

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/templates/binding.gyp.template
I just want to close out that issue.
> Backport "Removing zdefs" to v1.11.x

- packages/grpc-js-core/src/index.ts
This makes the API of the pure JS library more consistent with the existing library. I also added the wrapper function `waitForClientReady`.
> Pure JS: Add unimplemented errors for several API functions

- packages/grpc-protobufjs/package.json
It updates to protobufjs@6.8.6.
> Fixes #277 ReDoS Vulnerability

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
> Add a missing directory to grpc package.json

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
I also updated lodash in the package.json template to match the changes to package.json
> V1.12.0 update

- gulpfile.ts
- package.json
- packages/grpc-js-core/src/channel.ts
- packages/grpc-protobufjs/package.json
- run-tests.sh
- test/api/interop_sanity_test.js
- test/gulpfile.js
- test/interop/interop_client.js
Reverts grpc/grpc-node#340. I will fix the condition for running coverage code in the test script as discussed.
> Revert "Revert "Add coverage reporting for JavaScript and TypeScript files""

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
- packages/grpc-native-core/tools/run_tests/artifacts/build_all_linux_artifacts.sh
- run-tests.bat
- run-tests.sh
- tools/release/cross/Dockerfile
- tools/release/kokoro.sh
- tools/release/native/Dockerfile
Expected conflicts in build & release scripts with all the GCF kerfuffle, and the usual build.yml conflict.
> 1.12.2 upmerge

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/templates/binding.gyp.template
In particular, https://github.com/grpc/grpc/pull/15595
> Changes needed for the nanopb dep refactoring work

- packages/grpc-js-core/package.json
> Publish .d.ts files in grpc-js. Also bump the version

- packages/grpc-protobufjs/README.md
- packages/grpc-protobufjs/package.json
- packages/grpc-protobufjs/src/index.ts
> proto loader: make options properly optional. +minor documentation fix

- packages/grpc-native-core/ext/slice.cc
- packages/grpc-native-core/test/surface_test.js
- packages/grpc-native-core/test/test_service.proto
- test/interop/interop_client.js
> Properly create slices from utf8 strings.

- packages/grpc-native-core/index.js
> Stop using lodash's template generator.

- test/interop/interop_client.js
We'll do an actual utf8 test interop separately. @adelez will coordinate this.
Fixes https://github.com/grpc/grpc/issues/16078.
> Reverting the utf8 part of our interop test.

- packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node_arm.sh
Otherwise we won't have arm32 binaries again :)
> Upmerge from 1.13.x

- test/api/interop_sanity_test.js
- test/interop/interop_client.js
> Add special_status_message interop test

- packages/grpc-native-core/ext/channel_credentials.cc
- packages/grpc-native-core/index.d.ts
- packages/grpc-native-core/package.json
- packages/grpc-native-core/src/credentials.js
- packages/grpc-native-core/templates/package.json.template
- packages/grpc-native-core/test/credentials_test.js
This is a port of #403 into the 1.14 branch. CC @JackOfMostTrades.
> Backport "Add checkServerIdentity callback"

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
We need this to do another build with #476.
> Update to v1.14.0-pre3

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
This is specifically to pull in grpc/grpc#16276
> Bump to v1.14.0-pre4

- packages/grpc-native-core/index.d.ts
> Fix typo in typescript definitions file

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
I don't think anything else needs to be done before we publish 1.14 for real.
> Update to v1.14.0

- packages/grpc-native-core/README.md
Explaining the option to change the location of the precompiled-binaries. Related to #441 and #117.
> Updated doc in readme.md

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
We want to publish #492 and #496.
> Bump to version 1.14.1

- .gitignore
These are annoyingly showing up :-)
> Ignoring automated test reports.

- packages/grpc-js-core/src/call.ts
This change allows users to handle errors from server streams like this: https://github.com/googleapis/nodejs-spanner/blob/v1.4.0/src/database.js#L984-L991
> Pure JS: emit 'status'/'error' before 'end' for server streams

- packages/grpc-js-core/README.md
- packages/grpc-js-core/package.json
This is in preparation for the upcoming beta release.
> Update pure JS version, README

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Bumping to 1.14.2

- packages/grpc-js-core/src/call-credentials-filter.ts
The channel and stream credentials may change between the time a `CallCredentialsFilterFactory` is created and the time that the metadata is sent. This commit delays composing the credentials until the time metadata is sent.
For context, I observed test failures when updating from 0.2.0 to 0.3.0. No other changes were involved. After some debugging, I noticed that incorrect metadata was being sent to the server because the composed credentials were created too early. [These tests](https://github.com/cjihrig/grpc-server-js/blob/master/test/server-credentials.js#L235-L334), ported from this repo, are what began failing (as well as some tests in private repos).
> grpc-js-core: delay composing credentials

- packages/grpc-js-core/package.json
More patches need to be published
> Bump @grpc/grpc-js to 0.3.2

- .gitignore
- packages/grpc-native-core/src/client.js
> Backport "Call invocation transformer"

- packages/grpc-native-core/src/server.js
- packages/grpc-native-core/test/async_test.js
Implementation of grpc/proposal#108
> Native: add Server#bindAsync

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
We were actually pointing at 1.15 there.
> Properly updating submodule to point at 1.16.

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
> Update grpc submodule to HEAD

- packages/grpc-js-core/src/filter-stack.ts
This commit replaces combinations of `bind()`, `map()`, and `flow()` with simple `for` loops. This improves performance, and lessens the dependency on lodash.
> grpc-js-core: remove use of flow() and flowRight()

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Update to 1.16.0

- packages/grpc-native-core/src/client.js
replace _.assign with Object.assign
> refactor: replace _.assign with Object.assign

- packages/grpc-native-core/src/metadata.js
- packages/grpc-native-core/src/server.js
> refactor: drop usage of _.forOwn

- packages/grpc-native-core/src/client_interceptors.js
- packages/grpc-native-core/src/common.js
refactor: drop usage of _.flatMap
> refactor: drop usage of _.flatMap

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
And finally getting rid of all the node 11 shenanigans...
> Bumping to 1.16.1 for release.

- run-tests.bat
- run-tests.sh
And thus closing the loop on node 11, finally.
> Adding node 11 tests.

- packages/grpc-native-core/src/client.js
- packages/grpc-native-core/src/protobuf_js_5_common.js
- packages/grpc-native-core/src/protobuf_js_6_common.js
refactor: drop usage of _.each
> refactor: drop usage of _.each

- packages/grpc-native-core/src/client.js
refactor: drop usage of _.mapValues
> refactor: drop usage of _.mapValues

- packages/grpc-native-core/src/client.js
refactor: drop usage of _.partial
> refactor: drop usage of _.partial

- packages/grpc-native-core/index.js
> Native: lazily load Protobuf.js

- packages/grpc-native-core/src/protobuf_js_6_common.js
> Native: Protobuf.js 6: use nested again

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Bumping to pre3

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Bumping to 1.17.0

- packages/proto-loader/package.json
This is a patch because the only changes are #615 and #676. #615 has a minor potential behavior change, but only in rare cases that were previously errors.
> Update proto-loader to 0.3.1

- packages/grpc-native-core/index.d.ts
> Native: add details property to StatusError type

- packages/grpc-js/package.json
> grpc-js: bump to 0.3.3

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
I would like to get #705 in before this.
> Bump native to 1.18.0

- packages/proto-loader/package.json
> Bump proto-loader to 0.4.0

- packages/grpc-js/src/index.ts
This PR is similar to #547, but for `grpc-js`. 
Since `google-auth-library` has deprecated `getRequestMetadata` in 2.0.0, we use the new `getRequestHeaders` if it's available. There is no better way to check which auth library version created the given credentials object, so we just check if `getRequestHeaders` is a thing, and if it's there, we use it.
> fix: use getRequestHeaders if available

- packages/grpc-js/package.json
> Bump grpc-js to 0.3.5

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
Update submodule to 1.19.0-dev
> Update submodule on master

- tools/release/kokoro-grpc-tools.bat
- tools/release/kokoro-grpc-tools.sh
> Update submodules in grpc-tools kokoro scripts

- packages/grpc-tools/CMakeLists.txt
- packages/grpc-tools/build_binaries.ps1
- test/kokoro-nodejs-build-test.bat
- tools/release/kokoro-grpc-tools.bat
- tools/release/kokoro-nodejs.bat
> grpc-tools build script fixes part 2

- packages/grpc-tools/build_binaries.ps1
> Final fixes for grpc-tools build for real this time

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
> Bump to 1.19.0-pre1

- packages/grpc-tools/package.json
This is mainly to publish #747 and also try to fix #748.
> Bump grpc-tools to 1.7.1

- packages/grpc-tools/build_binaries.sh
OK, this one should actually fix the problem pointed out in #744.
> Clean more thoroughly to ensure cmake reconfigures

- packages/grpc-js/package.json
- packages/proto-loader/package.json
This should fix grpc/grpc#18245.
> Update typescript version to 3.3

- packages/grpc-js/LICENSE
To be included in the npm package.
> Add LICENSE from http://www.apache.org/licenses/LICENSE-2.0.txt

- packages/grpc-js/package.json
Lawyers want to see the LICENSE.
> Add LICENSE file from project root.

- packages/grpc-js/src/call-stream.ts
This shouldn't directly impact normal behavior of the surface API, but I think it should fix #752.
> grpc-js: call-stream: Don't output messages after status

- packages/grpc-js/package.json
There are a couple of changes I would like to publish.
> Bump grpc-js to 0.3.6

- README.md
Add README.md packages directory link.
> docs(readme): add packages directory link

- package.json
- packages/grpc-js/package.json
- packages/proto-loader/package.json
We need this more on the version branch.
> Update top level typescript dependency (attempt 2)

- package.json
This should fix some build breakages related to missing types.
> Update top level typescript dependency

- packages/grpc-js/src/client.ts
- packages/grpc-js/src/index.ts
> Export missing types, fix a couple of incorrect types

- packages/grpc-native-core/src/client.js
- packages/grpc-native-core/test/surface_test.js
> Native: fix generic Client constructor crashing

- packages/grpc-js/package.json
- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
- packages/grpc-native-core/src/client.js
- packages/grpc-native-core/templates/binding.gyp.template
- packages/grpc-native-core/test/surface_test.js
- packages/proto-loader/package.json
- tools/release/native/Dockerfile
We especially need to get some build fixes into master.
> V1.19 upmerge

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
Finally we can actually publish a new version.
> v1.20.0-pre1 submodule update and version bump

- packages/proto-loader/package.json
This is mainly to publish #811.
> Bump proto-loader version to 0.5.0

- packages/grpc-js/package.json
- packages/grpc-js/src/make-client.ts
- packages/grpc-js/test/test-call-stream.ts
Update grpc-js to the latest version of all dependencies.
> grpc-js: update dependency versions

- packages/grpc-tools/CMakeLists.txt
Maybe this will help with #819.
> Build grpc-tools with static libc

- packages/grpc-tools/package.json
I want to try publishing binaries built with #822.
> Bump grpc-tools to 1.7.3

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
I need to write something here.
> Bump to v1.20.0

- packages/grpc-native-core/templates/package.json.template
We *really* need a test for this... ugh...
> Fixing template.

- gulpfile.ts
- package.json
- packages/grpc-health-check/gulpfile.ts
- packages/grpc-js/gulpfile.ts
- packages/grpc-native-core/gulpfile.ts
- packages/proto-loader/gulpfile.ts
- run-tests.bat
- run-tests.sh
- test/gulpfile.ts
Hopefully this gets the tests working on Node 12 again.
> Update gulp to version 4, rewrite scripts

- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
Backport #828 and #836 to 1.20.x
> Protobufjs typescript types backport

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
> Update to 1.20.1

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Bump to 1.20.2

- packages/grpc-js/package.json
We got a request to publish #850. This needs to be a major bump because of #843.
> Update grpc-js to 0.4.0

- gulpfile.ts
- setup_interop.sh
- setup_interop_purejs.sh
This is the first part of fixing the second failure reported in grpc/grpc#15464.
> Add scripts for setting up interop clients and servers

- gulpfile.ts
It looks like I screwed up #862 and this should fix it.
> Actually export the new script in the gulp file

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Update to v1.21.0-pre1 without overriding the version

- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/test/test-server-errors.ts
- packages/grpc-js/test/test-server.ts
This commit adds bidi streaming RPC support to the server.
> grpc-js: add bidirectional streaming RPC support

- packages/proto-loader/package.json
This is pretty much just to publish #806.
> Bump proto-loader to 0.5.1

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
I need to say something for Mergeable.
> Update to v1.21.0

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Update to v1.21.1

- packages/grpc-js/package.json
To publish #887 when that gets merged
> Update grpc-js to 0.4.1

- packages/grpc-native-core/index.d.ts
> Update some TypeScript types to match documentation and implementation

- packages/grpc-js/src/channel.ts
- test/api/metadata_test.js
This fixes #894. Without the change this new tests reproduces the error from that issue.
> Fix custom metadata handling bug

- packages/grpc-js/package.json
We need to publish #900 and #901.
> Bump grpc-js to 0.4.2

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/templates/binding.gyp.template
This for grpc/grpc#19227 basically.
> Trying to enable C++14.

- packages/grpc-js/package.json
> Update grpc-js to 0.4.3

- packages/grpc-js/src/server-call.ts
This commit adds support for receiving multiple messages in a single `'data'` event from the underlying HTTP2 stream. It also handles potential out of order messages due to asynchronous deserialization of messages.
> grpc-js: handle multiple messages in single 'data' event

- merge_kokoro_logs.js
> Try to fix error reporting in log merging script again

- packages/grpc-tools/package.json
> Update grpc-tools to 1.8.0

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
- packages/grpc-native-core/test/resolver_test.js
> Bump to 1.22.0-pre1

- packages/grpc-js/src/compression-filter.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/test/test-call-stream.ts
- packages/grpc-js/test/test-server-deadlines.ts
- packages/grpc-js/test/test-server-errors.ts
- packages/grpc-js/test/test-server.ts
- test/api/connectivity_test.js
- test/api/error_test.js
- test/api/interop_helper/server.js
- test/api/metadata_test.js
- test/gulpfile.ts
- test/interop/interop_server.js
- test/performance/benchmark_server.js
- test/performance/worker.js
This PR exposes the grpc-js `Server` implementation as public API and enables interop testing.
> grpc-js: expose Server implementation publicly

- packages/grpc-js/package.json
Minor version bump because we're adding the server.
> Bump grpc-js to 0.5.0

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
> Bump to version 1.22.0

- packages/grpc-native-core/README.md
Corrected a few typos and semantics in the readme file.
> Updated README.md

- packages/grpc-js/package.json
We have a few things to publish.
> Bump grpc-js to 0.5.1

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Bump to version 1.22.2

- packages/grpc-js/package.json
> Bump grpc-js to 0.5.2

- packages/grpc-native-core/index.d.ts
Apparently we never merged 1.21 into master.
> Upmerge 1.21.x into 1.22.x

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
- test/kokoro/windows-build-electron.cfg
> Update version to 1.23.0

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
Apparently there's some kind of security fix we need to publish in a patch.
> Update to v1.22.3 (core 1.22.1)

- packages/grpc-native-core/index.d.ts
- packages/grpc-native-core/package.json
- packages/grpc-native-core/templates/package.json.template
I believe this will fix #572 once and for all by simply not having the typescript import from `protobufjs`.
> Duplicate relevant protobufjs type definition

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/build.yaml
- packages/grpc-native-core/package.json
> Update to v1.23.3

- packages/proto-loader/package.json
#877 has been waiting to be published for a while.
> Bump proto-loader to 0.5.2

- packages/grpc-js/package.json
We have a few small changes to publish
> Bump grpc-js to 0.5.3

- packages/grpc-health-check/README.md
- packages/grpc-health-check/package.json
Fixes #569
Signed-off-by: Teju Nareddy <nareddyt@google.com>
> Add documentation for `grpc-health-check`

- packages/grpc-js/package.json
> Bump grpc-js to 0.5.4

- packages/grpc-js/package.json
There are some major changes to publish.
> Bump grpc-js to 0.6.0

- packages/grpc-js/package.json
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/test/test-resolver.ts
> Fix DNS name regex and add tests

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/package.json
> Bump to 1.24.0

- packages/grpc-js/package.json
I think #1052 needs to be published
> Bump grpc-js to 0.6.2

- packages/grpc-js/src/resolver-uds.ts
- packages/grpc-js/src/resolver.ts
- packages/grpc-js/test/test-resolver.ts
> Add UDS resolver

- packages/grpc-js/package.json
Version bump to publish #1055.
> Update grpc-js to 0.6.3

- packages/grpc-js/src/subchannel.ts
The main fix here is adding the READY -> IDLE state transition in the close handler. Without that, the READY -> TRANSIENT_FAILURE transition skips creating a backoff timer, so nothing ever triggers it to move out of TRANSIENT_FAILURE and the subchannel stays broken. This can be a problem in a situation where a backend address is good but the connection has been dropped for reasons such as network inactivity.
> grpc-js: Fix handling of established connection drops in subchannel

- packages/grpc-native-core/index.d.ts
- packages/grpc-native-core/src/metadata.js
Please see #1090 for details.
Signed-off-by: imjoey <majunjiev@gmail.com>
> grpc-native-core: Backport #1090 to 1.25.x

- gulpfile.ts
This should help us understand what is happening when tests fail.
> Don't do anything in parallel in the gulpfile

- packages/grpc-native-core/ext/call.cc
Same as #1162, but on the proper branch.
> Downmerge of #1162

- packages/grpc-native-core/binding.gyp
- packages/grpc-native-core/templates/binding.gyp.template
See https://github.com/nodejs/node-gyp/issues/857 as to why this looks weird.
> Enabling RTTI for Windows.

- packages/grpc-native-core/ext/call.cc
> Fixing "vector: invalid subscript" issue.

- packages/grpc-js/src/subchannel.ts
> fix: prevent exceeding timer limitations when backing off

- packages/grpc-js/prettier.config.js
- packages/grpc-js/src/load-balancer-round-robin.ts
- packages/grpc-js/src/make-client.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-resolver.ts
- packages/grpc-js/tsconfig.json
- packages/grpc-js/tslint.json
This PR introduces full gts configuration generated by `gts init` with manual changes to `tsconfig.json` to enable useful options from existing configuration. I also fixed all reported TSLint issues. `prettier.config.js` allows IDEs to automatically start formatting using a correct configuration.
> build(grpc-js): add full gts configuration and fix TSLint issues

- packages/proto-loader/package.json
- packages/proto-loader/prettier.config.js
- packages/proto-loader/src/index.ts
- packages/proto-loader/test/descriptor_type_test.ts
- packages/proto-loader/tsconfig.json
- packages/proto-loader/tslint.json
Similar to https://github.com/grpc/grpc-node/pull/1172, but I also applied formatting fixes as not many files were affected.
> build(proto-loader):  add full gts configuration and fix reported issues

- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/call.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/compression-filter.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/load-balancer-round-robin.ts
- packages/grpc-js/src/logging.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/service-config.ts
- packages/grpc-js/src/subchannel-pool.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-resolver.ts
This was done using `gts fix`.
> style(grpc-js): format files using gts

- packages/grpc-js/src/metadata.ts
> grpc-js: Add detail to invalid metadata error

- packages/grpc-js/package.json
There are a few different changes to publish.
> grpc-js: bump to 0.6.12

- test/kokoro.bat
- test/kokoro.sh
- tools/release/kokoro-electron.bat
- tools/release/kokoro-electron.sh
- tools/release/kokoro-grpc-tools.sh
- tools/release/kokoro-nodejs.bat
- tools/release/kokoro-nodejs.sh
Why is it failing now? No idea.
> Fix MacOS failure

- test/kokoro.bat
- test/kokoro.sh
- tools/release/kokoro-electron.bat
- tools/release/kokoro-electron.sh
- tools/release/kokoro-grpc-tools.sh
- tools/release/kokoro-nodejs.bat
- tools/release/kokoro-nodejs.sh
#1193 is on master, this one's on 1.25.
> Backport of #1193

- test/interop/interop_client.js
- test/package.json
I'm not really sure how to test this, because these test cases are only run in the cloud-to-prod auth test job, which doesn't run in this repo, and I'm not sure how to set up the environment for them.
> Update google-auth-library in interop tests

- packages/grpc-js/package.json
> grpc-js: Bump to 0.6.15

- packages/grpc-tools/package.json
There are a couple of bug fixes to publish.
> Update grpc-tools to v1.8.1

- packages/grpc-js/src/server-call.ts
- test/api/error_test.js
Fixes https://github.com/grpc/grpc-node/issues/1236
Not certain the best way to add tests for this change.  Would appreciate assistance as I have only submitted one other (non-runtime) PR for this repo.  Thanks!
> Do not overwrite error 'metadata' if already specified by caller.

- packages/grpc-js/src/call-stream.ts
This mainly adds tracing for sending messages on the http2 stream, and distinguishes between messages (and `end()` calls) sent immediately, and those that are deferred until a stream is attached.
> grpc-js: Improve tracing around sending data

- packages/grpc-js/package.json
There are a few different minor improvements to publish.
> Update grpc-js to 0.6.16

- packages/grpc-native-core/tools/run_tests/artifacts/workflow.sh
- tools/release/kokoro/macos.cfg
Not sure yet what this file needs to contain, but we'll see.
> Adding a build_file field, as this seems necessary

- packages/grpc-js/package.json
I would especially like to publish #1271.
> Bump grpc-js to 0.6.17

- packages/grpc-js/package.json
- packages/grpc-js/src/channel.ts
Also log the error when starting a stream fails.
> Clone metadata going into the metadata filter stack

- packages/grpc-js/src/subchannel-pool.ts
> fix: only unref timers in supported environments

- packages/grpc-js/package.json
> Update grpc-js to 0.7.0

- PACKAGE-COMPARISON.md
> Update PACKAGE-COMPARISON doc to cover features added in grpc-js 0.7

- packages/grpc-js/package.json
To publish #1284, #1285, #1286, and #1287.
> Update grpc-js to 0.7.1

- packages/grpc-js/src/deadline-filter.ts
Basically the same as #1078, but for the deadline filter timer added in #1184.
> grpc-js: Unref deadline filter timer optionally

- packages/grpc-js/package.json
To publish #1302, #1303, and #1308.
> grpc-js: Bump to 0.7.2

- packages/grpc-native-core/tools/run_tests/artifacts/build_one_artifact_macos.sh
- test/kokoro.sh
Based on a suggestion from [this StackOverflow comment](https://stackoverflow.com/questions/60854726/how-can-i-fix-this-bizarre-no-such-file-or-directory-error-when-building-with#comment107671441_60854726), maybe this will fix our Mac issues.
> Use make from homebrew in Mac tests

- packages/proto-loader/package.json
> Bump proto-loader to 0.5.4

- packages/grpc-js/package.json
To publish #1323, #1324, and #1328.
> Bump grpc-js to 0.7.5

- packages/grpc-js/package.json
- packages/grpc-js/src/http_proxy.ts
Maybe this will help some users know **why** grpc failed to connect to the proxy.
> grpc-js: Add more information to proxy errors

- packages/grpc-health-check/package.json
> Bump grpc-health-check to 1.8.0

- packages/grpc-js/src/index.ts
> Export MetadataValue as part of the public API #1383

- packages/grpc-js/package.json
We have accumulated a few patches to publish.
> Bump grpc-js to 1.0.3

- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/load-balancer-round-robin.ts
- packages/grpc-js/src/load-balancer.ts
- packages/grpc-js/src/picker.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolver-uds.ts
- packages/grpc-js/src/resolver.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/subchannel.ts
This is just adding a few objects that will be needed for xDS stuff later, and plumbing them through a few internal APIs.
> grpc-js: Some internal changes in preparation for implementing xDS Global LB

- packages/grpc-js/src/index.ts
> grpc-js: Fix credentials type

- packages/grpc-js/src/load-balancer-weighted-target.ts
- packages/grpc-js/src/load-balancer.ts
- packages/grpc-js/src/load-balancing-config.ts
This is again based heavily on the [corresponding core class](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/weighted_target/weighted_target.cc).
This PR will conflict with #1433. I'll fix it up once that PR is merged.
> grpc-js: Add weighted_target load balancer

- packages/grpc-native-core/index.d.ts
closes https://github.com/grpc/grpc-node/issues/1495 (for `1.24.x`)
> add methodTypes enum

- packages/grpc-js/src/xds-client.ts
Cache updates so that whenever a new watcher is added, it can see existing updates for the name it is watching immediately.
> grpc-js: xDS Client: cache updates to pass them to new watchers

- packages/grpc-js/src/load-balancer-cds.ts
- packages/grpc-js/src/load-balancer-eds.ts
- packages/grpc-js/src/load-balancer.ts
- packages/grpc-js/src/load-balancing-config.ts
- packages/grpc-js/src/xds-client.ts
This is the next step in the xDS implementation. The CDS balancer sits one level above the EDS balancer in the load balancer hierarchy.
> grpc-js: CDS load balancer

- packages/grpc-js/src/load-balancer-eds.ts
- packages/grpc-js/src/load-balancer-lrs.ts
- packages/grpc-js/src/load-balancer.ts
- packages/grpc-js/src/load-balancing-config.ts
- packages/grpc-js/src/xds-client.ts
Add a load balancer class that intercepts pick operations to gather additional statistics to send back to the xDS server.
> grpc-js: Add LrsLoadBalancer class

- packages/grpc-js/package.json
There are a couple of contributions to publish.
> Bump grpc-js to 1.1.6

- packages/grpc-js/scripts/xds.sh
> grpc-js: Install dependencies in xds script

- packages/grpc-js/package.json
The repo is finally in a good state to publish a new minor release.
> grpc-js: Update to 1.2.0

- packages/grpc-tools/package.json
> grpc-tools: Bump version to 1.10.0

- packages/proto-loader/package.json
> proto-loader: bump to 0.5.6

- packages/grpc-js-xds/package.json
I missed this when originally making this package.json
> grpc-js-xds: List the files to publish in package.json

- packages/proto-loader/src/index.ts
- packages/proto-loader/test/descriptor_type_test.ts
- packages/proto-loader/test_protos/rpc.proto.json
**new feature:**
make `@grpc/proto-loader` can parse JSON descriptors in [protobuf.js](https://github.com/protobufjs/protobuf.js#using-json-descriptors)
**code change:**
encapsulated `fromJSON` function
and its test
> protobuf.js JSON descriptor

- packages/grpc-js-xds/package.json
- packages/grpc-js-xds/src/xds-client.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/call-credentials-filter.ts
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/compression-filter.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/subchannel.ts
Because we are getting close to 1.3
> Upmerge from @grpc/grpc-js@1.2.x

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/package.json
Getting ready for the 1.3.0 release.
> grpc-js: Update versions and xDS feature list

- packages/proto-loader/bin/proto-loader-gen-types.ts
- packages/proto-loader/golden-generated/google/longrunning/Operations.ts
- packages/proto-loader/golden-generated/google/showcase/v1beta1/Echo.ts
> Fix auto-generated service definition

- test/api/interop_extra_test.js
- test/api/interop_sanity_test.js
Improves the situation with https://github.com/grpc/grpc-node/issues/1801.
> Increase timeout for tests that timeout under emulator

- packages/grpc-tools/package.json
> grpc-tools: Bump to version 1.11.2

- packages/proto-loader/package.json
> proto-loader: Bump to version 0.6.3

- packages/proto-loader/package.json
> proto-loader: bump to 0.6.4

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js-xds/src/matcher.ts
- packages/grpc-js-xds/src/resolver-xds.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/client.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/logging.ts
- packages/grpc-js/src/resolver-ip.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-resolver.ts
> Upmerge from 1.3.x

- packages/grpc-js-xds/src/xds-client.ts
This is supposed to do the same thing as grpc/grpc#26757.
> grpc-js-xds: notify watchers when NACKing resource updates

- .gitattributes
As described in [this documentation](https://github.com/github/linguist/blob/master/docs/overrides.md)
> Add .gitattributes marking generated code in xDS package

- packages/grpc-js/package.json
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/http_proxy.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/subchannel.ts
I just want to get out ahead of merge conflicts.
> Upmerge from 1.3.x to master

- packages/grpc-js-xds/src/xds-client.ts
> grpc-js-xds: Log loaded bootstrap info in xDS client (master)

- packages/grpc-js-xds/src/xds-client.ts
Same as #1920 and #1921 but for 1.2.x
> grpc-js-xds: Handle all ways control-plane streams can end (1.2.x)

- packages/grpc-js-xds/interop/xds-interop-client.ts
- packages/grpc-js-xds/scripts/xds.sh
- packages/grpc-js-xds/src/xds-bootstrap.ts
- packages/grpc-js-xds/src/xds-client.ts
- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/server.ts
In particular, we need #1920 to also apply to master for tests.
> Merge 1.4.x branch into master

- packages/grpc-js-xds/package.json
This is a follow up to #1956 to change the file list with files from the new submodule and also include files that were not included before.
> grpc-js-xds: Update files list to account for submodule change

- packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/channel-options.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/channelz.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-channelz.ts
Keeping master synchronized with the branch.
> Merge 1.4.x into master

- packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
- packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/subchannel.ts
> Upmerge 1.4.x into master

- packages/grpc-js-xds/scripts/xds.sh
> fix: use xds-test-server-5 as interop server image

- packages/grpc-js/package.json
- packages/grpc-js/src/object-stream.ts
- packages/grpc-js/src/server-call.ts
> grpc-js: Fix compatibility with @types/node 17.0.6

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/package.json
Final preparations for release.
> Update grpc-js and grpc-js-xds to version 1.5.0

- packages/grpc-js/src/channel-credentials.ts
- packages/grpc-js/src/index.ts
This is the implementation of [gRFC L93](https://github.com/grpc/proposal/pull/282).
> grpc-js: Add credentials.createFromSecureContext

- packages/grpc-js/package.json
> grpc-js: Increase version to 1.5.5

- doc/environment_variables.md
- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/README.md
- packages/grpc-js/package.json
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/channel-options.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/load-balancer-child-handler.ts
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/logging.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-local-subchannel-pool.ts
- run-tests.sh
- test/distrib/distrib-test.js
- test/distrib/run-distrib-test.sh
> Merge 1.5.x into master

- packages/grpc-js/src/call-stream.ts
#2072 involves an error that has come up a couple of times before: `ERR_STREAM_WRITE_AFTER_END`, which is output by Node's Writable stream class when `write` is called after `end`. This has come up previously and my approach to addressing it has been focused on adding ordering restrictions to avoid triggering the error in the first place. This change instead insures that if the error does occur, we output it through the standard error output path with a gRPC error code. I choose the default `UNAVAILABLE` to match the synchronous error handling below at what is now line 866, but this particular error is more accurately `INTERNAL` because it is a violation of an API usage sequencing constraint.
> grpc-js: Avoid surfacing errors without gRPC error codes

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/package.json
> Update version to 1.6.0

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js-xds/src/xds-client.ts
- packages/grpc-js/README.md
- packages/grpc-js/package.json
- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/channel-options.ts
- packages/grpc-js/src/resolver-dns.ts
Somehow the xds interop tests are succeeding on master and failing on 1.6.x. This merge will make them identical, which should help narrow down the cause.
> Upmerge 1.6.x into master

- packages/grpc-js/src/subchannel.ts
This adds trace logs for receiving the ping response and hitting the deadline, so there is always a log of the result of the ping. In addition, it adds the timeout to the log of sending the ping, so that the reader knows in what time range to look for the ping result log.
> grpc-js: Add more details to keepalive ping tracing

- packages/grpc-js/test/test-resolver.ts
As requested in https://github.com/grpc/grpc-node/issues/2080#issuecomment-1103024536.
> grpc-js: Add regression tests for repeated DNS requests

- packages/proto-loader/package.json
> proto-loader: Increment version to 0.6.13

- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_url_map.cfg
The script is a copy of https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_xds_url_map_python.sh, with the variables changed.
> Add xDS k8s url_map test script

- packages/grpc-js-xds/scripts/xds_k8s_lb.sh
- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_url_map.cfg
> Backport xDS k8s test scripts to the v1.6.x branch

- packages/grpc-js-xds/scripts/xds_k8s_lb.sh
- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_url_map.cfg
> Backport xDS k8s test scripts to the v1.5.x branch

- packages/grpc-js-xds/scripts/xds_k8s_lb.sh
- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_url_map.cfg
> Backport xDS k8s test scripts to the v1.4.x branch

- packages/grpc-js-xds/scripts/xds_k8s_lb.sh
- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_url_map.cfg
> Backport xDS k8s test scripts to the v1.3.x branch

- packages/grpc-js-xds/scripts/xds_k8s_lb.sh
- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_url_map.cfg
> Backport xDS k8s test scripts to the v1.2.x branch

- packages/grpc-js-xds/src/xds-client.ts
- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/call.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/channelz.ts
- packages/grpc-js/src/client.ts
- packages/grpc-js/src/load-balancer-outlier-detection.ts
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel-pool.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/fixtures/test_service.proto
- packages/grpc-js/test/generated/Response.ts
- packages/grpc-js/test/generated/TestService.ts
- packages/grpc-js/test/test-client.ts
- packages/grpc-js/test/test-resolver.ts
- packages/grpc-js/test/test-server.ts
A variety of fixes have accumulated on the version branch and need to be on master too.
> Merge the v1.6.x branch into master

- packages/grpc-js-xds/interop/Dockerfile
> Backport xDS k8s interop docker image to version branch (1.5.x)

- packages/grpc-js-xds/interop/Dockerfile
> Backport xDS k8s interop docker image to version branch (1.4.x)

- packages/grpc-js-xds/interop/Dockerfile
> Backport xDS k8s interop docker image to version branch (1.2.x)

- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
> Clone submodules in xds k8s url map script (1.6.x)

- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
> Clone submodules in xds k8s url map script (1.5.x)

- packages/grpc-js-xds/scripts/xds_k8s_url_map.sh
> Clone submodules in xds k8s url map script(1.4.x)

- packages/grpc-js/package.json
This is to publish #2168. I meant to include this version increment in that PR but I forgot.
> grpc-js: Update version to 1.6.8

- packages/grpc-js/src/subchannel.ts
This is an attempt to fix #2139. The pattern here is similar to the one that is already in `startCallStream` in this file.
> grpc-js: Handle errors when trying to ping

- packages/grpc-js/package.json
Several patches are ready to be published.
> grpc-js: Update version to 1.6.9

- packages/grpc-js-xds/src/load-balancer-weighted-target.ts
- packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
In order to minimize churn when updating multiple children of an LB policy, we don't propagate any updates from the children until after finishing updating all of them. In both weighted_target and xds_cluster_manager, the current setup already stores the update from each child, and calculates the total state from those stored states. The change here is just to avoid triggering that calculation while sending updates to children.
This also needs to be done for priority, but that looked more complicated.
> grpc-js-xds: delay picker updates while updating children in weighted_target and xds_cluster_manager

- packages/grpc-js-xds/src/load-balancer-priority.ts
I make a few changes here to make the priority policy function similarly to the [core implementation](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/priority/priority.cc):
- Handle the fallback timer fully inside each child object, starting and cancelling it only when the child's state updates.
- Track whether each child has more recently seen a TRANSIENT_FAILURE vs IDLE/READY state update, and change fallback timer behavior accordingly.
- Replace `tryNextPriority` with the (mostly) idempotent `choosePriority`
- Pause update propagation while sending updates to children (similar to what #2200 did for other LB policies)
> grpc-js-xds: Make various fixes to the priority LB policy

- packages/grpc-js-xds/src/load-balancer-priority.ts
This is a simplification of the priority algorithm that matches the changes made to the C core in grpc/grpc#30705. With this change, the behavior of `choosePriority` no longer has any dependency on the state from before the most recent call to `updateAddressList`.
> grpc-js-xds: priority: remove `currentChildFromBeforeUpdate`

- packages/grpc-js/src/load-balancer-outlier-detection.ts
This is the implementation change to address grpc/proposal#322.
> grpc-js: Outlier Detection: fix failure percentage min hosts check

- packages/grpc-js/package.json
- packages/grpc-js/src/call-stream.ts
> grpc-js: Handle errors when decoding status details

- packages/grpc-js/package.json
- packages/grpc-js/src/call-stream.ts
> v1.6.x merge into master, again

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/package.json
See #2075 for a similar recent change.
> grpc-js: Bump to 1.7.0

- packages/grpc-js/test/test-channel-credentials.ts
I thought I found a bug that would prevent this from working, but it actually does work, so this is just a regression test.
> grpc-js: Add test for sending metadata from call creds on channel creds

- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
This is an implementation of the limitation documented [here](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/endpoint/v3/endpoint_components.proto#L164-L168).
> grpc-js-xds: Validate that endpoint weights sum to no more than the 32 bit uint max value per priority

- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
Along with #2240, this implements the rules described in grpc/proposal#332.
> grpc-js-xds: Validate uniqueness of addresses and continuity of priorities in EDS updates

- packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/server.ts
I mainly want to get #2247 into master to fix those test failures on the master branch.
> Merge v1.7.x into master

- packages/grpc-js/package.json
To publish performance improvements from #2249.
> grpc-js: Bump to 1.7.3

- packages/grpc-js/package.json
- packages/grpc-js/src/call-interface.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Channelz.ts
- packages/grpc-js/src/metadata.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
> Merge 1.7.x into master

- packages/grpc-tools/package.json
> grpc-tools: Bump to version 1.12.3

- packages/proto-loader/package.json
> proto-loader: Bump to version 0.7.4

- packages/grpc-js/package.json
To publish #2277, #2305, and #2306.
> grpc-js: Bump to version 1.8.1

- packages/grpc-js/package.json
- packages/grpc-js/src/resolving-call.ts
> grpc-js: Clear deadline timer when call ends

- packages/grpc-tools/package.json
> grpc-tools: Bump version to 1.12.4

- packages/grpc-js/package.json
- packages/grpc-js/src/call-credentials-filter.ts
- packages/grpc-js/src/call-credentials.ts
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/client-interceptors.ts
- packages/grpc-js/src/error.ts
- packages/grpc-js/src/metadata.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
- packages/proto-loader/package.json
The same as #2354.
Edit: I also needed to backport the proto-loader fixes from #2196 to get this to build.
> grpc-js: Update to newest typescript compiler (1.5.x)

- packages/grpc-js/package.json
- packages/grpc-js/src/call-credentials-filter.ts
- packages/grpc-js/src/call-credentials.ts
- packages/grpc-js/src/call-stream.ts
- packages/grpc-js/src/client-interceptors.ts
- packages/grpc-js/src/error.ts
- packages/grpc-js/src/metadata.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
Essentially the same as #2353, but for 1.6.x.
> grpc-js: Update to newest typescript compiler (1.6.x)

- packages/proto-loader/package.json
> proto-loader: Bump version to 0.7.5

- packages/grpc-js/src/server-call.ts
> grpc-js: add await/async on method that return promise (v1.8.x)

- packages/proto-loader/package.json
> proto-loader: Bump to 0.7.6

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: experiment with qps affect on circuit_breaking

- packages/grpc-js/package.json
> grpc-js: Bump version to 1.8.14

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: experiment with qps affect on circuit_breaking (1.5.x)

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: experiment with qps affect on circuit_breaking (1.8.x)

- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-global-subchannel-pool.ts
> grpc-js: Fix a couple of errors from a previous PR

- packages/grpc-js-xds/package.json
- packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts
- packages/grpc-js-xds/test/test-nack.ts
- packages/grpc-js/package.json
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/subchannel.ts
- packages/grpc-js/test/test-global-subchannel-pool.ts
I mainly need the changes from #2433 to avoid conflicts when working on federation.
> Merge v1.8.x into master

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: Increase old driver QPS to 75 (1.7.x)

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: Increase old driver QPS to 75 (1.6.x)

- packages/grpc-js-xds/scripts/xds.sh
> PSM Interop: Increase old driver QPS to 75 (1.5.x)

- packages/grpc-js/README.md
> grpc-js: Update documentation of compression behavior in README

- packages/proto-loader/package.json
> Fixes security issue by upgrading `protobufjs`

- packages/proto-loader/package.json
> proto-loader: Increment version to 0.7.8

- packages/grpc-js/package.json
- packages/grpc-js/src/channel-credentials.ts
- packages/grpc-js/src/client-interceptors.ts
- packages/grpc-js/src/client.ts
- packages/grpc-js/src/compression-filter.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ChannelConnectivityState.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ChannelTraceEvent.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/internal-channel.ts
- packages/grpc-js/src/load-balancer-outlier-detection.ts
- packages/grpc-js/src/load-balancer.ts
- packages/grpc-js/src/load-balancing-call.ts
- packages/grpc-js/src/max-message-size-filter.ts
- packages/grpc-js/src/metadata.ts
- packages/grpc-js/src/object-stream.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolver-ip.ts
- packages/grpc-js/src/resolving-call.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel-call.ts
- packages/grpc-js/src/transport.ts
- packages/grpc-js/test/test-channel-credentials.ts
- packages/grpc-js/test/test-channelz.ts
- packages/grpc-js/test/test-deadline.ts
- packages/grpc-js/test/test-outlier-detection.ts
- packages/grpc-js/test/test-server.ts
- packages/grpc-js/tsconfig.json
I had to add one comment to get eslint to ignore the `@ts-ignore` comment I added in #2503. In the future, it will be better to just change that code to not need that comment.
> Merge v1.18.x into master (with formatting fixes)

- packages/proto-loader/package.json
This will allow us to test whether #2504 works before properly publishing it.
> proto-loader: Increment version to prerelease version

- packages/grpc-js/package.json
- packages/grpc-js/src/server.ts
- packages/grpc-js/test/test-server.ts
> grpc-js: Fix propagation of UNIMPLEMENTED error messages

- packages/grpc-js/package.json
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/transport.ts
- packages/grpc-js/test/test-server.ts
> Merge 1.8.x into master

- packages/grpc-js/src/server-call.ts
> grpc-js: Cancel deadline timer on server when call is cancelled

- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/internal-channel.ts
- packages/grpc-js/src/load-balancer-outlier-detection.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolving-call.ts
- packages/grpc-js/src/retrying-call.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel-pool.ts
- packages/grpc-js/src/transport.ts
> grpc-js: Switch Timer type to Timeout (1.9.x)

- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/channel.ts
- packages/grpc-js/src/deadline-filter.ts
- packages/grpc-js/src/load-balancer-outlier-detection.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/subchannel-pool.ts
- packages/grpc-js/src/subchannel.ts
> grpc-js: Switch Timer type to Timeout (1.7.x)

- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/internal-channel.ts
- packages/grpc-js/src/load-balancer-outlier-detection.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolving-call.ts
- packages/grpc-js/src/retrying-call.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/subchannel-pool.ts
- packages/grpc-js/src/transport.ts
> grpc-js: Switch Timer type to Timeout (1.8.x)

- packages/grpc-js/package.json
This addresses https://github.com/grpc/grpc-node/issues/2495#issuecomment-1680910894.
> grpc-js: Update dependency on @grpc/proto-loader

- packages/grpc-reflection/package.json
> grpc-reflection: Increment version to 1.0.1

- packages/grpc-health-check/package.json
> grpc-health-check: Bump version to 2.0.1

- packages/grpc-js/src/server-credentials.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/test/test-server.ts
This change is in preparation for the file watcher plugin credentials defined in [gRFC A29](https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md). All of these APIs are officially non-public, so this doesn't lock anything in.
The test verifies that credentials can update a watcher with `null` (as an error) to make the server start rejecting connections, and then return a non-`null` value to make it start accepting them again.
> grpc-js: Expand ServerCredentials API to support watchers

- packages/grpc-js/src/backoff-timeout.ts
- packages/grpc-js/src/index.ts
- packages/grpc-js/src/internal-channel.ts
- packages/grpc-js/src/load-balancer-pick-first.ts
- packages/grpc-js/src/load-balancer-round-robin.ts
- packages/grpc-js/src/load-balancing-call.ts
- packages/grpc-js/src/logging.ts
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/resolving-load-balancer.ts
- packages/grpc-js/src/server-call.ts
- packages/grpc-js/src/server-interceptors.ts
- packages/grpc-js/src/server.ts
- packages/grpc-js/src/service-config.ts
- packages/grpc-js/src/transport.ts
- packages/grpc-js/test/common.ts
- packages/grpc-js/test/test-confg-parsing.ts
- packages/grpc-js/test/test-pick-first.ts
- packages/grpc-js/test/test-server-interceptors.ts
- packages/grpc-js/test/test-server.ts
I have forgotten to do this for a little while. This will help with reviewing other changes that also run the formatter.
> grpc-js: Run code formatter, fix one lint error

- packages/grpc-js/package.json
To publish #2677, #2680, and #2683.
> grpc-js: Bump to 1.10.2

- packages/proto-loader/package.json
> proto-loader: Bump version to 0.7.11

- packages/grpc-js/package.json
- packages/grpc-js/src/resolver-uds.ts
- packages/grpc-js/test/common.ts
- packages/grpc-js/test/test-idle-timer.ts
- packages/grpc-js/test/test-pick-first.ts
- packages/grpc-js/test/test-server-interceptors.ts
> grpc-js: Fix UDS channels not reconnecting after going idle

- packages/grpc-js/package.json
To release several patch changes.
> grpc-js: Bump to 1.10.10

- test/kokoro/xds_k8s_lb.cfg
Increased the timeout from 3hrs to 6hrs.
> xds_k8s_lb test: Increase the timeout

- packages/grpc-js/src/channel-options.ts
- packages/grpc-js/src/internal-channel.ts
- packages/grpc-js/src/retrying-call.ts
- packages/grpc-js/test/test-retry.ts
> grpc-js: Add a channel option to configure retry attempt limits

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/README.md
- packages/grpc-js/package.json
- packages/grpc-js/src/resolver-dns.ts
- packages/grpc-js/src/server-call.ts
fix: https://github.com/grpc/grpc-node/issues/2798
> support node v14.16 again

- packages/grpc-js/package.json
> grpc-js: Bump to 1.11.1

- packages/grpc-js/package.json
> grpc-js: Bump to 1.11.2

- test/kokoro/psm-dualstack.cfg
This is the same as the other configs, with just the test suite value changed.
> Add dualstack kokoro test job config

- packages/grpc-tools/package.json
> grpc-tools: Bump to version 1.13.0

- packages/grpc-js-xds/src/load-balancer-ring-hash.ts
Changes in accordance with https://github.com/grpc/proposal/pull/475. Now, ring_hash will proactively connect when the aggregate state is CONNECTING or TRANSIENT_FAILURE, on both resolver updates and leaf LB policy state updates, independent of the new leaf LB policy state.
> grpc-js-xds: ring_hash: proactively connect in more cases

- packages/grpc-js/src/generated/channelz.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Address.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Channel.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ChannelData.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ChannelTrace.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ChannelTraceEvent.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Channelz.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetChannelResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetServerResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetServerSocketsResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetServersResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetSocketResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetSubchannelResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/GetTopChannelsResponse.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Security.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Server.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/ServerData.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Socket.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/SocketData.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/SocketOption.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/SocketOptionLinger.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/SocketOptionTimeout.ts
- packages/grpc-js/src/generated/grpc/channelz/v1/Subchannel.ts
This includes changes from #2911, plus previous changes.
> grpc-js: Update generated code with generator changes

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js/package.json
Also update xDS feature list accordingly.
> grpc-js: Update to 1.13.0

- packages/grpc-js-xds/README.md
- packages/grpc-js-xds/package.json
- packages/grpc-js-xds/src/load-balancer-ring-hash.ts
- packages/grpc-js/package.json
> Merge 1.13.x into master

- packages/grpc-js/src/channel-credentials.ts
- packages/grpc-js/test/test-channel-credentials.ts
> grpc-js: Don't check authorized when rejectUnauthorized is false

- packages/grpc-js/package.json
> grpc-js: Bump to 1.13.1

- packages/grpc-js-xds/src/http-filter.ts
- packages/grpc-js-xds/src/http-filter/fault-injection-filter.ts
- packages/grpc-js-xds/src/http-filter/router-filter.ts
- packages/grpc-js-xds/src/resolver-xds.ts
- packages/grpc-js-xds/src/server.ts
- packages/grpc-js-xds/src/xds-resource-type/listener-resource-type.ts
> grpc-js-xds: Add support for server http filters

- packages/grpc-js/package.json
> grpc-js: Bump to 1.13.3

- packages/grpc-js/src/load-balancer-round-robin.ts
> grpc-js: round_robin: Start connecting to endpoints from a random index

- packages/grpc-js/test/test-resolver.ts
- packages/grpc-js/test/test-server-interceptors.ts
- packages/proto-loader/golden-generated/echo.ts
- run-tests.bat
- run-tests.sh
This has not been updated in a long time.
> Test with newer Node versions

- packages/grpc-js/src/compression-filter.ts
Not sure what caused this error to start happening.
> grpc-js: Declare buffer type to avoid build error

- packages/grpc-health-check/package.json
> grpc-health-check: Bump version to 2.1.0
