grpc/grpc-node

run-tests.sh

Fixes  ```grpc-node/run-tests.sh: 25: [: x: unexpected operator```

Fix run-tests.sh script

---

packages/grpc-native-core/src/client.js
test/api/surface_test.js

Add original name aliases for generated client methods

---

merge_kokoro_logs.js
package.json
run-tests.sh
test/kokoro/linux.cfg
test/kokoro/macos.cfg

Now Kokoro should get just one log per version to fix the issue mentioned in [this comment](https://github.com/grpc/grpc-node/pull/33#issuecomment-331239556)

Added script to merge jenkins logs per node version

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/templates/binding.gyp.template

Disable warning in recent GCC versions that hits BoringSSL

---

packages/grpc-native-core/ext/completion_queue.cc
packages/grpc-native-core/ext/completion_queue.h
packages/grpc-native-core/ext/node_grpc.cc
packages/grpc-native-core/src/client.js

This fixes a bug that was reported internally with processes that are idle for a long time

Add forced completion queue poll to ensure that waitForReady uses current connectivity state

---

gulpfile.js
package.json
packages/grpc-native-core/gulpfile.js
packages/grpc-native-core/jsdoc_conf.json
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template
test/gulpfile.js
test/package.json

This is the convention I'm following for dependencies:
- For the packages, "dependencies" have runtime dependencies, and "devDependencies" have test dependencies.
- For the root package, "devDependencies" have scripting dependencies (i.e. stuff that is used in gulpfiles).
- For the test package, "dependencies" contain runtime test dependencies.
This PR doesn't entirely complete that. The istambul dependency is still in the native package because of SBoudrias/gulp-istanbul#118.

Move dependencies around, add gulp target for document generation

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/common.js
packages/grpc-native-core/src/constants.js
packages/grpc-native-core/src/credentials.js
packages/grpc-native-core/src/metadata.js
packages/grpc-native-core/src/server.js

I've come across some typos and missing links in the documentation. They are fixed in this PR.

Fix some typos and type links in the jsDocs

---

package.json
packages/grpc-native-core/index.d.ts
packages/grpc-native-core/package.json

Following @murgatroid99's request I've moved the PR https://github.com/grpc/grpc/pull/12755 to this repo instead.
**From the original PR:**
This is a follow up of https://github.com/grpc/grpc/pull/11020. I've accidentally deleted the old gRPC fork I had as I had totally forgotten this PR.
This is a remake with all the latest API changes and the comments from the former PR added.
Further more, I've created a test repo to verify that the type comply with the documented API. It is located here for now: https://github.com/lunarway/grpc-ts-test
If it can fit into the structure of the repo, we could incorporate it to make sure the type and tests stay up to date? Let me know if there is anything I can do in that case.
From the initial PR:
> This PR closes https://github.com/grpc/grpc/issues/8233 …

Add TypeScript typings to gRPC native core package

---

run-tests.bat
run-tests.sh

This will hopefully fix the Windows test failures we've been seeing on some PRs.

Upgrade npm versions for every version of node in test scripts

---

packages/grpc-health-check/package.json
packages/grpc-native-core/package.json
packages/grpc-tools/package.json

This is a prerequisite for publishing prerelease packages.

Update grpc/grpc submodule and package versions to 1.7.0-pre1

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/templates/binding.gyp.template
packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.bat
packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.sh
packages/grpc-native-core/tools/run_tests/artifacts/build_package_node.sh

This copies the Node artifact build scripts pretty much verbatim to this repo, except that it adds 1.7.0 to the list of electron versions to build for.

Add artifact build scripts for native core

---

gulpfile.js
package.json
packages/grpc-health-check/gulpfile.js
packages/grpc-js-core/gulpfile.js
packages/grpc-js/gulpfile.js
packages/grpc-native-core/gulpfile.js
packages/grpc-native/gulpfile.js
packages/grpc-surface/gulpfile.js
test/gulpfile.js
util.js

This change removes `npm link` calls in favor of single-link-chain symlinks between modules.

Manually link packages

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template
packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.bat
packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.sh

Update to 1.7.1, add Node 9 support, fix generated file permissions

---

packages/grpc-native-core/index.d.ts
packages/grpc-native-core/index.js

The docs and typings had a duplicate method on ServerCredentials, both called `createInsecure`. I've updated them to have the correct name (createSsl).

Fixed name of ServerCredentials.createSsl in native docs & types.

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

The latest version of node-pre-gyp supports using `libc` as a variable for binary names, making it possible to differentiate between glibc and musl of alpine linux.
Fixes #81.

Build different binaries for different libc’s (a.k.a. support alpine linux)

---

packages/grpc-native-core/ext/completion_queue.cc

After adding the `CompletionQueueForcePoll` method to make `waitForReady` work properly, this assertion is no longer correct.
This fixes #91.

Remove now-incorrect assertion in completion queue wrapper

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/package.json
packages/grpc-native-core/test/channel_test.js

This points the submodule at grpc/grpc#13433 in order to test those changes against this repo. The submodule will have to be updated again once that PR is merged.

Update the submodule and unskip previously failing test

---

packages/grpc-native-core/src/grpc_extension.js

We've gotten multiple reports where the extension failed to load, and this will help us diagnose the problem in more cases.

Add more helpful error message for failure to load extension

---

packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/metadata.ts

`channel.ts` - We need to append the protocol to the incoming address parameter before it's turned into a `URL` (instead of after) - otherwise the hostname will be parsed as the protocol.
`call-credentials.ts`/`client.ts` - Google TS style guide prohibits use of `Object` types
`call-stream.ts` - `headers` doesn't have `Object` prototype functions, so `headers.hasOwnProperty` fails. Also, destroying an http2 stream twice causes problems
`metadata.ts` - compiler complains about `values` being undefined, also I added a note on Node 8.8 serializing headers incorrectly

grpc-js-core: compiler error and http2-facing fixes

---

packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/deadline-filter.ts

The `ClientHttp2Session` keeps the process alive after all requests are completed; this change works around that.
I think client stream calls are supposed to emit the `'status'` event, so I added it here.
This change promisifies `Http2Channel#connect` and makes small changes to credentials-related files to pass the `api/credentials_test.js` test suite.
This is a set of changes intended to allow the js client to pass the interop test suite.

grpc-js-core: more changes

---

packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/metadata-status-filter.ts
packages/grpc-js-core/src/metadata.ts

For unary response calls, `'status'` might be emitted too soon, and the user won't see any data in their callback. This change ensures that if `'status` comes before `'end'`, that `'end'` will invoke the user callback instead.
We should treat headers with `END_STREAM` flags as if they were trailers. In addition, I've added code to prevent race conditions for emitted StatusObject instances: if a header or trailer (in that order of priority) is still being put through the filter stack, wait to give those execution threads an opportunity to end the call first, before allowing the call to be ended synchronously in a `streamClosed` event.

grpc-js-core: prevent callback before 'end' event and handle eos headers as trailers

---

packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/events.ts
packages/grpc-js-core/src/object-stream.ts

This is a non-logical change (there are slight re-orderings of statements that should have no visible effect) to reduce the boilerplate `EventEmitter` type overloads.

grpc-js-core: merge all eventemitter overloads

---

packages/grpc-native-core/src/client.js
test/api/credentials_test.js
test/api/surface_test.js
test/interop/interop_client.js

We frequently get questions that reference status errors, but they almost never realize that the `code` is important or know what it means. This adds the status code number and name to the error message.

Add error code name to status error messages

---

packages/grpc-native-core/package.json
packages/grpc-native-core/src/client.js
packages/grpc-native-core/templates/package.json.template

This fixes #133 and #161. The error messages will be a little less helpful right now, but we can improve that later and I think it's good to get the fix out now.
The dependency on argue.js was actually removed a while ago in grpc/grpc#11707, but for some reason that change never made it out of the v1.4.x branch. So this is also correcting that error.

Replace argue.js usage with inline argument checking

---

packages/grpc-native-core/src/grpc_extension.js

A couple of times, e.g. in grpc/grpc#6435, people have reported errors indicating that the binary module directory doesn't exist at all, which isn't communicated well. This fixes that.

Improve module load error message when the directory does not exist

---

packages/grpc-native-core/index.d.ts

Fix usage of Protobuf.js Message type in TS file

---

packages/grpc-native-core/src/client.js
test/api/surface_test.js

Fix handling of undefined values for optional call arguments

---

packages/grpc-js-core/package.json
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/constants.ts
packages/grpc-js-core/src/deadline-filter.ts
packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/test/test-call-stream.ts

* Adds a few docs for classes
* Removes `ServiceErrorImpl`, as we can accomplish the same with the `Error` constructor
* ~~Adds support for cancellation propagation~~
* If an incoming metadata value is a single string, split it on the comma delimiter to get multiple values. This appears to be the behavior of the native implementation, as not doing this will fail tests.
* Self-explanatory
* Replaces `shutdown` with `close` (this was changed in Node 9.4, and I believe will be backported to Node 8 as well if not already)
* Self-explanatory
* Timers set to expire actions are now cleared when the actions are completed first
* Accounts for another change that was made in Node 9.4

grpc-js-core: fixes and update to use node 9.4 http2 api

---

install-nvm-windows.ps1

https://githubengineering.com/crypto-removal-notice/ broke the windows test. Forcing Powershell to update to TLS/1.2.

Update Windows test to force using TLS/1.2

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/common.js

@kjin This is the implementation in the existing native library of the function to load the "package definition" from the protobuf library. As you can see, it calls `makeClientConstructor`, which is the other function that is not currently implemented in the pure JavaScript implementation.
The result type for this looks something like
```typescript
type GrpcPackage = {
[name: string]: GrpcPackage | typeof Client
}
```

Add package definition loader function to native package

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/src/common.js
packages/grpc-native-core/src/constants.js
packages/grpc-native-core/test/client_interceptors_test.js
packages/grpc-native-core/test/echo_service.proto

A NodeJS implementation of client-side interceptors, as described in
the proposal: https://github.com/grpc/proposal/pull/14

Implement client interceptors for grpc-native-core

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/templates/binding.gyp.template

This gets this repo working with grpc/grpc#14400. In theory, the correct way to do this would be to use the per-target default compilation flags specified in the `build.yaml` file, but that section is too heavily tied to the Makefile build system to use here in general.

Add macro definition to gyp file

---

packages/grpc-protobufjs/package.json

Just adding the d.ts file to the package exports so we can access types from outside (and lowering the version number)
@murgatroid99 Can you publish a placeholder for this package?

grpc-protobufjs: add d.ts to package

---

packages/grpc-native-core/src/client.js

checking for functions simply by instanceof would render library usesless in vm or REPL contexts. because if client is created in another V8 context, typeof would still return "function" but instanceof Function would fail and return false for functions and arrow functions. thus it would be impossible to create client before starting a REPL context.
Mainly I ran into problem using [grpcc](https://github.com/njpatel/grpcc) with following error:
```
Error: Argument mismatch in makeClientStreamRequest
at ServiceClient.Client.makeClientStreamRequest (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client.js:640:11)
at apply (/usr/local/lib/node_modules/grpcc/node_modules/lodash/lodash.js:470:17)
at ServiceClient.wrapper [as add] …
```

stronger checking for functions in client.js

---

packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/make-client.ts

This change adds `makeClientConstructor` & `loadPackageDefinition` to grpc-js-core, and makes its interface a subset of `grpc`.

grpc-js: add makeClientConstructor and loadPackageDefinition

---

packages/grpc-native-core/src/client_interceptors.js

This is a follow-up to #59, addressing the performance penalties of the code I wrote to enforce a certain order in batch operations, as discussed here: https://github.com/grpc/grpc-node/pull/59#issuecomment-369114921
This replaces the worst-performing lodash and standard library calls. In micro-benchmarks, _startBatchIfReady runs in about half the time after these changes are applied.

Improve performance of batch operation serializer

---

packages/grpc-native-core/src/server.js

Had a situation where a test GRPC client was sending to a RPC method that did not yet exist on our GRPC server, resulting in an unclear error from the GRPC server:
```
unhandledRejection { Error: 12 UNIMPLEMENTED: 
at new createStatusError (/Users/t.gravity/xxx/node_modules/grpc/src/client.js:64:15)
at /Users/t.gravity/xxx/node_modules/grpc/src/client.js:583:15
code: 12,
metadata: Metadata { _internal_repr: {} },
details: '' }
```
It was a bit difficult to debug as the testing client was sending multiple events - this PR adds some clarification to which RPC method was being called that was not implemented.
With the update, we would now get clarification:
```
unhandledRejection { Error: 12 UNIMPLEMENTED: RPC method not implemented: /test.TestService/Metrics
at new createStatusError …
```

Add UNIMPLEMENTED details when an RPC method is not impl.

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

node-pre-gyp has had a few improvements since 0.6.x, and we won't get them automatically.

Update to newest version of node-pre-gyp

---

packages/grpc-js-core/src/channel.ts
test/any_grpc.js

The case where the stream status is non-null (i.e. the call has already completed on the client side). is handled in `stream.attachHttp2Stream`. So the channel should call that in either case.
The way this change is written right now, it also means that the channel will keep trying to connect even if the call is cancelled. I think that's fine.

Don't handle already-finished call in channel

---

packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/test/test-call-credentials.ts
packages/grpc-js-core/test/test-call-stream.ts

This PR:
1. Fixes a unit test for CallStream to reflect event name changes in a previous PR
2. Makes Call/ChannelCredentials generic on options type (defaults to {})
3. Implements `createFromGoogleCredential`
4. Documents public API

grpc-js: add google credentials implementation

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Starting probably with https://github.com/mapbox/node-pre-gyp/pull/299, the contents of the tarballs are bloated. Rolling back to 0.7.0.

Downgrading node-pre-gyp.

---

packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/test/test-call-stream.ts

I also added the `host` call option, because that impacts the same code paths.

Pure JS: Pass real service_url to call credentials

---

packages/grpc-tools/bin/protoc_plugin.js

Hi guys,
I ran into this issue where stdout maxBuffer is too small on a large proto codebase. This fixes the issue, 1MB is fair but I can adjust it per your liking.
Also, was not sure if master is the good branch, let me know and I'll re-submit

Added a 100MB maxBuffer since the default 200kb is too small

---

packages/grpc-native-core/ext/channel_credentials.cc
packages/grpc-native-core/ext/server.cc
packages/grpc-native-core/ext/server.h
packages/grpc-native-core/ext/server_credentials.cc
packages/grpc-native-core/ext/util.h
packages/grpc-native-core/test/server_test.js

This includes a few fixes:
- Ensure that client and server credentials construction arguments are null-terminated.
- Ensure that the callback for `Server#tryShutdown` is always called asynchronously.
- Ensure that the server doesn't get garbage collected while it is running, and remove server destructor code the server down.

Fix object lifetime and memory management problems in server code

---

packages/grpc-native-core/ext/call.cc
packages/grpc-native-core/ext/call.h
packages/grpc-native-core/ext/call_credentials.cc
packages/grpc-native-core/ext/call_credentials.h
packages/grpc-native-core/ext/node_grpc.cc
packages/grpc-native-core/package.json

WIP, but opening early to get early feedback, and to kick off the CI. I intend to revert the `-Wno-deprecated-declarations` removal before this lands.
Starting with Nan 2.9.x certain Nan::Callback::Call APIs are
deprecated. Instead there are mechanisms in place that allow native
modules to preserve async context across async calls.

fix: avoid using deprecated Nan APIs

---

packages/grpc-native-core/index.js

Updates incorrect option name in error msg from 'protobufjs_version' to 'protobufjsVersion'.

Update error msg for Protobuf.js detection options

---

test/client-libraries-integration/.gitignore
test/client-libraries-integration/init.sh
test/client-libraries-integration/package.json
test/client-libraries-integration/repositories.json
test/client-libraries-integration/use-grpc-js.js

This PR changes `use-grpc-js.js` to monkeypatch google-gax and @google-cloud/common-grpc to meaningfully use functions exported by `@grpc-js` and `@grpc/proto-loader`. The eventual goal is that the contents of these monkeypatches are directly merged into the codebases themselves.

client lib integration: monkeypatches for google-gax & @google-cloud/common-grpc

---

packages/grpc-protobufjs/src/index.ts
test/client-libraries-integration/use-grpc-js.js

This PR contains changes that help client libraries pass when using methods on the new gRPC protobuf package.
- ~~The move of `_.camelCase` seemed appropriate as it matches what I see here: https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/protobuf_js_6_common.js#L106-L121~~
- I've updated the monkeypatch implementations of methods accessing `grpc.load[Object]` to have more thorough conversion options. `oneofs: true` in particular seemed to allow Datastore tests to pass.

client library integration: adjust options

---

packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts

This PR makes a change so that only one `'connect'` handler is registered when `Http2Channel#connect()` is called. This prevents Node from warning that there might be an EventEmitter leak because too many listeners are added on the `'connect'` event. (This was observed during Firestore client library testing.)
To accomplish this, a class member `connecting` Promise is cached and returned when `connect()` is called more than once.
In addition to the above, I added a rejection condition for `connect()` for when the channel shuts down. This hadn't been causing problems before but might help in the future.
Also, I've reversed the order in which `Call` events are emitted; `'status'` events are now always emitted after `'error'` events. The PubSub client library appears to depend on this …

grpc-js-core: only listen for channel connect event once

---

packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/deadline-filter.ts
packages/grpc-js-core/src/events.ts
packages/grpc-js-core/src/filter-stack.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/src/metadata-status-filter.ts
packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/src/object-stream.ts
packages/grpc-js-core/test/common.ts
packages/grpc-js-core/test/test-call-credentials.ts
packages/grpc-js-core/test/test-call-stream.ts
packages/grpc-js-core/test/test-channel-credentials.ts

This is using the default gts linting and formatting rules. There are a couple of substantial changes in here: `CallCredentials` and `ChannelCredentials` are now abstract classes instead of interfaces extended by namespaces, because the linter doesn't like namespaces, and semantically they have static methods, which belong on classes.

Fix lint errors and formatting

---

run-tests.bat

We already don't do this on other platforms, and it looks like the newest version of npm doesn't work on Node 4 (see #295 test failures)

Don't upgrade npm in Windows tests

---

packages/grpc-protobufjs/package.json

Backport #278 to v1.11.x because we want to publish at least the first version from that branch

Update protobufjs version

---

packages/grpc-protobufjs/README.md
packages/grpc-protobufjs/src/index.ts
test/interop/interop_client.js
test/interop/interop_server.js

This follows the change to the proposal document in grpc/proposal#80. When we upmerge into master we will also have to make this change to the performance test scripts.

Change 'include' to 'includeDirs' in proto-loader package

---

packages/grpc-native-core/index.d.ts

The issue with `loadPackageDefinition` was pointed out in #189.

Add loadPackageDefinition and interceptor APIs to .d.ts file

---

packages/grpc-native-core/index.d.ts

This was causing compilation errors with Node.js 10 in nodejs-common-grpc.  
cc @alexander-fenster

fix: use capital `F` for `Function` when used as a type

---

test/api/interop_helper/server.js
test/api/interop_sanity_test.js

The main interop suite was catching errors we weren't seeing in our unit tests because it runs a separate client process per test case, and waits for that client process to end while leaving the server running. This change emulates that in the "interop sanity test", which runs in our unit test suite.

Interop sanity tests: run clients and server in different processes

---

packages/grpc-health-check/package.json
packages/grpc-js-core/package.json
packages/grpc-native-core/package.json

This should resolve warnings related to https://nodesecurity.io/advisories/577
Let me know if it shouldn't be updated in all of these places.

Update lodash version to ^4.17.5 (#330)

---

gulpfile.ts
package.json
packages/grpc-js-core/src/channel.ts
packages/grpc-protobufjs/package.json
run-tests.sh
test/api/interop_sanity_test.js
test/gulpfile.js
test/interop/interop_client.js

This also has the test script run the tests in `test/api`, including the interop sanity test.

Add coverage reporting for JavaScript and TypeScript files

---

gulpfile.ts
package.json
packages/grpc-js-core/src/channel.ts
packages/grpc-protobufjs/package.json
run-tests.sh
test/api/interop_sanity_test.js
test/gulpfile.js
test/interop/interop_client.js

Reverts grpc/grpc-node#332
Looks like the PR has broken grpc/grpc tests on master.
https://source.cloud.google.com/results/invocations/707c0572-1a9c-495e-aabe-81a92504fd21/targets/github%2Fgrpc/tests
```
gsutil cp gs://grpc-testing-secrets/coveralls_credentials/grpc-node.rc /tmp
./run-tests.sh: 48: ./run-tests.sh: gsutil: not found
```

Revert "Add coverage reporting for JavaScript and TypeScript files"

---

packages/grpc-native-core/gulpfile.js

Our fleet of macos is a bit less powerful than the rest, so we
regularly flake tests there due to this timeout.

Increasing mocha timeout to 5s up from 2s.

---

packages/grpc-js-core/gulpfile.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/compression-filter.ts
packages/grpc-js-core/src/filter-stack.ts
packages/grpc-js-core/src/filter.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/test/test-call-stream.ts
packages/grpc-js-core/tsconfig.json
test/gulpfile.js

This passes all of the existing tests, but I haven't added new ones. This mirrors the existing library, which also doesn't have substantial compression test coverage. In a future PR I will add the applicable compression interop tests.

Add compression handling to grpc-js

---

packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/client_interceptors.js

This moves all of the interceptor resolution logic to the call time to avoid needing to do method name lookups. This should fix #363. I also ended up deleting a couple of helper functions in `client_interceptors.js` that were only used for the previous iteration of this functionality. We could probably also remove `Client.prototype.$method_names`, but it's used in one of the tests and I didn't feel like trying to figure out how to change it.

Fix generic client interceptor resolution

---

packages/grpc-native-core/index.js

This doesn't actually change any functionality; it just adds a warning that appears once per process when someone uses `grpc.load`.

Add deprecation notice to grpc.load

---

packages/grpc-native-core/index.d.ts

Fixes #176 
@respinha-ribeiro FYI... Please comment on #176 on why this didn't work for you earlier. (As far as can tell `Message` is non-generic.)

Make Protobuf.js Message type non-generic

---

packages/grpc-native-core/index.d.ts

Allow custom options as a means of passing data per call to client interceptors
Resolves https://github.com/grpc/grpc-node/issues/433

grpc-native-core: Update CallOptions type to allow custom options (#433)

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/ext/call.cc
packages/grpc-native-core/ext/call.h
packages/grpc-native-core/ext/channel.cc
packages/grpc-native-core/ext/channel.h
packages/grpc-native-core/index.d.ts
packages/grpc-native-core/index.js
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/src/constants.js
packages/grpc-native-core/templates/binding.gyp.template
packages/grpc-native-core/test/call_test.js
packages/grpc-native-core/test/channel_test.js
packages/grpc-native-core/test/end_to_end_test.js

This is the implementation of [gRFC proposal L32](https://github.com/grpc/proposal/blob/master/L32-node-channel-API.md), and should fully resolve #386. I only have one test so far because I'm not sure what other tests I can usefully add for this API.

Add Channel class and Client channel override options to public API

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Hopefully this should fix grpc/grpc#16164, at least for 1.14. We can backport if the fix works

Don't refer to node-pre-gyp with a relative path

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/package.json

I want to publish the script changes in a new prerelease, plus there are some core changes that we'll want to get into the final release anyway.

Bump grpc to 1.14.0-pre2

---

packages/grpc-native-core/ext/channel_credentials.cc
packages/grpc-native-core/index.d.ts
packages/grpc-native-core/package.json
packages/grpc-native-core/src/credentials.js
packages/grpc-native-core/templates/package.json.template
packages/grpc-native-core/test/credentials_test.js

Core [PR 15274](https://github.com/grpc/grpc/pull/15274) added an option to provide a callback during peer certificate verification in order to perform additional validation. This PR exposes that option in node as a "checkServerIdentity" function that has the same semantics as the option of the same name available in the [node TLS library](https://nodejs.org/api/tls.html#tls_tls_checkserveridentity_host_cert) (except that it does not replace regular hostname; it is in addition to it).
Example usage:
```
grpc.credentials.createSsl(
fs.readFileSync("truststore.pem"),
fs.readFileSync("client.pem.key"),
fs.readFileSync("clent.pem.crt"),
{
"checkServerIdentity": function(host, cert) {
if (fingerprint(cert) !== expectedFingerprint) {
throw "Invalid server certificate presented";
}
}
});
```

Add checkServerIdentity callback

---

test/performance/benchmark_client.js
test/performance/benchmark_server.js
test/performance/worker.js

This fixes both the incorrect `include` argument and the proto paths that changed at some point.

Fix benchmark proto loading

---

PACKAGE-COMPARISON.md
README.md

Make sure to look at the rich diff. It looks a lot better than the markdown text does.
I took the feature list directly from our internal document (and omitted a couple of features that neither library has). I also guessed at a couple of `grpc` features that I think are implemented in the C Core, but I'm not entirely sure. The new link in the README links to the new document.
I'm unsure about the wording of the "Binary Addon" line. I think the green and red makes it look like a positive on the `grpc` side, which is not what we want to communicate, but I can't think of a good way to word it to switch them. "Just an npm package without a binary addon" seems convoluted and contrived.

Package comparison documentation

---

packages/grpc-health-check/gulpfile.js

The link that we still have in the health check directory that still points to the main grpc directory is the only think that causes problems with multiple runs of `gulp setup`. So, we delete it before touching the rest of that directory.

Make gulp setup idempotent

---

packages/grpc-native-core/ext/channel.cc
packages/grpc-native-core/src/client.js

Described in #490.
The testcase described there now yields the following error instead of segfaulting:
```
Error: Cannot call getConnectivityState on a closed Channel
at Immediate.checkState [as _onImmediate] (/home/pixel/sources/example_for_issue_grpc/node_modules/grpc/src/client.js:723:35)
at runCallback (timers.js:810:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)
```
We may also want to add testcases for this, but let's stop the bleeding first.

Fix potential segmentation fault.

---

packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/test/test-channel-credentials.ts

Basically, port #403 to the pure JavaScript library. I had to change a couple of the internal parts of the API.
CC @JackOfMostTrades

Add checkServerIdentity callback to pure js library

---

packages/grpc-native-core/src/client.js

Fixed call in `deprecated_request_wrap` to properly pass `options` to `getDefaultValues`

properly pass `options` to `getDefaultValues`

---

packages/grpc-js-core/src/channel-options.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/src/subchannel.ts

For now at least I think this is a better solution than throwing an error for unrecognized arguments that we know that the core handles, particularly because this solution won't automatically break some existing users that try to switch over transparently.

Pure JS: add warnings for unhandled channel options

---

packages/grpc-native-core/src/server.js

Enhances documentation of the `type` argument for `grpc.Server.register`, leveraging on JSDoc's support for literal enumerations.
This keeps developers from having to dig through the source code to find the valid values.

Replaces `string` type with actual possible values

---

PACKAGE-COMPARISON.md
README.md
packages/grpc-js-core/README.md
packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/compression-filter.ts
packages/grpc-js-core/src/deadline-filter.ts
packages/grpc-js-core/src/filter-stack.ts
packages/grpc-js-core/src/filter.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/src/metadata-status-filter.ts
packages/grpc-js-core/src/subchannel.ts
packages/grpc-js-core/test/test-call-stream.ts

This implements the [public Channel API proposal](https://github.com/grpc/proposal/blob/master/L32-node-channel-API.md) in the pure JS library. I also implemented `Client#getChannel`.
As part of this change I renamed `CallStream` to `Call` and the previously named `Call` to `SurfaceCall`, plus a couple of other changes. The naming scheme is a little confusing now, but I don't think there should be any meaningful user-visible changes.

Pure JS: Implement public Channel API

---

packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/test/test-channel-credentials.ts

This should make the `ChannelCredentials` classes in the two libraries have the same API.

Mark some methods of ChannelCredentials as internal

---

packages/grpc-js-core/src/constants.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/logging.ts
packages/grpc-js-core/test/test-logging.ts

These were missing from the pure JS implementation. This commit adds them.

grpc-js-core: implement setLogger() and setLogVerbosity()

---

packages/grpc-js-core/test/test-metadata.ts

The `Buffer()` constructor should not be used. This commit replaces its use in grpc-js-core tests with `Buffer.from()`.

grpc-js-core: remove use of deprecated Buffer() constructor

---

packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/test/test-metadata.ts

This PR:
- Simplifies regular expression usage.
- Adds a missing space to an error message.
- Caches `Object.prototype.hasOwnProperty()` to prevent tampering.
- Simplifies the code in `fromHttp2Headers()`.
Another simplification (that would get rid of the `hasOwnProperty()` usage) would be to make `internalRepr` a `Map`, but I wanted to check with the maintainers first.

grpc-js-core: metadata cleanup

---

test/api/error_test.js
test/proto/echo_service.proto
test/proto/test_messages.proto
test/proto/test_service.proto

This copies several tests from `packages/grpc-native-core/test/surface_test.js`, with modifications to use each client. This covers several error conditions to hopefully increase code coverage. I left the tests in the original file even though they're kind of redundant now.

Add some tests for error cases for both clients

---

packages/grpc-js-core/package.json
packages/grpc-js-core/src/index.ts

This fixes the engines field in the `package.json` file to match what we actually need, and also add a check at library load time to fix #382.

Pure js: fix engines field, add runtime check

---

packages/grpc-native-core/src/server.js

Native server: don't pass non-integer status codes to core

---

packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/status-builder.ts
packages/grpc-js-core/test/test-status-builder.ts

This commit ports `StatusBuilder` to TypeScript.

grpc-js-core: add StatusBuilder support

---

packages/grpc-js-core/gulpfile.ts
packages/grpc-js-core/src/call-credentials-filter.ts
packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/call.ts
packages/grpc-js-core/src/channel-credentials.ts
packages/grpc-js-core/src/channel.ts
packages/grpc-js-core/src/client.ts
packages/grpc-js-core/src/compression-filter.ts
packages/grpc-js-core/src/deadline-filter.ts
packages/grpc-js-core/src/index.ts
packages/grpc-js-core/src/logging.ts
packages/grpc-js-core/src/make-client.ts
packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/src/object-stream.ts
packages/grpc-js-core/src/status-builder.ts
packages/grpc-js-core/src/subchannel.ts
packages/grpc-js-core/test/test-call-stream.ts
packages/grpc-js-core/test/test-logging.ts
packages/grpc-js-core/test/test-status-builder.ts

This PR gets linting passing for the `@grpc/grpc-js` module. The third commit also removes unused variables (not including function parameters).

Clean up linting

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json

Not changing the submodule because we want to use the binaries from the prerelease.

Native: bump to 1.15.0

---

packages/grpc-native-core/README.md

It was pointed out to me that the previous "build from source" instructions were incorrect after we moved to this grpc-node repo.

Native: fix build instructions to account for move to new repo

---

packages/grpc-native-core/package.json
packages/grpc-native-core/src/credentials.js

Fixes #545.
Since `getRequestMetadata` is now [deprecated](https://github.com/googleapis/google-auth-library-nodejs/blob/6e3bc6ebe06bd476c0588d11d5e5666fd5e24f36/CHANGELOG.md#the-getrequestmetadata-method-has-been-deprecated) in `google-auth-library`, we are getting deprecation warnings in Google Cloud client libraries.
Since there is no good way to tell if the user passed old or new `googleCredentials` object, we can check if it has `getRequestHeaders` method or not, and if it has one, use it, otherwise fallback to the old `getRequestMetadata`. Ugly but works.

grpc-native-core: do not use deprecated getRequestMetadata

---

packages/grpc-native-core/package.json
packages/grpc-native-core/src/credentials.js

Backport "grpc-native-core: do not use deprecated getRequestMetadata" to 1.15.x

---

packages/grpc-js-core/src/compression-filter.ts
packages/grpc-js-core/src/filter.ts

`return await` isn't typically useful in `async` functions. Split out of #536

grpc-js-core: remove use of return await

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json

Bump the version so that we can publish #548.

Native: bump to 1.15.1

---

.gitmodules
packages/grpc-tools/src/config.h
packages/grpc-tools/src/config_protobuf.h
packages/grpc-tools/src/generator_helpers.h
packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_generator.h
packages/grpc-tools/src/node_generator_helpers.h
packages/grpc-tools/src/node_plugin.cc

We're going to need this if we ever want to publish another version of grpc-tools. This doesn't build yet, but I think it has all of the pieces that we need to build it.

Add Node plugin code and protobuf submodule to grpc-tools

---

packages/grpc-js-core/test/test-call-stream.ts

This should fix grpc/grpc#16692.

Fix missing property in ClientHttp2StreamMock

---

packages/grpc-native-core/index.js
packages/grpc-protobufjs/README.md

Documentation updates.

---

packages/grpc-js-core/src/call-stream.ts
packages/grpc-js-core/src/metadata.ts

`Metadata.fromHttp2Headers()` throws if any reserved headers are passed. Instead of deleting headers before calling the function, this commit causes the function to ignore reserved headers.
As a side note, this should make `Metadata.fromHttp2Headers()` easier to use on the server side, where clients may send a wider variety of headers.

grpc-js-core: ignore reserved headers in fromHttp2Headers()

---

packages/grpc-js-core/src/compression-filter.ts

The compression flag is written to the first byte, but read from the second byte. Update the read offset to match.

grpc-js-core: update compression flag byte offset

---

packages/grpc-js-core/package.json

`semver` is now used in `index.ts`, meaning that it needs to be included in the `"dependencies"` section of the `package.json`, otherwise deployments that use `npm i --production` will fail.

grpc-js-core: make semver a prod dependency

---

packages/grpc-native-core/ext/channel_credentials.cc

Fix grpc/grpc#16846.
The `ToLocalChecked` call is where it is because the result is empty if the function threw an error.
Strictly speaking, this is more correct because that variant of `callback->Call` is deprecated, but we only need this now because some Node interpreter change broke it entirely.

Native: Use non-deprecated function to call checkServerIdentity cb

---

packages/grpc-tools/src/node_generator.cc

Reposting from https://github.com/grpc/grpc/pull/16874

Generate JS file even if no services are defined in proto file; fix #574

---

packages/grpc-protobufjs/src/index.ts

This now allows users to load `.proto` files using absolute paths, and failures to resolve any files should now result in errors instead of empty return values.
A couple of notes:
- For efficiency, we don't check anything for absolute paths. We just return them directly and let Protobuf.js check them itself when it tries to read the file.
- Throwing an error is OK here even when loading asynchronously because Protobuf.js catches errors thrown by `resolvePath`.

@grpc/proto-loader: Fix absolute path handling and improve reporting of loading failures

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Also remove an included file in `package.json` because it was a workaround for an issue in core that was fixed.

Bump submodule and version to 1.16.0-pre1

---

.gitignore
packages/grpc-native-core/src/client.js

Add "callInvocationTransformer" argument to the client construction options as suggested by @murgatroid99 . The main purpose is to add an intercepting point to handle channel management.
More details in this proposal: [Node gRPC Call Invocation Transformer API](https://github.com/grpc/proposal/pull/107)

Call invocation transformer

---

packages/grpc-js-core/src/metadata.ts
packages/grpc-js-core/test/test-metadata.ts

This PR contains the following changes:
- Changes the `Metadata` backing store from a POJO to a `Map`. This is faster in recent versions of Node. It also eliminates an expensive `delete` operation, and the use of `hasOwnProperty()`.
- Remove use of `lodash` in `Metadata`. There was only one remaining use. This simplifies the code and helps performance.
- Simplify Metadata cloning. `cloneMetadataObject()` was only used in one place, so I inlined it. Also removes an extra `MetadataObject` allocation.
In some microbenchmarking, I'm seeing an improvement of 25-30% for the following sequence of operations:
```
const metadata = Metadata.fromHttp2Headers(http2Headers);
metadata.get('grpc-encoding');
metadata.get('grpc-accept-encoding');
metadata.remove('grpc-encoding'); …
```

Metadata class simplifications

---

packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/test/surface_test.js

This fixes #595. The tests now verify that clients report errors immediately when receiving malformed responses, no matter what the server does. The new error thrown in `InterceptingCall#_callNext` should prevent this particular kind of error from happening silently in the future.

Make clients fail better with malformed responses

---

packages/grpc-js-core/package.json
packages/grpc-js-core/src/call-credentials.ts
packages/grpc-js-core/src/filter-stack.ts
packages/grpc-js-core/src/make-client.ts

This commit removes lodash as a production dependency. It remains as a devDependency because it's used in tests, but the uses in the `src/` directory were easily replaced with vanilla JavaScript.

grpc-js-core: remove simple uses of lodash

---

packages/grpc-native-core/src/client.js

This replaces the use of `_.isFunction` with the native `typeof foo === 'function'`.

refactor: drop usage of _.isFunction

---

packages/grpc-native-core/src/metadata.js

This drops the usage of `_.isString` in favor of `typeof foo === 'string'`

refactor: drop usage of _.isString

---

packages/grpc-health-check/health.js
packages/grpc-health-check/package.json

This swaps out `lodash` for `lodash.clone` and `lodash.get` packages.

refactor: use individual lodash packages for health check

---

packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/src/protobuf_js_5_common.js
packages/grpc-native-core/src/protobuf_js_6_common.js

This drops `_.map` in favor of the native `Array.prototype.map` implementation.

refactor: drop usage of _.map

---

packages/proto-loader/package.json
packages/proto-loader/src/index.ts
packages/proto-loader/tsconfig.json

This drops the `lodash` package in favor of `lodash.camelcase`

refactor: use individual lodash package for proto loader

---

packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/src/protobuf_js_5_common.js
packages/grpc-native-core/test/client_interceptors_test.js

This uses the native `Array.isArray` instead of lodash.

refactor: use Array.isArray instead of _.isArray

---

packages/grpc-native-core/src/server.js

Replaces `_.bind` with the native `Function.prototype.bind`.

refactor: drop usage of _.bind

---

packages/grpc-js/test/test-call-stream.ts

This should fix grpc/grpc#17218. This change is needed now as a result of the changes made in DefinitelyTyped/DefinitelyTyped#30425, which reflects changes made to the http2 module itself in Node 10.

Add missing sendTrailers method in ClientHttp2StreamMock

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/server.js
packages/grpc-native-core/test/common_test.js

This replaces the usage of `_.defaults` with `Object.assign`.  Note that the order of assignment with this change is reversed.

refactor: use Object.assign

---

packages/grpc-js-core/test/test-call-stream.ts

So our 1.16.x tests are clean.

Backporting #632 to 1.16.x

---

packages/grpc-native-core/src/client_interceptors.js

This replaces `_.union` with a native `Array.from(new Set(array.concat(array)))` kinda thing.

refactor: drop usage of _.union

---

packages/grpc-native-core/src/server.js

**NOTE: It's very possible this one won't work and is a bad idea.**
This drops `_.isObject` in favor of the native `typeof foo === 'object'` approach.

refactor: drop usage of _.isObject

---

packages/grpc-native-core/src/client_interceptors.js

refactor: drop usage of _.get

---

packages/grpc-native-core/index.js
packages/grpc-native-core/package.json
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/client_interceptors.js
packages/grpc-native-core/src/common.js
packages/grpc-native-core/src/credentials.js
packages/grpc-native-core/src/metadata.js
packages/grpc-native-core/src/protobuf_js_5_common.js
packages/grpc-native-core/src/protobuf_js_6_common.js
packages/grpc-native-core/src/server.js
packages/grpc-native-core/templates/package.json.template
packages/grpc-native-core/test/common_test.js

This is the final PR for dropping `lodash` 🍻

refactor: use lodash subpackages

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Best I can tell, it's never used.

refactor: drop dependency on async

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Best I can tell, it isn't used, and we were installing a very, very old version.

refactor: drop dependency on google-auth-library

---

packages/grpc-js/src/channel.ts

When running jest tests against a project that includes `grpc-js` I'm getting the following module resolve related error from jest:
```
FAIL  test/unit/lnd/util.spec.js
Test suite failed to run
Cannot find module '../../package' from 'channel.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/channel.js:16:36)
```
This is caused by the following code:
```javascript
require('../../package')
```
The problem is that grpc-js is relying on the node module resolver to load in package.json when there is really no need for it to do this.
This is the only place in the code where `package.json` is required in this way. All other places it is required as a file (`require('../../package.json')`
Require …

fix: require package.json directly

---

packages/grpc-native-core/index.d.ts

This PR adds a missing Typescript definition for grpc-native-core/Server.bindAsync() and fixes a typo.

Add missing Typescript definition for Server.bindAsync()

---

packages/grpc-native-core/src/protobuf_js_6_common.js

This fixes an error when using `loadObject` with Protobuf.js 6 exposed by a change introduced in #618. See [these docs](http://dcode.io/protobuf.js/Service.html) for the definition of the new variable.

Native: Protobuf.js 6 loadObject: switch to mappable methodsArray

---

packages/grpc-native-core/src/protobuf_js_6_common.js

This fixes an error reported in https://github.com/grpc/grpc-node/issues/556#issuecomment-445176480. The documentation for those two members is [here](http://dcode.io/protobuf.js/NamespaceBase.html). Importantly, `nested` can be `undefined`, but `nestedArray` is always an array.

Native: Protobuf.js 6 loadObject: switch to nestedArray

---

packages/proto-loader/src/index.ts

Fixes the bug described in #668. When handling "common" proto files, the Protobuf.js internals assume that the resolver outputs paths in a particular format, so we use its own resolver when the file cannot be found using the include paths.

proto loader: Fall back to default path resolution

---

packages/grpc-native-core/src/protobuf_js_6_common.js

We don't have `Object.values` in node 6.

Fix for node 6.

---

packages/grpc-native-core/ext/channel.cc

Call with [`option.host`](https://grpc.io/grpc/node/grpc.Client.html#~CallOptions) to any value will resulting in `undefined`.
This bug was introduced in #446, original logic is here: https://github.com/grpc/grpc-node/commit/c4e3f1b7a083ad4dbeb0e1f2ce9083b17f85f3c6#diff-7503358f55dbc64f54f5e0faa14b246aL624 
It's a copy paste error.

bug: set host will always undefined

---

packages/grpc-native-core/index.d.ts
packages/grpc-native-core/index.js
packages/grpc-native-core/src/common.js

This is necessary for the proto-loader library to work with the native grpc library after #703 is merged. This also needs to be upmerged into master before the tests in that PR will pass.

grpc native: Fix handling of non-service objects in package definitions

---

gulpfile.ts
packages/proto-loader/gulpfile.ts
packages/proto-loader/src/index.ts
packages/proto-loader/test/descriptor_type_test.ts
packages/proto-loader/test_protos/enums.proto
packages/proto-loader/test_protos/messages.proto
packages/proto-loader/tsconfig.json

This is an implementation of [gRFC proposal L43](https://github.com/grpc/proposal/blob/master/L43-node-type-info.md), adding message and enum type information to the output of the `load` and `loadSync` functions. When loaded into a gRPC implementation using `loadPackageDefinition` those objects will appear in the expected place in the object tree. They will also be included in the `requestType` and `responseType` message properties.
This supersedes PRs #408 and #448, and fixes #407.

Add message and enum type information to package definition output.

---

packages/grpc-js/package.json

I specifically want to publish #704 around or before when we publish the next proto-loader version with #703.

Bump grpc-js to 0.3.4

---

run-tests.bat
run-tests.sh

We will still build binaries for node 4 and 5, but support is now going to be provided as a best effort.

Stop testing on node 4 and 5.

---

packages/grpc-js/tsconfig.json

According to [this StackOverflow post](https://stackoverflow.com/a/50466512/159388), the ES2017 target should work for Node 8.10 and above, which is our compatibility boundary anyway.

Target grpc-js build at a higher ES standard

---

packages/grpc-health-check/v1/health_grpc_pb.js
packages/grpc-native-core/src/credentials.js
packages/grpc-native-core/src/protobuf_js_5_common.js
packages/grpc-native-core/test/call_test.js
packages/grpc-native-core/test/common_test.js
packages/grpc-native-core/test/credentials_test.js
packages/grpc-native-core/test/end_to_end_test.js
packages/grpc-native-core/test/math/math_grpc_pb.js
packages/grpc-native-core/test/metadata_test.js
packages/grpc-native-core/test/surface_test.js
packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_plugin.cc
test/api/error_test.js
test/interop/interop_client.js
test/interop/interop_server.js
test/performance/benchmark_client.js
test/performance/benchmark_server.js

this PR comes to resolve #670 .
by doing so, I have done the following things:
- replaced all usages of `new Buffer` with `Buffer.from`
- changed default minimum node version to 6 to to EOL of older node versions

Resolve new Buffer deprecation

---

packages/grpc-tools/build_binaries.ps1
packages/grpc-tools/build_binaries.sh
packages/grpc-tools/copy_well_known_protos.js
packages/grpc-tools/package.json
packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_generator.h
packages/grpc-tools/src/node_plugin.cc
tools/release/kokoro/macos-grpc-tools.cfg

This has a few different cleanup changes that we need before publishing the next release:
- Move the well-known protos copying logic to a prepublish hook instead of putting them in the binary tarball. This more closely matches what we did before.
- Move the binaries to the new GCS bucket.
- Bump the version number.
- Remove the "minimum_node_version" argument that was made unnecessary in a previous change. We never published a version with that argument so we're not breaking anything by removing it.

grpc-tools cleanup and packaging update

---

packages/grpc-tools/build_binaries.ps1

Fixing an issue pointed out in #499.

node-pre-gyp refers to Windows as 'win32'

---

packages/grpc-tools/package.json

Fixes #746.
This allows npm to determine the path to `node-pre-gyp` for the install script from `grpc-tools` rather than specifying the path. This also brings the install script in line with the one used for the `grpc` package.

Fix grpc-tools install script

---

packages/grpc-js/src/events.ts

This commit removes the unused `EmitterAugmentation0` and `EmitterAugmentation2` interfaces.

grpc-js: remove unused EventEmitter interfaces

---

packages/grpc-js/src/deadline-filter.ts
packages/grpc-js/src/subchannel.ts

This fixes a problem I encountered while trying to reproduce #694. Currently if the channel never connects the promise sticks around forever.
Edit: The original test that exposed this problem no longer shows it with these changes.

grpc-js: deadline filter: reject promise if call ends

---

packages/grpc-tools/package.json

I investigated further why I'm having the problem I first described [here](https://github.com/grpc/grpc-node/issues/748#issuecomment-466409893) and subsequently led us to think it was [an issue in yarn](https://github.com/yarnpkg/yarn/issues/7063).
As it turns out yarn tried to install `grpc-tools` before `node-pre-gyp`. If there is a reason for having `node-pre-gyp` in `bundledDependencies` then feel free to close this PR.
You can verify that the issues disappear with following `package.json` (having this project cloned in a sibling directory):
```json
{
"dependencies": {
"grpc-tools": "^1.7.1"
},
"resolutions": {
"grpc-tools": "file:../grpc-node/packages/grpc-tools"
}
}
```

Make node-pre-gyp a regular dependency

---

packages/proto-loader/src/index.ts

I'm running proto-loader from inside a [haraka](https://github.com/haraka/Haraka/) plugin.
When I send `includeDirs` as Array, `instanceof` fails. 
When I do `Array.isArray` it works correctly. 
Turns out `instanceof` does not work correctly for arrays in different contexts!

Array.isArray instead of instanceof for consistent checking

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/templates/binding.gyp.template

This should be another step toward fixing our Alpine build failures.

Omit a build warning that v8 headers violate

---

tools/release/native/Dockerfile

[See this question for why this change is needed](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository)

Fix jessie-backports URL

---

README.md

The `http2` module is no longer considered experimental.
Fixes: https://github.com/grpc/grpc-node/issues/808

grpc-js: remove experimental text for http2

---

packages/proto-loader/src/index.ts
packages/proto-loader/test/descriptor_type_test.ts
packages/proto-loader/test_protos/well_known.proto

This is a draft PR. It is not complete yet because there was some push back in #771 about implementing this in protobufjs, and I'd like feedback on the general approach taken. Since almost 3 weeks have passed with no response from protobufjs, I decided to open a WIP PR.
This commit ensures that the Google well known protos are available because protobufjs only exposes a subset of them.
Fixes: https://github.com/grpc/grpc-node/issues/771

proto-loader: include Google well known protos

---

packages/grpc-js/src/index.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/test/test-server-credentials.ts

At gRPC Conf, I discussed porting the code in [`grpc-server-js`](https://www.npmjs.com/package/grpc-server-js) to `@grpc/grpc-js` with @murgatroid99. I think it makes the most sense to do this as smaller changes that are easier to author and review. `ServerCredentials` is a relatively isolated piece of code, so I decided to start there. The code in this PR is ported to TypeScript from https://github.com/cjihrig/grpc-server-js/blob/master/lib/server-credentials.js.

grpc-js: add ServerCredentials support

---

packages/grpc-js/package.json
packages/proto-loader/package.json

It turns out that the `prepare` scripts need a direct dependency on Typescript.

Re-add typescript dependency on packages that use it

---

packages/grpc-js/package.json
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/common.ts
packages/grpc-js/test/fixtures/math.proto
packages/grpc-js/test/test-server.ts

This PR builds on the work in https://github.com/grpc/grpc-node/pull/809. Again, the goal is to keep these PRs down to a manageable size (~700 lines here is already pushing that), so the server is not 100% functional.
This commit defines the `Server` API contract, and implements the `Server` functionality (with tests), minus the actual handling of requests. This commit intentionally does not publicly expose the `Server` functionality in `index.ts` yet.

grpc-js: define Server API contract

---

packages/grpc-native-core/package.json

Require @types/protobuf.js at version 5.x as a dependency

---

packages/grpc-native-core/ext/channel.cc
packages/grpc-native-core/ext/channel_credentials.cc
packages/grpc-native-core/ext/server_credentials.cc
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Fixes #834, and lets us get out the Node 12 packages.

Native: fix Node 12 compilation errors

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Reverts grpc/grpc-node#838. It looks like this caused more problems than it solved.

Revert "Protobufjs typescript types backport"

---

.gitignore

This file is generated by newer versions of Node, and can show up in multiple locations.

gitignore Node's bash completion file

---

PACKAGE-COMPARISON.md
packages/grpc-js/gulpfile.ts
packages/grpc-js/package.json
packages/grpc-js/src/index.ts
test/gulpfile.js

This commit bumps the required semver range to versions of Node that include a non-experimental http2 module.

grpc-js: require non-experimental http2

---

packages/grpc-js/src/client.ts

The `kChannel` symbol was being exported due to a TypeScript issue. That issue has been resolved, so it seems OK to remove the export.
While I'm here, should I rename `kChannel` to something that follows the project's style (per https://github.com/grpc/grpc-node/pull/832#discussion_r277438065)?

grpc-js: don't export private symbol

---

packages/grpc-native-core/src/grpc_extension.js

This would have helped troubleshoot https://stackoverflow.com/questions/55924715/cant-get-google-stt-api-working-on-embedded-machine

Add some helpful information to the fallback error when loading addon

---

packages/grpc-js/src/index.ts

We (`google-gax`) need these two types exported to switch from C-core gRPC.

grpc-js: adding GrpcObject

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json

We could just publish new binaries but if we want other people to be able to build against Electron 5 we need to publish a new library version.

Update to 1.20.3

---

packages/grpc-js/src/index.ts

Pub/Sub needs `ServiceError` to be exported from gRPC.

grpc-js: add ServiceError

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/fixtures/echo_service.proto
packages/grpc-js/test/fixtures/test_service.proto
packages/grpc-js/test/test-server-errors.ts
packages/grpc-js/test/test-server.ts

This commit adds support for unary and server streaming RPCs.
Server and bidi streaming will be added, but first I'd like to extract [this logic](https://github.com/grpc/grpc-node/blob/ad9eb795d6a194716f95ce3c1d70e5bc78b60f7d/packages/grpc-js/src/call-stream.ts#L294-L351) to make it reusable by the server.

grpc-js: support unary and server streaming rpcs

---

packages/grpc-native-core/index.d.ts

Removes:
- getCallCredentials
- getSecureContext
These functions no longer exist, so their presence in the TypeScript type definitions is invalid.

Native: Remove unused ChannelCredential type definitions

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/stream-decoder.ts

This commit pulls the stream decoding logic into a separate
class so that it can be reused by the server code.

grpc-js: extract reusable stream decoding logic

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server-errors.ts
packages/grpc-js/test/test-server.ts

This commit adds client streaming RPC support.

grpc-js: add client streaming RPC support

---

merge_kokoro_logs.js

This should fix the problem we see in the test logs in #864 where some parsed logs were `null` and that stopped it from combining other logs for the same Node version.

Handle parse failures when merging test logs

---

packages/grpc-js/package.json
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

Now that all four server handler types have landed, this is just some small follow up cleanup:
**First commit:**
During initial implementation, the `serialize` and `deserialize` APIs of `ServerReadableStream`, `ServerWritableStream`, and `ServerDuplexStream` became inconsistent. This commit brings back consistency.
**Second commit:**
This commit removes some unnecessary imports and exports from the server code.
**Third commit:**
This commit resolves issues from `npm outdated`. The `gts` dependency will be updated to 1.x.x in a separate follow up PR, as it comes with significant churn.

grpc-js: misc small cleanup

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

This got removed in #842 but I think the upmerge undid that, possibly because that was a reversion of a backported PR. Fixes #883.

Remove @types/protobufjs dependency again

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/test/test-server-deadlines.ts

This commit adds support for client cancellation to the server, and adds cancellation/deadline tests.

grpc-js: support client cancellation

---

packages/grpc-js/src/channel.ts
packages/grpc-js/src/deadline-filter.ts

Instead of having filters explicitly use the channel's `connectivityStateChanged` listener to track connectivity state, make the filter stack's initial metadata promise only resolve when the channel becomes connected. Then any filter can just await that promise to wait for the channel to connect. This should fix the warning reported in https://github.com/grpc/grpc-node/issues/694#issuecomment-496566860.

grpc-js: Change how filters access connectivity information

---

packages/grpc-js/package.json
packages/grpc-js/tsconfig.json

This PR updates [TypeScript to 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/), which is supposed to be faster. It also enables incremental builds to speed up compilation. On my machine I'm seeing the compile times drop from about ~4-5 seconds every time to  ~1.5-4 seconds depending on what is changed.

grpc-js: update typescript and enable incremental builds

---

PACKAGE-COMPARISON.md
packages/grpc-js/src/metadata.ts
packages/grpc-native-core/ext/call.cc
packages/grpc-native-core/index.d.ts
packages/grpc-native-core/src/metadata.js
packages/grpc-native-core/src/server.js
packages/grpc-native-core/test/call_test.js
packages/grpc-native-core/test/end_to_end_test.js
packages/grpc-native-core/test/surface_test.js

This is an implementation of [proposal L48](https://github.com/grpc/proposal/blob/master/L48-node-metadata-options.md). For grpc-js this just adds the API to pass the options in. They currently have no effect, but this is required to make it a working drop-in TypeScript replacement.

Add metadata options

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/stream-decoder.ts

This fixes #895. This depends on specific HTTP/2 framing behavior so I don't know how to turn it into a unit test, but I suspect that this bug was also the cause of grpc/grpc#18967. If so that can act as a regression test.
CC @cjihrig.

Fix dropped messages when multiple arrived in one HTTP/2 frame

---

packages/grpc-js/src/server.ts

gRPC has its own mechanisms for timing out a request. Furthermore, the default timeout was removed from Node.js.
Refs: https://github.com/nodejs/node/pull/27558

grpc-js: disable http2 server timeout

---

packages/grpc-js/src/index.ts

This commit loads the required semver range from the `package.json` file, instead of hard-coding the string in `index.ts`.
This should make it a bit easier to update the required version in the future. After this change, the version string will exist in:
- This module's `package.json` file. Ideally, this would be the only non-docs location.
- The top level `PACKAGE-COMPARISON.md` file.
- The top level's `test/gulpfile.js`. I'm happy to update that as well if it's OK.

grpc-js: load semver range from package.json

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

This commit implements the following portion of the spec:
If Content-Type does not begin with "application/grpc", gRPC servers SHOULD respond with HTTP status of 415 (Unsupported Media Type). This will prevent other HTTP/2 clients from interpreting a gRPC error response, which uses status 200 (OK), as successful.

grpc-js: reject invalid Content-Type requests

---

merge_kokoro_logs.js

This failure showed up in the tests on #902. The loop checks if each object is populated, but if the first one is undefined then `merged.testsuites.testsuite` throws.

Don't throw if failure is at index 0

---

packages/grpc-js/src/channel.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/stream-decoder.ts

When the gRPC server has not been started, incoming connections can be destroyed on session establishment, which happens before a stream is created.

 grpc-js: destroy connections when session begins

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-call-stream.ts
test/api/connectivity_test.js

First, I think this fixes #734. When a Node http2 client session receives a GOAWAY from the server, it sets its closed flag and emits a `'goaway'` event immediately, and then emits the `'close'` and `'error'` (if needed) events a tick or two later. We listen for the `'close'` event to know when a session should be considered unusable, and if the channel tries to start a stream in between the `'goaway'` event and the `'close'` event, it ends with an error. The fix is to simply stop using the subchannel as soon is the `'goaway'` event comes in.
Second, RST_STREAM error codes were not getting handled correctly in the stream code, including artificial RST_STREAM errors created by the Node http2 code when a GOAWAY is received.

Pure JS: Fixed two bugs with goaway handling

---

packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_generator.h
packages/grpc-tools/src/node_plugin.cc

This adds a `generate_package_definition` option to the code generation plugin we distribute with grpc-tools. If that option is set the output is a file that returns a `PackageDefintion` object (defined [here](https://github.com/grpc/proposal/blob/master/L23-node-protobufjs-library.md)), which can be loaded by either grpc implementation library's `loadPackageDefinition` function.
I tested this by building the plugin, generating a file from our examples' `helloworld.proto` and loading it with grpc-js.
I used the option handling code from the last time someone added an option to this package.

grpc-tools: Add option to generate package definition

---

packages/grpc-native-core/gulpfile.ts
packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node.bat
tools/release/kokoro-electron.bat
tools/release/kokoro-electron.sh
tools/release/kokoro-nodejs.bat

This directory is taken from the NodeJS build error logs in #917.

Delete another directory in Windows build script

---

test/api/connectivity_test.js

Avoid potential timing issues with making the final calls and calling `forceShutdown` on the server in the `after` hook.

Connectivity test: ensure all calls end before ending the test

---

packages/grpc-native-core/ext/channel.cc

If passing an `undefined` as the first argument throws a generic error about all 3 arguments which is confusing. Googling for it sends you to rabbit hole (e.g. https://github.com/grpc/grpc/issues/10786).

Fix Channel argument validation error messages

---

packages/grpc-js/src/call-stream.ts

This is an attempt to get a fix for #941
There are 2 things here:
1) Correctly check http error status codes as number rather than string. This is probably correct.
2) Trigger `handleTrailers` in the case of an http error. This is probably not the right thing to do, but I'm not very familiar with the codebase or protocol and I'm literally just hacking away trying to get the result I'm looking for. This does fix the error I'm experiencing, although probably not the right way to go about it.

fix: properly handle http error status codes

---

packages/grpc-js/src/client.ts

This is a follow-up to #943, fixing part of the problem reported in #941. I'm pretty sure that the current grpc library just outputs a `null` message if no message arrives for a unary call. This check here is overriding more useful errors, so it's best to just remove it.

Remove check in grpc-js that doesn't appear in grpc

---

packages/grpc-native-core/index.d.ts

Fixes: https://github.com/grpc/grpc-node/issues/950
The latest release of grpc-node cannot be used in a typescript project that uses -noImplicitAny.  This is due to a signature being added without a specified return type.  This causes the return type to implicitly be 'any' which TS explicitly disallows.  For projects that use strict flags to catch lots of bugs, this prevents usage of this version of grpc entirely.
Fix is simple, just actually provide an annotation for this method.

Fix 'noImplicitAny' issue with declaration file.

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

This is needed to build from source now that we're building the cares resolver.

Include address_sorting files in package

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

I definitely already did this, but I guess there's some git weirdness with backporting a change from master, reverting the backport in the branch, and then merging the branch into master.

Remove dependency on @types/protobufjs again

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json

We should really publish #953.

Bump native to 1.22.1

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

This time I actually tested the `npm pack` output with `--build-from-source`. We should really add a test for that. But I'd like to get this out.

Include cares files in published package

---

packages/grpc-js/src/metadata.ts

I want to preserve the invariant that any `Metadata` object is always a valid set of gRPC metadata. googleapis/nodejs-datastore#415 indicates that we need to handle the case where the `http2` module invalidly mangles the headers. We should try to do as much as possible, but erroring out when something goes wrong is probably to onerous for our users. So, we emit a warning and omit the problematic metadata entry from the resulting metadata object.
The added `export` is completely separate. VSCode complained about it not being there.

Warn instead of failing when constructing metadata from remote end

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/server.js

This has gotten a couple of questions and the current documentation is pretty bad.

Add options documentation for Channel, Client, and Server

---

packages/grpc-js/package.json

Currently when you `npm i` you get a failure to compile because there are no type definitions for `semver`

grpc-js: Add @types/semver as devDependency

---

packages/proto-loader/src/index.ts

The issue: https://github.com/grpc/grpc-node/issues/876
This is an obvious typo; `typeof` has to return a string `'undefined'`, not a literal `undefined.`
The fix is so minor and trivial that I don't mind anyone to please create a different PR and fix it there, instead of waiting for me to sign the Linux Foundation license, etc.

Fix a TypeError loading a non-existent proto file.

---

packages/grpc-js/src/index.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-native-core/index.d.ts

This mainly makes the server call types and `Server#registerService` function signature more specific, the server error types more permissive, and exports some more types needed for writing service implementations.
Also, this fixes a typo in the native library's `index.d.ts` that got brought up in #965. That class is essentially internal, so code written using the typo works. I have added an alias to avoid breaking that.

Improve server-related types exported by grpc-js

---

packages/grpc-native-core/src/client.js

It turns out that you can't use that syntax for optional array parameters. The doc generator is happy with this change.

Fix minor errors in new docs

---

packages/grpc-health-check/package.json

The last version we published was 1.6.6 and apparently there is some stuff since that that we haven't published.

Set grpc-health-check version to 1.7.0

---

packages/grpc-health-check/package.json

The package name we currently have there was never actually published, and I think we want continuity for now.

Revert grpc-health-check name to original name

---

package.json
packages/grpc-js/package.json
packages/grpc-js/test/test-server.ts

My goal was to be able to successfully:
```
git clone git@github.com:grpc/grpc-node.git
cd grpc-node/packages/grpc-js
npm i
npm run test
```
What I did:
1. Specify all of the dependencies required to run the tests in `package.json` as `devDependencies`
2. Add teardown steps to two tests that prevented the process from exiting when the tests completed.

Add dev-dependencies and fix tests so they exit after running

---

packages/grpc-native-core/index.d.ts

The `makeServerStreamRequest` return type in grpc-native-core is currently `ClientReadableStream<RequestType>`; this PR updates it to `ClientReadableStream<ResponseType>`.

Fix typo in makeServerStreamRequest return type (grpc-native-core)

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

From the [description of `@types/protobufjs`](https://www.npmjs.com/package/@types/protobufjs):
> This is a stub types definition for protobufjs (https://github.com/dcodeIO/ProtoBuf.js). protobufjs provides its own type definitions, so you don't need @types/protobufjs installed!
Introducing this module caused a bunch of build failures for me on a project that depends on `grpc`.

Remove deprecated @types/protobufjs module

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/package.json.template

Somehow the last removal of that dependency didn't make it into the 1.23.x branch.

Remove @types/protobufjs and bump to 1.23.1

---

tools/release/kokoro-electron.bat
tools/release/kokoro-nodejs.bat

Our build is currently failing because of [a bug in npm 6.11 on Windows](https://npm.community/t/6-11-0-npm-looking-for-executable-packages-in-root-c/9574).

Install npm 6.10 on Windows

---

packages/grpc-native-core/index.d.ts

Fixes #1006 
For sad historical reasons, Typescript's syntax for ambient modules, which is what grpc-native-core's index.d.ts tries to declare, is the same as module augmentations. The way to tell the difference between the two is whether the file has imports or exports outside the declaration. #1002 adds such a declaration, turning the ambient module into a module augmentation. Not only is there no grpc module to augment, module augmentations are subject to a bunch of restrictions since they are only supposed to augment the contents of an existing module. That's the cause of the new errors.
I'm not sure if merging into the grpc@1.23.x branch is correct. That's what I targetted with this change.

Move EventEmitter inside declare module "grpc"

---

packages/grpc-native-core/src/server.js

If there was an error during serialization or deserialization, no stack trace or any output would happen on the node grpc server.
When using protoc compiled js and goog.asserts, the client would receive just "Assertion failed"
```
ERROR:
Code: Internal
Message: Assertion failed
```
We ran into this issue due to repeated enums packed vs. unpacked decoding. E.g. 
https://github.com/protocolbuffers/protobuf/issues/5232

Log internal errors from proto serialization/deserialization

---

packages/grpc-native-core/src/client_interceptors.js

I put these logs at the `ERROR` verbosity level because these errors indicate very fundamental problems that the programmer needs to be aware of. These logs should help with debugging issues like #1022.

Add logging for (de)serialization errors

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/test/test-call-stream.ts

I think this will fix the problem of reporting a status of INTERNAL instead of UNAVAILABLE when the network drops, originally reported in firebase/firebase-functions#536.

Add specific call error for TCP disconnection

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/test-call-stream.ts

My goal was to run:
```
git clone git@github.com:grpc/grpc-node.git
cd grpc-node/packages/grpc-js
npm i
npm run test
```
The tests would fail on the `gts check` portion:
```
> @grpc/grpc-js@0.5.3 posttest /Users/bjornstar/grpc-node/packages/grpc-js
> npm run check
> @grpc/grpc-js@0.5.3 check /Users/bjornstar/grpc-node/packages/grpc-js
> gts check
Index: /Users/bjornstar/grpc-node/packages/grpc-js/src/call-stream.ts
===================================================================
--- /Users/bjornstar/grpc-node/packages/grpc-js/src/call-stream.ts
+++ /Users/bjornstar/grpc-node/packages/grpc-js/src/call-stream.ts
@@ -342,14 +342,18 @@
* from bubbling up. However, errors here should all correspond to
* "close" events, where we will handle the error more granularly */
});
/* If the …
```

grpc-js: Update gts and apply fixes

---

packages/grpc-native-core/index.d.ts

More context —
1. https://github.com/grpc/grpc-node/issues/502#issue-351407366
2. https://github.com/grpc/grpc-node/issues/502#issuecomment-530293049

Fix #502 - Make all properties of CallOptions optional

---

packages/grpc-js/src/call-stream.ts

Revert #1021 as an alternative to #1034 for fixing #1027. That PR caused a warning and a memory leak that are both causing significant issues, so it's probably best to just revert until we can do it properly after #1015 is merged.

Revert "Add specific call error for TCP disconnection"

---

packages/grpc-js/src/compression-filter.ts

This commit fixes a typo observed in https://github.com/grpc/grpc-node/pull/1015#discussion_r323370376

grpc-js: fix typo

---

run-tests.bat
run-tests.sh

Resolves #1038 
In order to use modern javascript syntax and libraries using that syntax we need to stop supporting node v6. At the same time, we can also stop testing other versions of node that are officially EOL.
This PR removes testing against node v6, 7, 9, and 11 while moving the initial node version from v8 to v10.
I also added `node-gyp` as a devDependency since it is required to build.

Stop testing EOL versions of node

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-resolver.ts

This fixes grpc/grpc#20383. The part of the change that actually fixes the problem is the change to `subchannel.ts`; the rest was for debugging the problem. The problem was that the channel target could include the port number, which would cause the server name/certificate matching to fail.

grpc-js: Fix TLS server name handling

---

packages/grpc-js/src/channel.ts
packages/grpc-js/test/test-server-deadlines.ts

This should fix metadata elements from `CallCredentials` (plus a couple of other sources) not being sent to the server. This should have been caught by metadata credentials interop tests; I will need to figure out why we missed this.

Properly use filtered metadata when starting requests

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json

Apparently there's a fix in core that needs to be backported to 1.23

Bump submodule to 1.23.1 and library version to 1.23.4

---

packages/grpc-js/package.json
packages/grpc-js/src/picker.ts
packages/grpc-js/src/resolving-load-balancer.ts

This should fix #1061. Previously the `updateState` call in `exitIdle` could cause infinite recursion if there was a pending call, because the `QueuePicker` there would call `exitIdle` again. The change to `exitIdle` should stop the loop, and the change to the `QueuePicker` would make the loop non-recursive. It's probably just a good idea in general not to change the load balancer state while checking the picks of pending calls as a result of changing the load balancer state.

grpc-js: exitIdle asynchronously in QueuePicker, only act in exitIdle if IDLE

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/binding.gyp.template
packages/grpc-native-core/templates/package.json.template

Remove nanopb from node project. This should be merged after `packages/grpc-native-core/deps/grpc` is updated to the latest.

Clean up nanopb

---

packages/grpc-js/src/load-balancer-pick-first.ts

This should fix #1064 by allowing a pick first channel to reconnect after failing to connect while no calls are pending.

Pick first: go IDLE if all subchannels go IDLE

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/logging.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/subchannel.ts

This adds support for the `GRPC_TRACE` and `GRPC_VERBOSITY` environment variables, with the following tracers:
- `connectivity_state`
- `pick_first`
- `dns_resolver`
- `resolving_load_balancer`
- `subchannel`
It also adds support for the `all` tracer option to enable all of them. The `-` tracer prefix to disable tracers is currently not supported.

Add tracing functionality and a few connectivity state tracers

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

Also move the `requestReresolution` call to `exitIdle` to ensure that resolution will always be attempted if the connection fails because the backend addresses changed.

grpc-js: pick first: remove reference and go idle after disconnect

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

`connectToAddressList` can be called while there is a current pick, and it should not update the state to override that current pick. I think this is what is causing the remaining reports of the problem in #1064 after the partial fix in 0.6.6.

grpc-js: pick-first: fix bad state transition when reconnecting connected LB

---

packages/grpc-js/src/index.ts
packages/grpc-js/src/make-client.ts

Export `handleBidiStreamingCall`, `handleServerStreamingCall`, `handleUnaryCall`, and `ServiceDefinition` to match exports in regular grpc.
Also changed `MethodDefinition<object, object>` to `MethodDefinition<any, any>` in `ServiceDefinition` to emulate the `UntypedServiceImplementation` from the regular grpc code as `ServiceDefinition` is not generic in grpc-js.
This removes some of the barriers preventing using grpc-js in statically generated code as noted in https://github.com/grpc/grpc-node/issues/931

grpc-js Api changes for using statically generated code with grpc-js

---

packages/grpc-js/src/call.ts
packages/grpc-js/src/client.ts
packages/grpc-js/test/test-server-deadlines.ts

The idea here is to communicate in the stack trace that this error just comes from the status. Honestly, I don't know if this will actually improve anything. But in the worst case it still consolidates duplicated code from two files into one function.
This also makes the error message format match the other library (https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/common.js#L83).

Add function for creating errors from statuses

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts

This addresses a failure in a situation where none of the backends in the current address list is available and a DNS query would return new addresses. With the previous code, as long as there were active calls on a channel, `exitIdle` would keep getting called, causing all subchannels in TRANSIENT_FAILURE to switch to CONNECTING after the backoff timer ended, and causing all subchannels in IDLE to switch to CONNECTING immediately. The result is that if there are at least two subchannels that are failing to connect, the load balancer would never enter the IDLE state, so it would never call `requestReresolution` and it would never get the new good address list.
This change can increase churn because it requests reresolution once all subchannels have started connecting, not when they have …

grpc-js: pick first: resolve address again after trying all addresses

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/resolving-load-balancer.ts

This change does the following:
- If all of the subchannels in the pick first load balancer subchannel list go IDLE, the list is removed.
- If a load balancer goes IDLE, the resolving load balancer removes it (redundant with previous item, but good for defense in depth)
- After backing off from failed name resolution, only resolve again if something has requested it in the intervening time. Otherwise just go IDLE.
- Always change to CONNECTING when starting name resolution if the underlying load balancer is IDLE.

grpc-js: Some fixes for how idleness and reresolution are handled

---

PACKAGE-COMPARISON.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/service-config.ts

This also adds support for the `grpc.service_config` channel argument so that this load balancer can be enabled on the client side. I don't have any automated tests for this, but for a simple manual test I modified the interop client with a service config argument including a "round_robin" load balancer config and the tests passed and I confirmed that they were using the new round robin load balancer.

Add round robin load balancer implementation

---

packages/grpc-js/src/subchannel.ts

This should fix the connection leak described in #1085.

grpc-js: Close http2 sessions that are dropped by their subchannels

---

packages/grpc-js/src/metadata.ts
packages/grpc-native-core/index.d.ts
packages/grpc-native-core/src/metadata.js

I'm using the latest version of grpc-native-core client and in my use case, the default behavior of `waitForReady` for RPC is `false`, but the annotations tell us the default is `true`. After digging into the source codes, as well as https://github.com/grpc/grpc-node/pull/899 and https://github.com/grpc/grpc-node/issues/896 , the default value should probably be the `false`. This ps is going to change the relevant annotations, both in grpc-native-core and grpc-js packages.
Signed-off-by: imjoey <majunjiev@gmail.com>

doc: Change the default value of waitForReady argument

---

packages/grpc-js/package.json

I have been convinced that it's worth publishing #1088 now rather than waiting and folding it into a bigger release. This release will also include the round robin load balancer implementation in #1063. The only API change there is a newly supported key in the channel options object.

Bump grpc-js to 0.6.10

---

gulpfile.ts

This may fix the issues with lock files that have been causing MacOS test failures.

Perform all npm operations sequentially

---

packages/proto-loader/package.json
packages/proto-loader/src/index.ts

I think there's a good chance that this fixes the memory leak reported in #1085.

proto-loader: Pass file descriptors around instead of caching them separately

---

packages/grpc-js/src/subchannel.ts

This implements the following paragraph of the [basic keepalive spec](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#basic-keepalive):
> When a client receives a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings", it should log the occurrence at a log level that is enabled by default and double the configure KEEPALIVE_TIME used for new connections on that channel.
The 'goaway' event arguments are described [here](https://nodejs.org/api/http2.html#http2_event_goaway)
The main goal here is to add the required logging, which may give us more information about what is causing #1158.
The previous behavior here is actually the same as in the core. See grpc/grpc#16210.

Handle 'too_many_pings' error from server

---

packages/grpc-js/package.json

It would be good to publish #1083 and #1164.

grpc-js: Bump to 0.6.11

---

packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/test/test-resolver.ts

Previously, it was calling `Object.keys` on a function which would never return the appropriate prefixes for registered resolvers and always fallback to the DNS resolver.
Fixes #1054

grpc-js: Change resolver to look at registeredResolvers when invoking getDefaultAuthority

---

packages/grpc-js/package.json

I recently needed to use a debugger with grpc-js and it would have helped to have these files to see what was happening in the original code.

grpc-js and proto-loader: Publish ts and map files

---

packages/grpc-js/src/channel.ts

This is what [the spec](https://github.com/grpc/proposal/blob/master/L32-node-channel-API.md) says that method should do. This part of the functionality got lost when the `Channel` class was rewritten in #1015.
This is probably what's causing googleapis/nodejs-pubsub#818.

Fix Channel#getConnectivityState API and behavior

---

packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/test/test-resolver.ts

Trying to connect to a Grpc server via an ipv6 address (e.g. `[::1]:58440`) fails with the following error:
```
internal/url.js:243
throw new ERR_INVALID_URL(input);
^
TypeError [ERR_INVALID_URL]: Invalid URL: http://::1:58440
at onParseError (internal/url.js:243:9)
at new URL (internal/url.js:319:5)
at Object.connect (internal/http2/core.js:2893:17)
at Object.connect (/Users/james/Development/ortoo/api-service/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-http2.js:119:33)
at Subchannel.startConnectingInternal (/Users/james/Development/ortoo/api-service/node_modules/@ortoo/infra-grpc-client/node_modules/@ortoo/grpc-utils/node_modules/@grpc/grpc-js/build/src/subchannel.js:183:31)
at Subchannel.transitionToState (/Users/james/Development/ortoo/api-service/node_modules/@orto …
```

grpc-js: fix explicit ipv6 addresses not resolving correctly

---

Documentation/compression.md
doc/compression.md

Adding compression documentation, I had spent some time to find the information is needed. I hope this will help others to start committing documentation too.
There are no server docs, since my server is on `Go` so I haven't explored that part.

(doc): add compression documentation part of #402

---

packages/grpc-js/src/index.ts
packages/grpc-native-core/src/credentials.js

Our upstream authentication library has gradually added more keys that provide meta-information to the upstream gRPC API.
We could not think of a reason why we were fetching only the `authorization` header, let's move away from this approach and simply populate all headers populated by `google-auth-library`.
CC: @murgatroid99, @alexander-fenster

feat: allow headers other than authorization

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts

This should always handle the error for #734.

grpc-js: Handle error when starting call on subchannel

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/subchannel.ts

This will hopefully help with debugging individual calls that behave badly. In several places it prints message length instead of message contents to make the logs hopefully easier to follow while still providing something to match up between different parts of the log.

grpc-js: Add low-level call tracers

---

test/interop/interop_client.js
test/package.json

Reverts grpc/grpc-node#1206. Apparently it broke the cloud-to-prod interop tests.

Revert "Update google-auth-library in interop tests"

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/tls-helpers.ts
packages/grpc-js/test/test-server-credentials.ts

This adds support for the `GRPC_SSL_CIPHER_SUITES` and `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` environment variables as documented [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md). After this the only unsupported environment variable that is relevant to this library will be `http_proxy`.
This should fix #804.

grpc-js: Add support for TLS-related environment variables

---

PACKAGE-COMPARISON.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts

Add some channel args that don't need significant plumbing to implement. Also update some outdated information in the package comparison doc.

grpc-js: Add more channel args

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts

This number is tracked in the channel file so that the channel can log that ID number when creating a call, linking the call number with the channel target and the method name. This change should make it easy to filter on the ID and see the entire lifetime of any single call.

grpc-js: Add unique ID number to call trace logs

---

packages/grpc-tools/src/node_plugin.cc

This fixes the "Plugin output is unparseable" error when using the `generate_package_definition` flag in grpc-tools. I got the error message when running in macOS and linux. After removing the `printf` the plugin would complete successfully with the `generate_package_definition` flag.

grpc-tools: fix output is unparseable error

---

packages/grpc-native-core/src/metadata.js

The idea here is that if anyone ever reports this message, it implies that the issue in #1173 is on the server side, because we would have seen the same error from two entirely independent http2 (and grpc) implementations.

Native: Add log for malformed incoming metadata

---

packages/grpc-tools/src/node_generator.cc

This should fix #1204 by preventing the printer from trying to interpolate variables whenever the `$` character appears in comments.

grpc-tools: Use PrintRaw when outputting comments

---

packages/grpc-native-core/package.json
packages/grpc-native-core/templates/binding.gyp.template
packages/grpc-native-core/templates/package.json.template

Updated `grpc-native-core` project templates to add abseil targets properly.
Related to https://github.com/grpc/grpc/pull/20184.

Add absl support

---

packages/grpc-js/src/metadata.ts
test/api/connectivity_test.js

This is tests from #796 and #899, but for both implementations. This should reproduce the same conditions as described in #1228.
This revealed a bug in the grpc-js implementation, so the fix for that is here too.

Add test for waitForReady on both implementations

---

packages/grpc-js/src/call-stream.ts

This should ensure that if a call ends as a result of a client-side error, e.g. when parsing or filtering incoming metadata, the information that the call has ended propagates back to the server. I don't actually know if this fixes any real problems, but I think the code is more correct with this line than without it.

grpc-js: Destroy http2 stream when a call ends in any way

---

packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server-credentials.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/tls-helpers.ts
packages/grpc-js/test/test-resolver.ts

This creates a new interface `SubchannelAddress` that can separately represent network socket names and IPC socket names, in order to properly support UDS. This new interface is used instead of strings everywhere internally when representing subchannel addresses.
This should fix the problems described in https://github.com/grpc/grpc-node/issues/258#issuecomment-579437170.
The second commit is all lint fixes, including some on otherwise untouched parts of the code. The first commit has all of the substantial changes.

grpc-js: Use an object to represent subchannel addresses

---

packages/grpc-js/src/channel.ts

The first few lines of this change are just formatting fixes. The relevant parts are the `tryPick` changes. This fixes #1250 (see my comment in the issue linked from that issue).

grpc-js: Different handling for errors when starting streams

---

packages/grpc-native-core/tools/run_tests/artifacts/build_one_artifact.bat

I guess I copied and pasted some code from inside a loop in the older script, and forgot to change the variables it was referring to.

Use correct environment variables in new windows build script

---

packages/grpc-native-core/src/client_interceptors.js

Cancel requester description in `client_interceptors.js` does not match with `CancelRequester` typing.
It might be confusing for someone who wants to write such an interceptor.

Message parameter removing from cancel requester description

---

packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/subchannel.ts

This fixes the tracer in the pick first load balancer that outputs the list of addresses to properly stringify them. It also adds a tracer that shows the original error when an http2 session fails, and adds a couple of trace lines to the the round robin load balancer that are the same as in the pick first load balancer.

grpc-js: Fix a trace line, and add a few new ones

---

packages/grpc-js/src/server.ts
packages/grpc-native-core/src/server.js

This should make client error logs more informative, and help with debugging some kinds of UNIMPLEMENTED errors.
This PR makes the same change to both implementations

Include method name in UNIMPLEMENTED details string

---

packages/grpc-js/src/channel.ts

This mainly adds a few trace lines to the `tryPick` function. I suspect that googleapis/nodejs-pubsub#890 was somehow caused by #1251, so I'm hoping that these logs can help track that down.

grpc-js: Add pick tracing and one error handler

---

packages/grpc-js/src/call-credentials-filter.ts

In the metadata, if the "authorization" header has multiple values, it will be rejected by the http2 library (see e.g. #894). We want to detect this early and report an error so that we don't get into a retry loop when the http2 library fails to start a stream. We shouldn't just arbitrarily use one of the values because this error indicates either a user error, which the user needs to know about, or a library error, which we need to know about.

grpc-js: Detect and error on multiple auth headers

---

packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/subchannel.ts

The implementation here is based pretty closely on the corresponding core code in https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc. The code for establishing the connection is loosely based on [this section of the `tunnel-agent` package](https://github.com/request/tunnel-agent/blob/master/index.js#L117-L182), which is used by the `request` package for establishing HTTP CONNECT tunnels.
With this change the library handles the environment variables `grpc_proxy`, `https_proxy`, `http_proxy`, `no_grpc_proxy`, and `no_proxy`.
I am considering this an experimental feature for now because I am not familiar with environments with those kinds of proxies and I don't know how to test it.

grpc-js: Add HTTP CONNECT support, i.e. egress proxy support

---

packages/grpc-js/src/channel.ts

The automatic retry code was originally added to handle the "New streams cannot be created after receiving a GOAWAY" error. To avoid another retry loop (googleapis/nodejs-pubsub#890), we should only retry on errors that are related to the http2 session's connectivity state, and so far, that is the only known error like that.
That error code string comes from https://github.com/nodejs/help/issues/2105#issuecomment-568470595.

grpc-js: Only automatically retry picks on known error

---

packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/test/test-resolver.ts

With the new representation of addresses from #1245, I think that we will no longer be impacted by the bug that prevented us from using IPv6 addresses on older Node versions.

grpc-js: Always return IPv6 addresses from DNS resolver

---

packages/grpc-js/src/server-call.ts

I expect that this will fix #1279. We shouldn't be trying to send trailers (or anything) over a stream that is in some kind of error state.

grpc-js: server calls: Don't try to send an error on stream error

---

packages/grpc-js/test/test-resolver.ts

This should fix #1289. I think this is the right way to move forward until changes can be made to Node itself to allow us to get AAAA records more consistently using `dns.lookup`.

grpc-js: tests: skip checking for IPv6 addresses from DNS servers

---

packages/grpc-js/src/server.ts
packages/grpc-native-core/src/server.js

Also, have bindAsync report a port number of 0 on error, and in the other implementation, treat 0 as an error. This should also make UDS servers work.

grpc-js: Use resolver to bind server ports

---

packages/grpc-js/src/call.ts
packages/grpc-js/src/client.ts

This is an implementation of #557 for grpc-js. We need this for grpc-gcp. I had to weaken some of the type constraints to make this work; I think that was unavoidable.

grpc-js: Add callInvocationTransformer option

---

packages/proto-loader/src/index.ts

This fixes #1298. I'm not changing any behavior, just adding an informative warning.

proto-loader: Warn if file not found in imports

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/client.ts
packages/grpc-js/src/index.ts

This includes these changes:
- Export a few types that are helpful in using some APIs
- Fix the parent call option type
- Update the channel interface to match the original proposal
- Add some runtime type checks because grpc-gcp tests for those and the code won't work correctly anyway if they're wrong.
I successfully built and tested a modified grpc-gcp with these changes.

grpc-js: Update some types and type checks for compatibility with grpc-gcp

---

packages/grpc-js/package.json
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/test-resolver.ts

This change makes the DNS resolver return a `null` service config if it gets the addresses before the TXT record, and then update the service config later if and when it gets one.
Currently the service config is only used to set which load balancing policy is used, so the most significant possible functional impact from this change is that the a client that is supposed to use round robin will send all requests to one address for a few seconds before switching to round robin. And round robin will start sending requests to the first address that connects anyway.
Also, I put IPv6 addresses before IPv4 in the merge call on purpose. It was always supposed to be that way.

grpc-js: Don't wait for TXT record to return DNS lookup result

---

packages/grpc-js/src/subchannel.ts

The purpose of the backoff timer is to enforce a minimum time between connection attempts. Transitioning from from CONNECTING to IDLE does not serve that purpose. I think that we can trust that Node will eventually time out connection attempts on its own, and that will result in a proper transition to TRANSIENT_FAILURE.
The reason I want to do this is to fix the problem described in https://github.com/grpc/grpc-node/pull/1322#issuecomment-606237127.

grpc-js: Don't time out connection attempts

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/compression-filter.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/subchannel.ts

This changes a few headers:
- `:authority` now includes the port number if it was specified in the channel target
- `accept-encoding: identity, gzip` is now sent
- `grpc-encoding: identity` is now omitted
I also added more detailed header tracing. For technical reasons the initial client header trace does not have a call number. We can plumb that through later but for now this is better than nothing.
I also added separate explicit tracing for receiving status code and details in the trailing metadata. Technically it's redundant with the trailing metadata tracing but I think it's easier to see when traced separately like that.

grpc-js: Make some headers conform to what the other library does

---

packages/grpc-js/package.json
packages/grpc-js/src/http_proxy.ts

It turns out that `http.STATUS_CODES` does not actually map status code names to status code numbers as I thought.
I also upgraded the verbosity of some logs so that if one of the environment variables is set and the proxy cannot be used, the user should always see at least one error log.

grpc-js: Fix status check when connecting to proxy

---

packages/grpc-js/src/index.ts
packages/grpc-js/src/make-client.ts

I tried to use the @grpc/grpc-js package with typescript definitions generated by [grpc_tools_node_protoc_ts](https://github.com/agreatfool/grpc_tools_node_protoc_ts). But the miss export of type `MethodDefinition` (which is exported in [native-core's index.d.ts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts)) made it impossible. Also I adjusted the ServiceDefinition. 
This will also help to for #931
Export `MethodDefinition` in index.ts and add generic `ImplementationType`
to `ServiceDefinition`.

grpc-js: adjust ts definitions to equal native-core

---

packages/grpc-js/src/resolver-dns.ts

#1341 was the only change from 0.7.6 to 0.7.7 and this looks like the only part of it that could reasonably explain #1347.

grpc-js: Don't include the port in :authority

---

packages/grpc-js/.eslintrc
packages/grpc-js/src/index.ts
packages/grpc-js/src/subchannel.ts

Apparently if you `import` your `package.json` file in a TypeScript project, the TypeScript compiler puts a copy of `package.json` into the `build` directory. And this apparently causes `npm` to not publish any `.js` files from that directory, completely breaking the package.
So, I'm putting it back to a `require` call and disabling the `gts` rule that told us to use `import` in the first place.
This fixes #1357.

grpc-js: Fix how package.json is loaded

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/subchannel.ts

This makes grpc-js handle proxies the same way the C core library does: the proxy address is treated as the channel target for name resolution and creating subchannels, and the original target is stored in a channel option until it is needed when the subchannel establishes a connection.
In `http_proxy.ts`, `mapProxyName` corresponds to [`HttpProxyMapper::MapName`](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc#L100) and `getProxiedConnection` corresponds to [`HttpConnectHandshaker::DoHandshake`](https://github.com/grpc/grpc/blob/433439bc77a796552f23e432cbcc46c30d75f6b5/src/core/ext/filters/client_channel/http_connect_handshaker.cc#L278).
Local testing on my own computer shows the proxy server responding with an error, but I have a feeling the …

grpc-js: Interact with proxies properly

---

packages/grpc-health-check/health.js

To use in serviceMap.
**Before**
```js
const grpcHealthCheck = require('grpc-health-check');
const grpcHealthCheckMessages = require('grpc-health-check/v1/health_pb');
const statusMap = {
'': grpcHealthCheckMessages.HealthCheckResponse.ServingStatus.SERVING,
};
const healthImpl = new grpcHealthCheck.Implementation(statusMap);
server.addService(grpcHealthCheck.service, healthImpl);
```
**After**
```js
const grpcHealthCheck = require('grpc-health-check');
const statusMap = {
'': grpcHealthCheck.messages.HealthCheckResponse.ServingStatus.SERVING,
};
const healthImpl = new grpcHealthCheck.Implementation(statusMap);
server.addService(grpcHealthCheck.service, healthImpl);
```

Export health-check messages

---

packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/subchannel.ts

Trying to get ssl connection to establish correctly when connecting via proxy.
In reference to https://github.com/grpc/grpc-node/issues/992

grpc-js: initiate tls connection through http proxy

---

packages/grpc-js/src/index.ts

InterceptorOptions extends CallOptions with the addition of method_definition property

grpc-js: export InterceptorOptions

---

packages/grpc-js/src/channel.ts
packages/grpc-js/test/test-client.ts

grpc-js: Client waitForReady callback fix.  Fixes #1352

---

packages/grpc-js/src/index.ts

grpc-js: Make request callback type match the other library

---

packages/grpc-js/src/channel.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/src/uri-parser.ts
packages/grpc-js/test/test-resolver.ts
packages/grpc-js/test/test-uri-parser.ts

This change is a result of a few things:
1. When working on the proxy code, I noticed that there were a few pieces of code that performed overlapping but not identical operations related to parsing targets/addresses.
2. #1359 was filed, and I realized that the easy fix would make the already unwieldy regexes in the DNS resolver even worse.
3. I found [the core URI parsing code](https://github.com/grpc/grpc/blob/53657b5de385ffc54e33899b3f2a87ff78d2952b/src/core/lib/uri/uri_parser.cc) and I realized that a structured representation of URIs could solve both problems.
The new `parseUri` function is based on [`grpc_uri_parse`](https://github.com/grpc/grpc/blob/53657b5de385ffc54e33899b3f2a87ff78d2952b/src/core/lib/uri/uri_parser.cc#L188), except that I don't handle query parameters or fragments …

grpc-js: Use a more structured representation of URIs internally

---

README.md
packages/grpc-js/README.md
packages/grpc-js/package.json

Bump grpc-js to 1.0 and stop calling it "beta"

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/server.ts
packages/grpc-js/test/test-resolver.ts
packages/grpc-js/test/test-uri-parser.ts

There were multiple issues here:
- We expect a proxy URL in the form `http://host:port`, but this does not actually fit with our naming scheme, so the URI parser parses it wrong. The solution is to revert to a previous version of `getProxyInfo` that parses the proxy address using the `URL` class.
- If the target had no scheme and was parsed weirdly into the `GrpcUri` structure, the resolver knew how to deal with that, but the proxy didn't, and it was making a bad request to the proxy. The solution is to stop using a default resolver, and instead modify the target at channel construction time so that it has a known scheme.
- The channel constructor was just overwriting the target after it got modified by the proxy.
- The proxy map result target didn't have an explicit scheme, even though …

grpc-js: Fix interactions between proxy code and new URI parsing

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/test/fixtures/test_service.proto
packages/grpc-js/test/test-server-errors.ts

`stream.write()` in server stream code is asynchronous for no apparent reason. As a result, it breaks the perfectly reasonable RPC implementation code like this one:
```js
stream.write(data);
stream.write(data);
stream.emit('error', err);
```
since `write` being `async` for no reason delays its execution and an error is emitted first within the same event loop.
Note that `grpc` server implementation works properly in this case.
We had this problem in [nodejs-spanner](https://github.com/googleapis/nodejs-spanner/blob/master/test/mockserver/mockspanner.ts#L499-L503) test code where they are using gRPC server to emulate some conditions for testing the client, and it blocks migrating this library from `grpc` to `@grpc/grpc-js`.

fix: make stream.write() synchronous in server-call

---

packages/grpc-js/package.json
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/subchannel.ts

There were a few more issues:
- `ChannelCredentials#_getConnectionOptions` was returning a reference to a mutable object, which `Subchannel#createSession` was mutating. I changed both of those lines for defense in depth.
- In `http_proxy.ts`, `getProxiedConnection` was resolving the promise before trying to connect with TLS. That is simply incorrect, and was probably a merge error.
- Again in `getProxiedConnection`, `tls.connect` did not always get a `servername` option, which is required to set the SNI request in the TLS handshake. With that change, adding the original `connectionOptions` needs to be moved to the end so that the `servername` option from the `grpc.ssl_target_name_override` channel option takes precedence.
I tested this by successfully making a request to the prod interop …

grpc-js: Fix the final proxy bugs

---

packages/grpc-js/src/channel.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-load-balancer.ts

I'm attempting to debug a random "failed to parse server response" error and this is what i'm seeing in my logs (note the `[object Object]`):
```
2020-04-23T06:13:06.747Z | dns_resolver | Resolved addresses for target [object Object]: [::1:57426,127.0.0.1:57426]
2020-04-23T06:13:06.747Z | pick_first | IDLE -> IDLE
2020-04-23T06:13:06.748Z | resolving_load_balancer | [object Object] CONNECTING -> IDLE
2020-04-23T06:13:06.748Z | connectivity_state | [object Object] CONNECTING -> IDLE
2020-04-23T06:13:06.748Z | dns_resolver | Resolution update requested for target [object Object]
2020-04-23T06:13:06.748Z | resolving_load_balancer | [object Object] IDLE -> CONNECTING
2020-04-23T06:13:06.748Z | connectivity_state | [object Object] IDLE -> CONNECTING
2020-04-23T06:13:06.748Z | …
```

grpc-js: fix target in tracing logs

---

packages/grpc-js/src/call-stream.ts

I think that with the existing code, `destroyHttp2Stream` may be triggering the underlying `close` event, which in turn calls `endCall` again before the first one completes, resulting in the wrong status taking precedence.

grpc-js: don't destroyHttp2Stream before saving the status code

---

packages/grpc-js/src/call-stream.ts

If the `Channel` API is used directly, it is possible for a call to end without `start` ever being called, so `this.listener` will be unset. In that case we might as well drop the event on the floor, because there's nothing waiting for it. This probably only impacts `onReceiveStatus` because the others require receiving something from the server, but the same change is valid for all of them.

grpc-js: Don't try to call listener if it is unset

---

packages/grpc-js/package.json
packages/grpc-js/src/call-credentials.ts
packages/grpc-js/src/channel-credentials.ts
packages/grpc-js/src/index.ts

`grpc-js` now depends on `google-auth-library`. I moved the `createFromGoogleCredential` function into the `CallCredentials` class so that it could be more easily accessed from `channel-credentials.ts`, and I changed the `OAuth2Client` type definition slightly to match what actually comes from `google-auth-library`; the only change is that it requires at least one of the specified functions, instead of both of them. The only change to `createFromGoogleCredential` is to replace `if (typeof googleCredentials.getRequestHeaders === 'function')` with `if (isCurrentOauth2Client(googleCredentials))`.
`createGoogleDefaultCredentials` is currently private because it hasn't gone through any API review, but it could easily be turned into `ChannelCredentials.createGoogleDefault` or something to make …

grpc-js: Add internal "Google default" channel credentials

---

packages/grpc-native-core/package.json
packages/grpc-tools/package.json

node-pre-gyp [doesn't recommend](https://www.npmjs.com/package/node-pre-gyp#1-add-new-entries-to-your-packagejson) using bundledDependencies anymore:
> Note: in the past we recommended putting node-pre-gyp in the bundledDependencies, but we no longer recommend this. In the past there were npm bugs (with node versions 0.10.x) that could lead to node-pre-gyp not being available at the right time during install (unless we bundled). This should no longer be the case. Also, for a time we recommended using "preinstall": "npm install node-pre-gyp" as an alternative method to avoid needing to bundle. But this did not behave predictably across all npm versions - see https://github.com/mapbox/node-pre-gyp/issues/260 for the details. So we do not recommend using preinstall to install node-pre-gyp. …

Don't use bundledDependencies

---

packages/grpc-js/package.json
packages/proto-loader/package.json

We're calling that in our tests, and we need to test on Node 8, and `gts` now throws if you call it from Node 8. This is just making the script explicitly do what `gts clean` does.

Don't use gts clean in npm clean to avoid errors on Node 8

---

packages/grpc-tools/src/node_generator.cc
packages/grpc-tools/src/node_generator.h
packages/grpc-tools/src/node_plugin.cc

This is a minor change to use the pure JavaScript gRPC Client `@grpc/grpc-js` instead of the (now deprecated) `grpc` node package when generating javascript files using the proto compiler. This change is very similar to the `generate_package_definition` param.
Reasoning: 
I understand that it's recommended to use `@grpc/proto-loader` to the load protos files. 
I have some hesitation to adopt this approach, as when using TypeScript, I have to typecast using [type assertions](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) to type the grpc client as a [`ServiceClientConstructor`](https://github.com/grpc/grpc-node/blob/4ec023c271890a0f8ecb2548ba2001357ae31c79/packages/grpc-js/src/make-client.ts#L87-L94), for example:
```ts
const echoService = …
```

grpc-tools: add grpc_js param to grpc_out

---

packages/grpc-native-core/deps/grpc/tools/run_tests/interop/with_nvm.sh

The interop scripts in the grpc/grpc repo reference that file at this path. This is the simplest solution to make the interop tests work again.

Copy a file that was previously in the grpc submodule

---

packages/grpc-js/src/client-interceptors.ts

Specify what is getting (de)serialized, and include the original error message, e.g. from Protobuf.js.

grpc-js: Add more detailed information to client (de)serialization errors

---

packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts

Trace what ports the server binds, what requests the server receives, and what status it ends each call with. Currently, if the call is cancelled, that doesn't get logged, because logging it properly is a little tricky.
The first commit has the substantive changes. The rest is cleanup from the formatter.

grpc-js: Add a few trace lines to the server

---

packages/grpc-js/src/metadata.ts
packages/grpc-js/test/test-metadata.ts

According to #1412 the current grpc-js behavior is different from the other implementation's behavior, so we should change it.

grpc-js: Don't split header values by commas

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/test/test-client.ts

This fixes #1411 (specifically, the new line 170 and 171 of `load-balancer-pick-first.ts` fixes that)
Also stop reporting IDLE on LB creation. That was causing pointless state change churn.

grpc-js: Fix pick_first handling of IDLE subchannels.

---

packages/grpc-tools/README.md
packages/grpc-tools/build_binaries.ps1
packages/grpc-tools/package.json

To publish #1370, #1371, and #1380.

Bump grpc-tools to 1.9.0 and add a README

---

PACKAGE-COMPARISON.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/http_proxy.ts

Fixes https://github.com/grpc/grpc-node/issues/1453
This change adds support for the [`grpc.enable_http_proxy`](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#gaa3f69f6e1e789e36d2d9c6083fec0257) channel option.

grpc-js: Add support for grpc.enable_http_proxy channel option

---

packages/grpc-js/package.json

This fixes #1442. The code path that calls into `google-auth-library` can't actually be triggered from the current public APIs, so if someone doesn't have the peer dependency they'll be fine. Firebase depends on `google-gax` 1.x, which depends on `google-auth-library` 5.x, and other client libraries depend on `google-gax` 2.x, which depends on `google-auth-library` 6.x. The peer dependency will be satisfied in either case.
We also need to add the dev dependency because we need it at build time for the type definitions.
Once the xDS stuff is done (or we want to create a `credentials.createGoogleDefault` public API) and that code path can actually be triggered, we should switch back to a direct dependency on `google-auth-library` 5.x to ensure that we still support Node 8. Hopefully we can …

Move google-auth-library to a peer dependency

---

packages/grpc-js/src/subchannel.ts

The comment that was previously there is wrong: we don't want to reset the backoff here. If we're in the case where we want to back off, i.e. the application indicates that it wants to keep trying to connect, and we keep failing to connect, the state transition sequence looks like this:
1. IDLE -> CONNECTING (start connecting)
2. CONNECTING -> TRANSIENT_FAILURE (fail to connect)
3. TRANSIENT_FAILURE -> IDLE (backoff timer ends)
4. IDLE -> CONNECTING (the queue picker from step 3 kicks the subchannel out of IDLE)
5. ...
The previous code resets the backoff timeout in step 3 of that sequence, which is exactly what we don't want to happen. The backoff timeout should only be reset when transitioning to READY, and that is handled already on line 490.

grpc-js: Properly back off when transitioning through IDLE

---

packages/grpc-js/src/subchannel.ts

If the backoff timer ends before the connection attempt fails, the subchannel needs to transition into TRANSIENT_FAILURE briefly to signal to the channel that the connection attempt failed, but then it needs to transition out of TRANSIENT_FAILURE to be able to try to connect again.
This fixes #1434.

grpc-js: transition out of TRANSIENT_FAILURE if backoff timer has ended

---

packages/grpc-js/src/call-stream.ts

Possible fix for googleapis/gax-nodejs#826

grpc-js: Don't push messages after ending a call

---

packages/grpc-js/package.json

This release will include #1406, #1436, #1443, #1444 and #1446.

Bump grpc-js to 1.0.5

---

.github/workflows/build.yml
packages/grpc-native-core/README.md
packages/grpc-native-core/package.json
packages/grpc-native-core/src/metadata.js
packages/grpc-tools/package.json
tools/release/alpine_artifact/Dockerfile
tools/release/cross/Dockerfile
tools/release/native/Dockerfile

Cherry pick #1371 and #1224, add the new versions of Node and Electron to the build matrix, and bump the version.

grpc 1.24 updates from master

---

packages/grpc-js/src/index.ts

We have a wrapper around the base Client, and being able to annotate with this type helps it be a bit more seamless

feat(client): export `ClientOptions` type

---

packages/grpc-js/src/server-call.ts

addresses: https://github.com/googleapis/nodejs-logging-winston/issues/414
this fixes an issue with open handles when running tests with jest. the timeout is created on import of this file and not cleaned up.
at a glance, i couldn't tell if a singleton was necessary, so this could be solved by just creating a separate timer for each stream, but figured this was closer to the current implementation.
a singleton still has issues if people are creating a server in their tests, but figure this will be rare compared to people just importing grpc-js for client usages

grpc-js: clear noop server call deadline

---

packages/grpc-js/src/subchannel.ts

grpc-js: Consistently set servername connection option to support SNI

---

packages/grpc-js/src/server.ts

As currently written, the `sessions` field tracks every HTTP/2 session that has ever been established with the server, which can grow without bound. If we remove the ones that are closed, it should be bounded by network connection limits. The check for `session.closed` in `tryShutdown` should avoid potential race conditions, where we get to that line and the `close` event is pending but has not fired yet.
I think this will fix #1458.

grpc-js: server: cull closed sessions from list, check for closed in tryShutdown

---

packages/grpc-js/src/constants.ts
packages/grpc-js/src/index.ts

grpc-js: Export propagate constants for type parity with grpc

---

packages/grpc-js/src/call-credentials-filter.ts
packages/grpc-js/src/resolver-dns.ts

Experimentally, this behavior matches the behavior of `grpc`. This fixes #1475, and I'm pretty sure it will avoid a regression of #1347.

grpc-js: Add port to :authority, leave it out of service_url

---

packages/grpc-tools/package.json

node-pre-gyp 0.12.0 uses needle 2.4.1 which has the bug in it.
Even with grpc 1.24.3, which refers to the updated version, it seems npm can decide to use the older version referenced by this package.

Update node-pre-gyp to pickup fix for #1362

---

packages/grpc-js/src/client.ts
test/api/interop_extra_test.js
test/interop/async_delay_queue.js

It turns out that the `Readable` stream class will aggressively call `_read` even if `push` returns `true`, so we don't also need to start another read after pushing. This fixes #1473, at least according to the test case provided in that issue.

grpc-js: Don't initiate a read after receiving a message

---

test/api/interop_extra_test.js

This was accidentally included in a commit in #1479.

Remove 'only' that was left over from test fixes

---

packages/grpc-js/package.json

This release includes #1459, #1465, #1463, #1433, #1449, #1466, #1467, #1468, #1478, and #1479. I think those are all valid patch-level changes; the minor version bump is mainly to ensure that it goes through testing before getting picked up by `google-gax`, to validate that #1478 doesn't cause a regression of #1347.

grpc-js: bump to 1.1.0

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

This was a bad interaction between #1466 and #1478. SNI is just supposed to use the hostname, not the full `host:port` string.

Omit port number from servername option

---

packages/grpc-js/package.json

I have been convinced by the discussion on #1443 that having this `peerDependencies` entry is not beneficial, and is sometimes detrimental.

grpc-js: Remove peerDependency on google-auth-library

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/subchannel.ts

There are a few different error handling-related changes here:
1. Update the error message "Received RST_STREAM with code 2" to add the string "Internal server error". We have seen several reports of people seeing the original error message and not understanding it.
2. Add trace logs for GOAWAYs. Node's http2 internals seem to automatically translate GOAWAYs to RST_STREAMs on streams still open in that session. Logging this will help distinguish between real RST_STREAM errors and GOAWAYs.
3. Transition a subchannel to TRANSIENT_FAILURE whenever its session fails to create a stream. This addresses a failure reported at https://github.com/googleapis/nodejs-firestore/issues/1023#issuecomment-653204096 where an error is thrown from `session.request` with the code `ERR_HTTP2_GOAWAY_SESSION`, …

grpc-js: Improve error handling in a few places

---

packages/proto-loader/package.json
packages/proto-loader/src/index.ts
packages/proto-loader/test_protos/well_known.proto

Protobuf.js provides both the `google/protobuf/*.proto` files that it doesn't load into `common` itself, along with the JSON generated files for those `.proto` files. It turns out that those JSON files have exactly the format that can be loaded into `common`, and `require` can load JSON files directly, so we can load these files without using `require.resolve` at all. I replaced the loop with constant strings so that a tool like webpack that needs to manipulate `require` calls would be able to understand it.
This should fix #969.

Load google/protobuf/* into common using require

---

packages/proto-loader/package.json

This is the same change as in #1500 because that branch was deleted.

Fix @types/mocha compatibility issue

---

packages/grpc-tools/CMakeLists.txt
packages/grpc-tools/package.json

This is apparently what is needed to fix #1484.

grpc-tools: Add compiler flag to fix error on Mac

---

packages/grpc-js/src/load-balancer-eds.ts
packages/grpc-js/src/load-balancing-config.ts

This is implemented on top of #1489. The changes for this PR are the last 2 commits, and they affect the files `load-balancer-eds.ts` and `load-balancing-config.ts`.

grpc-js: Implement EDS load balancer

---

packages/grpc-js/package.json
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolving-load-balancer.ts

This should fix #1510 by changing how TXT record lookup failures are handled. Specifically, now no action is taken when that happens.
I also updated the config handling codepath to address updates that have been made to [the spec](https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md) since this implementation was originally written. In addition to that, I simplified the logic somewhat to more consistently fall back to using the default service config when we do not retrieve one.

grpc-js: Fix handling of unsuccessful TXT record lookups

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/generated/envoy/api/v2/endpoint/ClusterStats.ts
packages/grpc-js/src/generated/envoy/api/v2/endpoint/EndpointLoadMetricStats.ts
packages/grpc-js/src/generated/envoy/api/v2/endpoint/UpstreamEndpointStats.ts
packages/grpc-js/src/generated/envoy/api/v2/endpoint/UpstreamLocalityStats.ts
packages/grpc-js/src/generated/envoy/service/load_stats/v2/LoadReportingService.ts
packages/grpc-js/src/generated/envoy/service/load_stats/v2/LoadStatsRequest.ts
packages/grpc-js/src/generated/envoy/service/load_stats/v2/LoadStatsResponse.ts
packages/grpc-js/src/generated/lrs.ts
packages/grpc-js/src/load-balancer-eds.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/xds-client.ts

The code in `src/generated` is new generated code for the `LoadReportingService`, which is used here and in the upcoming `LrsLoadBalancer`.

grpc-js: xDS: add support for dropping calls and reporting drops

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/generated/envoy/api/v2/ScopedRouteConfiguration.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/HttpConnectionManager.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/HttpFilter.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/Rds.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/RequestIDExtension.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/ScopedRds.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/ScopedRouteConfigurationsList.ts
packages/grpc-js/src/generated/envoy/config/filter/network/http_connection_manager/v2/ScopedRoutes.ts
packages/grpc-js/src/generated/envoy/config/trace/v2/Tracing.ts
packages/grpc-js/src/generated/google/protobuf/MethodOptions.ts
packages/grpc-js/src/generated/http_connection_manager.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver-xds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/xds-client.ts
packages/grpc-js/test/test-resolver.ts

This is the final major PR in the implementation of [gRFC A27: xDS-Based Global Load Balancing](https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md). This PR adds the `XdsResolver` class that handles `xds://address` target names using an `XdsClient` and emits service config objects that configure the load balancer classes created in the other classes.
This PR purposely does not call the `setup` function in `xds-resolver.ts`. That function call will enable the global load balancing feature; it will be added after the feature is sufficiently tested.
All of the new code in `src/generated` is there to handle deserializing the `HttpConnectionManager` message from a `google.protobuf.Any` field on lines 720 and 755 of `xds-client.ts`.

grpc-js: Add XdsResolver and corresponding XdsClient behavior

---

packages/grpc-js/src/xds-client.ts

I refactored the `XdsClient` class to move the logic for each message type in the ADS stream into its own class. The remaining ADS logic in the `XdsClient` class itself is generic with respect to the different message types.
I also noticed when I was doing this that the `onResourceDoesNotExist` watcher methods were not getting called so I added those too.

grpc-js: Refactor the XdsClient class

---

packages/grpc-js/README.md

- Adds a link to `grpc` documentation
- Addresses some of the concerns in #1540

Add link to grpc docs in @grpc/grpc-js README

---

packages/grpc-js/package.json

I don't remember why we omitted this before, but the published types depend on the stream classes and `EventEmitter` from the `@types/node` package so we should have a production dependency on that for people trying to compile TypeScript code against grpc-js. This rarely causes problems because people often have their own dependency on `@types/node` to be able to use any Node builtins, but occasionally, as in #1538, they have a version of the types package that is incompatible with grpc-js and it causes compilation errors. We can't actually avoid that entirely because TypeScript's package resolution algorithm violates some assumptions that npm's package layout algorithm makes, but this is the best thing we can do to minimize the chance of that error.
The `@types/node` package is the only …

grpc-js: Move @types/node to a production dependency

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/call.ts
packages/grpc-js/src/server-call.ts

Also, always return "unknown" when it doesn't have a better answer, for consistency with the core's behavior. This fixes #1483, in the sense that it provides the requested functionality in an existing method that previously threw a "not yet implemented" Error.

grpc-js: Implement getPeer on the client and server

---

packages/grpc-js/src/server-call.ts

grpc-js: Add end(md?: Metadata) method to streaming server calls

---

packages/grpc-js/src/server-call.ts

Right now, the `defaultResponseHeaders` global is mutated on every request. This is a **huge** security vulnerability if there's any auth data in the metadata.

Prevent mutation of default headers

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts

The main functional change here is calling `listener.onReceiveStatus` in `process.nextTick` in `call-stream.ts` so that the call stream cleanup code can finish before the status can bubble up to the surface API and result in an error being thrown. In particular, this means that the client will properly `close` the underlying http2 stream, so this is a fix for #1523.
The rest of the PR is adding and fixing trace log output.

grpc-js: Clean up call even if status throws an error

---

packages/grpc-js/package.json

I had `google-auth-library` and `@grpc/proto-loader` in dev dependencies because the code that requires them at runtime was supposed to be unreachable but as #1550 shows, that's fragile. So I'm just moving them to production dependencies now so that won't happen.
This fixes #1550.

grpc-js: Move a couple of dev dependencies to prod

---

packages/grpc-js/src/channel.ts

Docs say they should work: https://grpc.github.io/grpc/node/grpc.html#~Deadline : "If it is a finite number, it is treated as a number of milliseconds since the Unix Epoch. If it is Infinity, the deadline will never be reached. If it is -Infinity, the deadline has already passed". Previously the Infinity case didn't work (was coerced into an invalid date, which ended up as a timeout of NaN, which is called ~immediately). 
(The `-Infinity` case sortof did work by accident since the callback being called immediately is basically the correct behaviour for that, but I've made it a bit more explicit)

Channel#watchConnectivityState: handle infinite deadlines correctly

---

packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/subchannel.ts

Latest version has caused @google-cloud/pubsub fail to connect over a proxy connection.
Snapshot of error:
2020-08-29T10:52:45.340Z | proxy | Successfully connected to pubsub.googleapis.c
om:443 through proxy 172.16.52.252:443
2020-08-29T10:52:45.370Z | subchannel | 172.16.52.252:443 CONNECTING -> TRANSIEN
T_FAILURE
2020-08-29T10:52:45.372Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
2020-08-29T10:52:45.373Z | resolving_load_balancer | dns:172.16.52.252:443 CONNE
CTING -> TRANSIENT_FAILURE
2020-08-29T10:52:45.375Z | channel | Pick result: TRANSIENT_FAILURE subchannel:
undefined status: 14 No connection established
2020-08-29T10:52:45.377Z | call_stream | [11] cancelWithStatus code: 14 details:
"No connection established"
2020-08-29T10:52:45.379Z | call_stream | [11] ended with status: …

Fixed connectivity to Google PubSub over proxy

---

packages/grpc-js/src/channel-options.ts

Remove index signature from ChannelOptions to fix intersection error
described in #1558 which causes issues on using ClientOptions direct
fields with TypeScript.
Removing of index signature required few minor changes:
- adding few constant types that were used throughout the app
- using `as const` assertion in xds-client
- using not-so-great type cast in channelOptionsEqual
Alternative solution would be removing the index signature from
ChannelOptions explicitly in ClientOptions definition, which is not
trivial and probably calls for a generic type helper.
See: https://github.com/grpc/grpc-node/issues/1558
Fixes: 1558

Fix ClientOptions types

---

packages/grpc-js/src/server-call.ts

When writing a small decorator for allowing developers write their code with throwing errors I stumbled upon an issue.
It looks like the grpc-js library overwrites the error code of an error being thrown even if `code` is present. An example is the following:
```ts
const streamHandlerDecorator = <RequestType, ResponseType>(
handler: (
sessionId: string,
stream: ServerWritableStream<RequestType, ResponseType>,
) => Promise<void>,
): ((
stream: ServerWritableStream<RequestType, ResponseType>,
) => Promise<void>) => async (
stream: ServerWritableStream<RequestType, ResponseType>,
): Promise<void> => {
try {
await handler(stream);
} catch (error) {
const maybeConvertedError =
error instanceof GrpcError
? error
: new GrpcError('An unknown error ocurred.', status.INTERNAL);
stream.emit('error', …
```

fix(grpc-js): preserve original error code when the handler of a readable stream throws an error

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

Adding support for `ImplementationType` to `server.addService(...)`.
It seems like the original (non-js) `grpc` type definitions support this - https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/index.d.ts#L266.
Not sure if there was a reason not to do it in grpc-js?
Thanks!

fix(grpc-js): Add support for impl type to server.addService

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

Reverts grpc/grpc-node#1556. That change broke #1552. Breakage error log: https://source.cloud.google.com/results/invocations/a9b120c7-c487-453a-82c8-0d29b91b73ce/targets/grpc%2Fnode%2Fpull_request%2Flinux/log

Revert "fix(grpc-js): Add support for impl type to server.addService"

---

packages/grpc-js/scripts/xds.sh

The script gets called with a relative path and it wasn't handling that correctly.

grpc-js: Fix path handling in xds interop script

---

test/kokoro/xds-interop.cfg

The test takes more than an hour to finish. The equivalent test job in grpc/grpc also uses a 2 hour timeout: https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_xds.cfg.

grpc-js: Double the xds test job timeout

---

packages/grpc-js/scripts/xds.sh

The test logs show that the Node xDS interop client can't load the `http2` module. The most likely explanation for that is that it is using an old version of Node. The main test log shows `nvm` installing correctly and using Node 12, so my guess is that we are encountering nvm-sh/nvm#1866. Based on [this post](https://unix.stackexchange.com/a/46856/9579), this change is my best guess for properly using the version of Node from `nvm` in the test client.

grpc-js: Source nvm.sh in profile files in xds script to get nvm in subprocesses

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts

This should fix #1579.
We want to hold the event loop open as long as there is an active call. For most of the lifetime of most calls, this is accomplished by `ref`ing each subchannel as long as it is handling at least one active call. However, that does not account for calls that are never attached to subchannels. This closes that gap by creating an interval timer that lasts for the lifetime of the channel. We `ref` that timer as long as there is at least one pending call on the channel that has not been assigned to a subchannel.

grpc-js: Add a timer that holds the event loop open while there are pending calls

---

test/api/interop_extra_test.js

This also consistently makes the requests sequentially instead of concurrently.

Fix the max message size tests by making the requests with different clients

---

packages/grpc-js/src/index.ts

This provides better compatibility with the legacy `grpc` package.

grpc-js: Export handleClientStreamingCall type

---

packages/grpc-js/src/load-balancer-cds.ts
packages/grpc-js/src/load-balancer-eds.ts

The `onResourceDoesNotExist` event is triggered in the CDS LB policy when a CDS update does not have the requested cluster name, and in the EDS LB policy when an EDS update does not have the requested cluster/service name, and when a CDS update does not have any resources with the requested name.
In the first two cases we do not want to remove the watcher because we want to know if the requested resource exists again later. In the last case, we do want to remove the watcher, but that update should also result in the EDS policy either getting removed or getting a new configuration with a new cluster/service name, and either of those events will cause the watcher to be removed or replaced.

grpc-js: xDS: Do not remove watchers in onResourceDoesNotExist

---

packages/grpc-js/src/xds-client.ts

This is an implementation of grpc/proposal#204

grpc-js: xDS: handle insecure and google_default bootstrap creds

---

packages/grpc-native-core/index.d.ts

To provide better type compatibility with `@grpc/grpc-js`. 
See https://github.com/grpc/grpc-node/issues/1581
Here's the `@grpc/grpc-js` type definition for ServerWritableStream:
https://github.com/grpc/grpc-node/blob/5e0feb5d74d266d435939dd750a091b44c91ff1e/packages/grpc-js/src/server-call.ts#L90-L93

Add ResponseType to ServerWritableStream

---

test/interop/interop_client.js
test/package.json

Version 0.9.x of the google-auth-library package was so old that it was using an old metadata server version that is no longer supported. The modifications here are mostly inferred based on the documentation. Hopefully they don't break anything.

tests: Update google-auth-library dependency from 0.9 to 6.1

---

packages/grpc-js/src/load-balancer-cds.ts
packages/grpc-js/src/load-balancer-eds.ts
packages/grpc-js/src/xds-client.ts

This is an attempt to track down the cause of a flaky test in the xDS interop tests. The flake appears to be related to a watcher spuriously being removed, which results in the corresponding LB policy thinking that resource has been removed.

grpc-js: xds: Add more logging around adding and removing eds and cds watchers

---

test/interop/interop_client.js

I accidentally removed this in #1596.

Fix missing arg variable in perRpcCreds interop test

---

packages/grpc-js/src/http_proxy.ts

Set the default port of 80 explicitly in http_proxy

---

packages/grpc-js/src/make-client.ts
packages/grpc-js/test/test-prototype-pollution.ts

This bug was reported to us in an email. The test is directly adapted from that report. There will be a similar PR for the other implementation.

grpc-js: Prevent prototype pollution in loadPackageDefinition

---

packages/grpc-native-core/index.js
packages/grpc-native-core/src/client.js
packages/grpc-native-core/test/prototype_pollution_test.js

This is the native library equivalent to #1605.

grpc: Prevent prototype pollution in loadPackageDefinition

---

packages/grpc-js/package.json
packages/grpc-js/src/http_proxy.ts

Backport #1609 to 1.1.x so that we can publish it more quickly.

Backport of "Set the default port of 80 explicitly in http_proxy" to 1.1.x

---

PACKAGE-COMPARISON.md
packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/subchannel.ts

This addresses the most pressing concern raised in #1593. With this change, if the arg is 1, we start keepalive pings when the connection is established. Otherwise, we start keepalive pings when a call is started using the subchannel, and end them when no active calls are using the subchannel. In both cases, we also stop the keepalive pings when the connection is dropped; that part is unchanged from the previous code.

grpc-js: Add support for grpc.keepalive_permit_without_calls channel arg

---

packages/grpc-native-core/ext/call.cc
packages/grpc-native-core/ext/slice.cc
packages/grpc-native-core/ext/slice.h

This should fix #1407, or at least the reproduction demonstrated in https://github.com/grpc/grpc-node/issues/1407#issuecomment-717170288. This change is needed because of change in Node 14 that prohibits multiple `Buffer` objects from pointing to the same underlying memory. That makes the previous zero-copy function error-prone in some situations.

Native: Copy slice data into Buffer when receiving binary metadata

---

packages/grpc-js/src/server.ts
packages/grpc-js/test/test-server.ts

This PR includes:
- removing the requirement of `Server#addService(...)` for non-started server
- adding `Server#unregister(...)` and `Server#removeService(...)` - the counterparts of `Server#register(...)` and `Server#addService`
workaround for https://github.com/grpc/grpc-node/issues/1547

grpc-js: support adding/removing services on started server

---

packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts
test/api/interop_extra_test.js
test/gulpfile.ts

This fixes #1533.
[Documentation for this option](https://nodejs.org/api/http2.html#http2_http2_connect_authority_options_listener):
> Sets the maximum allowed size for a serialized, compressed block of headers. Attempts to send headers that exceed this limit will result in a `'frameError'` event being emitted and the stream being closed and destroyed.

grpc-js: Allow clients and servers to send metadata of unlimited size

---

.github/workflows/build.yml
packages/grpc-native-core/README.md
packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json
packages/grpc-native-core/templates/binding.gyp.template
packages/grpc-native-core/templates/package.json.template

A couple of previous changes set the `package.json` file out of sync with the template and `build.yaml`, so I corrected that here.
Also add a note in the README specifying the latest version of Node and Electron that we support. We will only have to update that a few times before we stop updating the version support entirely.

Native: add new Node and Electron versions, bump version

---

packages/grpc-js/src/channel.ts

[The corresponding enum in the native library](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/constants.js#L260-L266). This fixes #1620.

grpc-js: Rearrange connectivity state enum to match the native library

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/client-interceptors.ts
packages/grpc-js/src/constants.ts
packages/grpc-js/src/server-call.ts
packages/grpc-js/test/test-call-propagation.ts

This addresses #1542. The tests I added here are pretty closely adapted from the equivalent tests in the native library: https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/test/surface_test.js#L1224-L1410.

grpc-js: Implement deadline and cancellation propagation

---

packages/grpc-js-xds/src/xds-client.ts

Since the client always reports metadata when reporting an error, receiving metadata is not a valid indication that we have successfully established a connect.

grpc-js-xds: Reset LRS backoff on data, not metadata

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

grpc-js: Make calls use the min of parent and own deadline when both are provided

---

packages/grpc-js-xds/package.json

It will really simplify documentation about which version of the library supports which feature if the two packages have the same version numbers, at least up to the minor version.

Make grpc-js and grpc-js-xds versions match

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js/package.json
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/test/test-resolver.ts

A channel that connects to an `xds:///` backend creates an internal client connected to an xDS server. Currently that client just always has an active call and holds the process open forever. This change makes it so that when that channel's `close` method is called, which calls its resolving load balancer's `destroy` method, that propagates to destroy the resolver, which then shuts down the xDS client, allowing the process to end.
*Technically*, this is a breaking change in the `experimental` namespace by adding an additional method to the `Resolver` interface that would need to be implemented by an implementing class. However, the real point of the `experimental` version compatibility guarantees is to avoid breaking grpc-js-xds, and since that's not out yet I don't consider it to be a …

grpc-js-xds: Shutdown the xDS client used by the resolver when the channel shuts down

---

packages/grpc-js/src/call-stream.ts

This should help us understand the causes of some of those errors.
The diff here is large because of an indentation change. The actual change to the `stream.on('close', ...)` handler moves the body into `process.nextTick` to delay processing until after the `error` event is handled, and adds a branch in the `INTERNAL` error case to handle error messages from the error event.

grpc-js: Propagate internal stream errors from the http2 module

---

packages/grpc-js/package.json
packages/grpc-js/src/deadline-filter.ts

This should fix #1636.
`process.nextTick` queues a function to be called in the current phase of the event loop, while `setTimeout` will wait until the timer handling phase. We still want to call `cancelWithStatus` asynchronously for consistency.

grpc-js: End calls faster if the deadline has already passed

---

packages/grpc-js/package.json
packages/grpc-js/src/load-balancer-round-robin.ts

This should fix #1663. When a connected subchannel gets a GOAWAY it transitions to IDLE, and as of #1073 the same is true of other kinds of disconnects. Those are supposed to be signals to the round robin balancer that it should do name resolution again, so that's what we do here.

grpc-js: round robin: re-resolve when subchannels go idle

---

packages/grpc-js/package.json
packages/grpc-js/src/client-interceptors.ts

The main fix here is to move the `onReceiveMessage` call out of the `try` block, because that function eventually calls `stream.push` or the equivalent unary handler function, and the result is that that function is called within the context of that `try` block and any errors it throws will be misinterpreted as response parsing errors.
This fixes #1661.

grpc-js: Move call to user code out of try block

---

packages/grpc-js/package.json

This fixes #1679. TypeScript does not do module resolution the same way Node does, and one result is that it reintroduces the diamond dependency problem to a system that does not otherwise have it. The solution here is to declare a dependency with a version range so broad that npm's package deduplication logic will always apply, or at least that the constraint here is never the one that prevents it from applying.
This change may cause build problems in the future if there are relevant breaking changes in `@types/node`, but the existing dependency is causing build problems now so I consider that an acceptable tradeoff.

grpc-js: Loosen dependency on @types/node

---

packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts

This is an implementation of the first part of [gRFC A31](https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md): the `ConfigSelector`. The purpose of this API is to enable the resolver to provide configuration information and especially routing information that can differ depending on the method and on the metadata. The resolver can return a `ConfigSelector` along with other name resolution information, and the `ResolvingLoadBalancer` passes that along to the channel. The channel calls it before before calling into the `Picker` that comes from the load balancer.
This change should not cause any observable behavior changes, it's just foundational.

grpc-js: Add ConfigSelector to Resolver API and plumb it through the channel

---

packages/grpc-js/src/channel.ts

Some users are seeing that error and it is hard to tell what is going wrong there.

grpc-js: Add more details to 'Failed to start HTTP/2 stream' error

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js/package.json
packages/grpc-js/src/backoff-timeout.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/subchannel.ts

We want the gRPC library to hold the Node process open if and only if there is an active request. The channel is responsible for this while a call has not yet been assigned to a subchannel, and the subchannel is responsible for this after the call has been assigned, until the call ends. In the subchannel, there is always either an http session, or an active backoff timer (or both). So, we ref both of those as long as the subchannel has at least one call. Since the resolving load balancer is never responsible for keeping the process open, we always unref its backoff timer. The same is true of the xDS client, which always operates as a subordinate of another channel.

grpc-js: Ref and unref backoff timer

---

packages/grpc-js/package.json
packages/grpc-js/src/call-credentials-filter.ts
packages/grpc-js/src/channel.ts

This has two complementary changes: in the channel, only propagate error codes from metadata filters if they are numbers, and in the call credentials filter, explicitly set the UNAUTHENTICATED error code instead of letting errors from the credentials plugin implicitly bubble up.
This should fix the reports from googleapis/nodejs-pubsub#1063 of the error code `ERR_OSSL_PEM_NO_START_LINE` getting propagated from a Node crypto module error.

grpc-js: Don't propagate non-numeric errors from auth plugins

---

packages/grpc-js-xds/src/index.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts

The logic of this class is pretty simple: it is configured with a map of names to child service configs, and it delegates all pick actions to the corresponding child load balancers based on the `cluster` string passed in the pick arguments. Most of the code is transparent delegation and connectivity state bookkeeping.
All of the logic is independent of xDS, but it is part of the xDS library for consistency with [the relevant section of gRFC A31](https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md#implementation-for-xds-routeaction-support).

grpc-js-xds: Add XdsClusterManager LB policy

---

packages/grpc-native-core/index.js
packages/grpc-native-core/package.json
packages/grpc-native-core/src/client.js
packages/grpc-native-core/src/common.js

This is a port of #1654 to the old grpc library.
Credit to @d3v53c for the original fix.

grpc: Fix prototype pollution possibility in loadPackageDefinition

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

A couple of people in googleapis/nodejs-firestore#1023 have reported calls ending with INTERNAL errors triggered by an underlying error that says "read ECONNRESET". Those should be reported as UNAVAILABLE. My guess is that Node is reporting these errors in the form of a [`SystemError`](https://nodejs.org/api/errors.html#errors_class_systemerror) with the code `ECONNRESET`. If that is the case, we can distinguish those errors and change the code. I also added some logging for the errors from Node to hopefully get a better idea of the error structure if this doesn't work.
If that information isn't actually available in a structured way in the error, we might have to fall back to parsing the error message but I really hope we can avoid that because those messages are supposed to be …

grpc-js: Speculative fix for ECONNRESET errors

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/load-balancer-eds.ts
packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts
test/kokoro/linux.cfg

The LRS load reporting server name is usually the empty string to indicate that the primary xDS server name should be used, but the empty string is falsey so this was taking the wrong branch and LRS was getting disabled when it should have been used.

grpc-js-xds: Fix handling of empty LRS server names

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/xds-client.ts

The issue here is that when a LRS stream was killed and then the client reestablished it, it would try sending any stats accumulated in the intervening time, but the settings would be `null`, including the settings for which stats to send.
I fixed this in two ways: First, ending the stream does not clear the settings, and cleared settings are no longer used as the primary signal to determine whether to start a timer when receiving new settings. Second, the code for sending stats checks whether the settings are there before trying to use them.

grpc-js-xds: Fix sending stats when reestablishing LRS stream

---

packages/grpc-js/src/channel.ts

`Channel#waitForReady` expects this error to be thrown (https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts#L178-L186). This is the same error that is thrown by `Channel#createCall` if the channel is closed.
This was discovered because of someone noting in https://github.com/googleapis/nodejs-pubsub/issues/1190#issuecomment-797580406 that the `watchConnectivityState` timer can keep the process running even after the channel is closed.

grpc-js: Throw in watchConnectivityState if channel is closed

---

packages/grpc-js/package.json
packages/grpc-js/src/backoff-timeout.ts

This fixes #1708. We actually ran into the same issue before in #1077 but I forgot when I implemented #1688.

grpc-js: Timer ref and unref might not exist

---

packages/grpc-tools/package.json

The previous version was 3.14.0. This notably enables default support for proto3 `optional` fields to fix #1717.

grpc-tools: Bump protobuf dependency to 3.15.6

---

packages/grpc-js-xds/interop/generated/grpc/testing/ClientConfigureRequest.ts
packages/grpc-js-xds/interop/generated/grpc/testing/ClientConfigureResponse.ts
packages/grpc-js-xds/interop/generated/grpc/testing/LoadBalancerAccumulatedStatsRequest.ts
packages/grpc-js-xds/interop/generated/grpc/testing/LoadBalancerAccumulatedStatsResponse.ts
packages/grpc-js-xds/interop/generated/grpc/testing/LoadBalancerStatsService.ts
packages/grpc-js-xds/interop/generated/grpc/testing/XdsUpdateClientConfigureService.ts
packages/grpc-js-xds/interop/generated/test.ts
packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/proto/grpc/testing/messages.proto
packages/grpc-js-xds/proto/grpc/testing/test.proto

This adds implementations of the `XdsUpdateClientConfigureService` service and the `GetClientAccumulatedStats` method in the `LoadBalancerStatsService`. The first of those in particular is needed to enable the `path_matching` and `header_matching` interop tests for testing those features.

grpc-js-xds: Add functionality to the xDS interop client

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/environment.ts
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-eds.ts
packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-client.ts
packages/grpc-js-xds/src/xds-stream-state/cds-state.ts
packages/grpc-js-xds/src/xds-stream-state/eds-state.ts
packages/grpc-js-xds/src/xds-stream-state/lds-state.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts
packages/grpc-js-xds/src/xds-stream-state/xds-stream-state.ts
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/experimental.ts
test/kokoro/linux.cfg

There are a few changes included in this PR:
- Refactor some helper classes out of `xds-client.ts` into the directory `xds-stream-state`
- Modify the `XdsClient` class to be a singleton shared by all channels. In particular, it no longer takes the resolver's `ServiceConfig` watcher in the constructor. Instead, the resolver now watches for LDS and RDS updates the same way the EDS and CDS load balancers watch for their corresponding updates.
- Add traffic splitting and routing logic to the xDS resolver class, enabled by the environment variable `GRPC_XDS_EXPERIMENTAL_ROUTING`. It creates a `ConfigSelector` as implemented in #1681 and an `XdsClusterManager` as implemented in #1687.

grpc-js-xds: Do traffic splitting and routing in the resolver

---

packages/grpc-js/package.json
packages/grpc-js/src/compression-filter.ts

It turns out that if the server sends gzip-encoded content, you have to actually do gzip decompression. grpc-js does not currently have that functionality, so putting `gzip` in the `accept-encoding` header is inaccurate. It can always be added again later.
This should fix #1719.

grpc-js: don't send accept-encoding: gzip

---

packages/grpc-tools/package.json
packages/grpc-tools/src/node_plugin.cc

The requirement for this change isn't documented anywhere, I just copied it from [the corresponding PR in the protobuf repo to enable the feature in the JS generator](https://github.com/protocolbuffers/protobuf/pull/7592/files#diff-a76a32283775a91e5c13baedb0617723fea7abf4295d302ecc4db8927720faeb). This fixes #1717. I manually tested it this time; it successfully handles fields that cause errors with the current version.

grpc-tools: make the plugin compatible with proto3 optional fields

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/load-balancer-eds.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js-xds/src/matcher.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/route-action.ts
packages/grpc-js-xds/src/xds-client.ts
test/kokoro/linux.cfg

These are the additional interop tests enabled by #1715.
This PR includes a major refactor of the matching and route action logic in the xDS resolver class, moving them into separate files and multiple classes. The main purpose was to improve the ability to log them for debugging, but that should also improve readability. The refactor also fixed a bug with how the safe regex header match configuration was handled.

Enable path_matching and header_matching xDS interop tests

---

packages/grpc-js/src/channel-options.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel.ts

Currently there is no way to set the parameter maxSessionMemory for http2.createServer() and http2.connect() options. In case when queued data at session is become more than default value there thrown exception.

feature(grpc-js): Add possibility to provide maxSessionMemory http2 option through ChannelOptions

---

packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/environment.ts
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/xds-stream-state/rds-state.ts

The environment variable protection for these features is only needed until the corresponding interop tests are passing. That was accomplished with #1724. (Hide whitespace changes).

grpc-js-xds: Remove env var protection for routing feature

---

packages/grpc-js/package.json
packages/grpc-js/src/index.ts

This is an alternative approach to #1693. With Node 8 being past EOL and Node 10 nearing the end of its maintenance window, the probability of a user using a version older than the supported version range is outweighed by the probability that a user will encounter the issue described in the linked PR with prerelease versions of Node.

grpc-js: Remove explicit version compatibility check

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/google/api/HttpRule.ts
packages/proto-loader/golden-generated/google/longrunning/Operation.ts
packages/proto-loader/golden-generated/google/longrunning/WaitOperationRequest.ts
packages/proto-loader/golden-generated/google/protobuf/DescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/EnumDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/EnumValueDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/FieldDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/FileDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/MethodDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/MethodOptions.ts
packages/proto-loader/golden-generated/google/protobuf/OneofDescriptorProto.ts
packages/proto-loader/golden-generated/google/protobuf/ServiceDescriptorProto.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/BlockRequest.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/EchoRequest.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/ExpandRequest.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/WaitMetadata.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/WaitRequest.ts

When the `defaults` option is set, message values that are not provided will be represented as `null` instead of being omitted from the object entirely. Those `null` values should not appear in maps or repeated fields.
This fixes #1741.

proto-loader: generator: allow for null message values

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/echo.ts
packages/proto-loader/golden-generated/google/longrunning/Operations.ts
packages/proto-loader/golden-generated/google/showcase/v1beta1/Echo.ts
packages/proto-loader/package.json
packages/proto-loader/src/index.ts

This fixes #1740. The type of the service definition attached to the generated client class needs to list the specific methods so that it can work with the type of the `addService` function in the native library.

proto-loader: generator: add specific service definition interfaces

---

packages/grpc-native-core/src/client_interceptors.js

instanceof Function does not work in different contexts, in this case the callback to the end of stream is not called, I am using it for [haraka](https://haraka.github.io/) plugin, similar to https://github.com/grpc/grpc-node/pull/204 and https://github.com/grpc/grpc-node/pull/795
Doing it similar to underscorejs.

grpc: stricter function check than instanceof

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json
packages/grpc-native-core/src/server.js
tools/release/cross/Dockerfile
tools/release/native/Dockerfile

grpc: Log (de)serialization errors specificially, instead of internal errors in general

---

packages/grpc-js/src/resolver-ip.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/test/test-resolver.ts

This adds support for the `ipv4` and `ipv6` schemes as described in the [naming doc](https://github.com/grpc/grpc/blob/master/doc/naming.md). These schemes support multiple addresses in a single target string, and uniquely, multiple different ports. This makes it much easier to meaningfully test the round_robin load balancing policy, and in particular #1728.

grpc-js: Add support for ipv4 and ipv6 schemes

---

packages/grpc-js/src/client.ts

`instanceof Function` does not work in vm context, related to https://github.com/grpc/grpc-node/pull/204 https://github.com/grpc/grpc-node/pull/795 and https://github.com/grpc/grpc-node/pull/1759

grpc-js: stricter function check than instanceof

---

packages/grpc-native-core/binding.gyp
packages/grpc-native-core/build.yaml
packages/grpc-native-core/package.json
packages/grpc-native-core/src/grpc_extension.js

native: Fix reference to node-pre-gyp

---

run-tests.sh
test/aarch64/prepare_qemu.sh
test/kokoro/linux_aarch64.cfg
test/kokoro_linux_aarch64.sh

Run unit tests under an aarch64 docker container and use qemu to emulate. Similar approach is already being used for several protobuf languages and for grpc-java and grpc-go.

Add CI tests for linux aarch64 (and run them under an emulator).

---

packages/grpc-js/src/subchannel.ts

The purpose of transitioning to TRANSIENT_FAILURE here is to drop the connections that the subchannel is using, but an IDLE subchannel also doesn't have an active connection, making that transition pointless. Plus, the subchannel will immediately transition back to IDLE because there is no running backoff timer. The result is pointless log spam, as can be seen in https://github.com/googleapis/nodejs-pubsub/issues/1135#issuecomment-828023182 in the fourth log chunk.

grpc-js: Don't transition out of idle when discarding subchannels

---

packages/grpc-js/package.json
packages/grpc-js/src/call-stream.ts

This is a different approach to solving the problem I tried to fix in #1705.

grpc-js: Look for ECONNRESET errors by checking the error code

---

packages/grpc-js/package.json
packages/grpc-js/src/client.ts

This is the same change as in #1786, but for grpc-js.

grpc-js: Change function check to handle async functions

---

packages/grpc-native-core/src/client_interceptors.js

Current check is not working for async functions:
```js
toString.call(async function() {}); // [object AsyncFunction]
```

fix(grpc-native-core): incomplete function check

---

packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/deadline-filter.ts
packages/grpc-js/src/filter-stack.ts
packages/grpc-js/src/filter.ts
packages/grpc-js/src/service-config.ts

This is the grpc-js side of the timeout part of [proposal A31](https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md): the mechanism for applying a timeout from a service config to each individual request. The xDS side uses xDS v3-specific fields, so I will do that after #1765 is merged.
I changed the method config definition to more closely match [the spec](https://github.com/grpc/grpc/blob/master/doc/service_config.md). The validation code still accepts the same inputs it accepted before, so that shouldn't break anything.
This puts the deadline filter in a weird state. It already had some implicit coupling with the deadline exposed by the call stream class, but now that deadline can change and the filter needs to take action when that happens. I …

grpc-js: Apply timeouts from service configs

---

run-tests.sh

Without the native library in this branch, this step may not be needed at all.

Don't clean after testing on each Node version

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/resolver-xds.ts
packages/grpc-js-xds/src/route-action.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/metadata.ts
packages/grpc-js/test/test-deadline.ts
test/kokoro/xds-interop.cfg
test/kokoro/xds-v3-interop.cfg

And add the corresponding interop test. This is the xDS side of [A31](https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md#supported-fields), following up from #1785.

grpc-js-xds: Propagate timeouts from xDS responses to method config

---

test/kokoro_linux_aarch64.sh

Workaround for https://github.com/grpc/grpc-node/issues/1795

Workaround "key too small" problem in arm64 tests

---

test/api/interop_extra_test.js

Increasing one more timeout. With this change, the emulated tests suite will finally be green (based on a few adhoc runs).
part 1: https://github.com/grpc/grpc-node/pull/1803
Example green runs:
https://source.cloud.google.com/results/invocations/b59c8b3d-c57c-4360-8b51-ee2162c7ad37/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests;query=should%20receive%20all%20messages%20in%20a%20long%20stream;group=js%20client%20-%3E%20native%20server%20Interop-adjacent%20tests;test=should%20receive%20all%20messages%20in%20a%20long%20stream;row=3
https://source.cloud.google.com/results/invocations/e38ca58a-1b14-4221-a6d8-199d3300f6b0/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests;query=should%20receive%20all%20messages%20in%20a%20long%20stream;group=js%20client%20-%3E%20native%20server%20Interop- …

Increase timeout for tests that timeout under emulator (part 2)

---

packages/grpc-js/src/index.ts

A solution for the problems described in #1805.

grpc-js: Export ServerErrorResponse type, which is used in public APIs

---

packages/grpc-js-xds/interop/xds-interop-client.ts
packages/grpc-js-xds/scripts/xds.sh
packages/grpc-js-xds/src/load-balancer-cds.ts
packages/grpc-js-xds/src/load-balancer-eds.ts
packages/grpc-js-xds/src/xds-client.ts

This implements [A32: gRPC xDS circuit breaking](https://github.com/grpc/proposal/blob/master/A32-xds-circuit-breaking.md).

grpc-js-xds: Add circuit breaking functionality

---

packages/grpc-js-xds/src/load-balancer-eds.ts
packages/grpc-js-xds/src/load-balancer-lrs.ts
packages/grpc-js-xds/src/load-balancer-xds-cluster-manager.ts
packages/grpc-js/src/call-stream.ts
packages/grpc-js/src/channel.ts
packages/grpc-js/src/filter-stack.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/picker.ts
packages/grpc-js/src/subchannel.ts

The previous pattern of having `FilterStack` objects containing other filter stack objects to combine their contents was inefficient and difficult to work with. The change here is to allow `FilterStack` and `FilterStackFactory` objects to have their contents extended after construction, which should make them easier to work with and make it easier to support future APIs with hooks for providing filters.

grpc-js: Refactor FilterStack usage

---

packages/grpc-tools/package.json

This versions of node-pre-gyp has some issues with some weird proxy configurations that can be solved updating this deprecated package.

(grpc-tools) Update node-pre-gyp dependency

---

tools/release/native/Dockerfile

This doesn't work anymore because the newest version of docker doesn't support the version of Debian we're using in this docker image. And we don't need it anymore; this is only used in the grpc-tools build now, and that doesn't use nested docker containers.

Don't install docker in the docker image

---

TROUBLESHOOTING.md
doc/environment_variables.md
packages/grpc-js/src/constants.ts
packages/grpc-js/src/logging.ts

The new docs are adapted from the core's [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) and [doc/environment_variables.md](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md).
To make the grpc-js behavior more closely match what is described in those docs, it now supports the `NONE` option for `GRPC_VERBOSITY` and negated tracers in the `GRPC_TRACE`.

Document environment variables, improve logging behavior

---

packages/grpc-js/package.json
packages/grpc-js/src/constants.ts
packages/grpc-js/src/logging.ts

Backport the logging changes from #1820 to 1.3.x so that the behavior of the released library is consistent with the documentation.

grpc-js: Backport logging changes to 1.3.x

---

packages/proto-loader/bin/proto-loader-gen-types.ts
packages/proto-loader/golden-generated/echo.ts

Since proto files don't always contain enums and messages, it was possible to get into a state where generated code contained unused imports which caused TS errors. This change makes those imports conditional on the existence of the corresponding definitions in the proto file.
Co-authored-by: Austin Puri <austin.puri@gmail.com>
Co-authored-by: Joe Porpeglia <josephp@spotify.com>

Avoid unused definition imports from proto-loader

---

packages/grpc-js/package.json
packages/grpc-js/src/subchannel.ts

I'm pretty sure that we don't need to keep those timers ref'd to keep the process alive when it needs to be alive, and with the `grpc.keepalive_permit_without_calls` option in particular, they can keep the process open even if gRPC is otherwise unused. I think this will fix #1825.

grpc-js: Unref timers for keepalive functionality

---

packages/proto-loader/bin/proto-loader-gen-types.ts

Closes #1830.
f289c343b3393aad73795c0657415f4160bcdcb5 introduced a bug - the recursive for-loop descended into the first element's nested array and returned that value without iterating over the other members of the array. This means that the code would only work correctly when the protofile contained a definition whose name was alphabetically before the first  first amongst its siblings.
This commit fixes the issue by only returning early when `containsDefinition` returns true.
This change results in no effect on the output of `yarn generate-golden` - it seems that the echo.proto file used to generate the test output has enough cases where the target type appears before a namespace base sibling that the bug is not exposed.

Prevent early return in proto-loader containsDefinition

---

packages/grpc-js/README.md

It seems that it was not clear to some people that we were looking for feature requests for addressing feature parity gaps in grpc-js, so hopefully this will make that clearer.

grpc-js: Add note in README about feature parity requests

---

packages/grpc-js-xds/package.json
packages/grpc-js-xds/src/matcher.ts
packages/grpc-js-xds/src/resolver-xds.ts

This is a correction to existing functionality, according to a conversation in the internal xDS chat room.

grpc-js-xds: case_sensitive flag should not affect regex matcher

---

packages/grpc-js/package.json
packages/grpc-js/src/channel.ts
packages/grpc-js/src/client.ts
packages/grpc-js/src/connectivity-state.ts
packages/grpc-js/src/experimental.ts
packages/grpc-js/src/http_proxy.ts
packages/grpc-js/src/index.ts
packages/grpc-js/src/load-balancer-child-handler.ts
packages/grpc-js/src/load-balancer-pick-first.ts
packages/grpc-js/src/load-balancer-round-robin.ts
packages/grpc-js/src/load-balancer.ts
packages/grpc-js/src/resolver-dns.ts
packages/grpc-js/src/resolver-uds.ts
packages/grpc-js/src/resolver.ts
packages/grpc-js/src/resolving-load-balancer.ts
packages/grpc-js/src/server.ts
packages/grpc-js/src/subchannel-address.ts
packages/grpc-js/src/subchannel-pool.ts
packages/grpc-js/src/subchannel.ts
packages/grpc-js/test/test-client.ts
packages/grpc-js/test/test-resolver.ts

The main changes here are moving the `ConnectivityState` enum and `SubchannelAddress` type (plus related definitions) into separate files so that other files can use them without importing `channel.ts` and `subchannel.ts` respectively. The load balancer registry code also makes the default configurable instead of hardcoding it as pick_first, to avoid a dependency cycle between that code and the pick_first code.
This only addresses dependency cycles in the compiled code, because that's what I had a tool to detect. Plus, dependency cycles that include type-only imports shouldn't really be a problem, as long as the types themselves are not cyclically defined.
This addresses #1821.

grpc-js: Refactor code to eliminate runtime dependency cycles

---

test/kokoro/xds-interop.cfg

Recent test runs have been running up against the current limit and failing. This increase matches a previous increase on master.

grpc-js-xds: Increase interop test timeout

---

test/kokoro/xds-interop.cfg
test/kokoro/xds-v3-interop.cfg

With the timeout test, these are already average something like 2:40 so this goes ahead and gives the jobs a (hopefully) excessive time limit.
We are seeing lots of failures due to hitting the 120 minute timeout set on the v1.3.x branch, so this should be backported to v1.3.x and v1.2.x as well.
cc @murgatroid99 
b/192479958

Increase xDS job timeouts to match Java and Go

---

test/kokoro/xds-interop.cfg

This is essentially a backport of #1840. This branch does not have xDS v3 tests, so there's only one config file to change.

grpc-js-xds: Increase interop test timeout to 6 hours in 1.3.x branch

---

test/kokoro/xds-interop.cfg

#1843 but actually point the PR at the 1.3.x branch this time.

grpc-js-xds: Increase interop test timeout to 6 hours in 1.3.x branch (for real this time)

---

packages/grpc-js/package.json
packages/grpc-js/src/http_proxy.ts

I think #1841 is hitting this error case, but without this log line it's hard to tell what exactly is happening.

grpc-js: Add logging for TLS over proxy connection errors

---

packages/grpc-js/src/logging.ts
packages/grpc-js/test/test-logging.ts

This is an evolution of the change proposed in #1811. With this change, logs at different severity levels are passed to different logger methods, but the default logger still sends them all to `stderr` to preserve the current behavior (though I added severity letters at the beginning of the log lines as core does, to take advantage of the split). This change also falls back to `_logger.error` when other methods are not available, to avoid dropping log messages when using older custom loggers that only implement `error`.
This fixes #1835.

grpc-js: Split out logs for different severity levels
